(function(d){function k(a,b){b===void 0?b=typeof a=="boolean"?{show:a}:a:b.show=a;if(b&&(b.img||b.element)&&!b.pulse)b.pulse=!1;if(b&&b.onAjax!==void 0&&b.show===void 0)b.show=!1;return b}function h(a,b){var c=a.css(b);return c=="auto"?0:parseFloat(c,10)}var f=d.loading=function(a,b){return d("body").loading(a,b,!0)};d.fn.loading=function(a,b,c){var b=k(a,b),g=c?d.extend(!0,{},f,f.pageOptions):f;return this.each(function(){var a=d(this),c=d.extend(!0,{},g,d.metadata?a.metadata():null,b);typeof c.onAjax==
"boolean"?f.setAjax.call(a,c):f.toggle.call(a,c)})};var j={position:"fixed"};d.extend(f,{version:"1.6.4",align:"top-left",pulse:"working error",mask:!1,img:null,element:null,text:"Loading...",onAjax:void 0,delay:0,max:0,classname:"loading",imgClass:"loading-img",elementClass:"loading-element",maskClass:"loading-mask",css:{position:"absolute",whiteSpace:"nowrap",zIndex:1001},maskCss:{position:"absolute",opacity:0.15,background:"#333",zIndex:101,display:"block",cursor:"wait"},cloneEvents:!0,pageOptions:{page:!0,
align:"top-center",css:j,maskCss:j},html:"<div></div>",maskHtml:"<div></div>",maskedClass:"loading-masked",maskEvents:"mousedown mouseup keydown keypress",resizeEvents:"resize",working:{time:1E4,text:"Still working...",run:function(a){var b=a.working,c=this;b.timeout=setTimeout(function(){c.height("auto").width("auto").text(a.text=b.text);a.place.call(c,a)},b.time)}},error:{time:1E5,text:"Task may have failed...",classname:"loading-error",run:function(a){var b=a.error,c=this;b.timeout=setTimeout(function(){c.height("auto").width("auto").text(a.text=
b.text).addClass(b.classname);a.place.call(c,a)},b.time)}},fade:{time:800,speed:"slow",run:function(a){var a=a.fade,b=a.speed,c=this;a.interval=setInterval(function(){c.fadeOut(b).fadeIn(b)},a.time)}},ellipsis:{time:300,run:function(a){var b=a.ellipsis,c=this;b.interval=setInterval(function(){var b=c.text(),d=a.text,e;e=d.indexOf(".");e=e<0?d.length:e;c.text(b.length-e<3?b+".":d.substring(0,e))},b.time)}},type:{time:100,run:function(a){var b=a.type,c=this;b.interval=setInterval(function(){var b=c.text().length,
d=a.text;c.text(b==d.length?d.charAt(0):d.substring(0,b+1))},b.time)}},toggle:function(a){var b=this.data("loading");b?a.show!==!0&&b.off.call(this,b,a):a.show!==!1&&a.on.call(this,a)},setAjax:function(a){if(a.onAjax){var b=this,c=0,d=a.ajax={start:function(){c++||a.on.call(b,a)},stop:function(){--c||a.off.call(b,a,a)}};this.bind("ajaxStart.loading",d.start).bind("ajaxStop.loading",d.stop)}else this.unbind("ajaxStart.loading ajaxStop.loading")},on:function(a,b){var c=a.parent=this.data("loading",
a);if(a.max)a.maxout=setTimeout(function(){a.off.call(c,a,a)},a.max);if(a.delay&&!b)return a.timeout=setTimeout(function(){delete a.timeout;a.on.call(c,a,!0)},a.delay);if(a.mask)a.mask=a.createMask.call(c,a);a.display=a.create.call(c,a);a.img?a.initImg.call(c,a):a.element?a.initElement.call(c,a):a.init.call(c,a);c.trigger("loadingStart",[a])},initImg:function(a){var b=this;a.imgElement=d('<img src="'+a.img+'"/>').bind("load",function(){a.init.call(b,a)});a.display.addClass(a.imgClass).append(a.imgElement)},
initElement:function(a){a.element=d(a.element).clone(a.cloneEvents).show();a.display.addClass(a.elementClass).append(a.element);a.init.call(this,a)},init:function(a){a.place.call(a.display,a);a.pulse&&a.initPulse.call(this,a)},initPulse:function(a){d.each(a.pulse.split(" "),function(){a[this].run.call(a.display,a)})},create:function(a){var b=d(a.html).addClass(a.classname).css(a.css).appendTo(this);if(a.text&&!a.img&&!a.element)b.text(a.originalText=a.text);d(window).bind(a.resizeEvents,a.resizer=
function(){a.resize(a)});return b},resize:function(a){a.parent.box=null;a.mask&&a.mask.hide();a.place.call(a.display.hide(),a);a.mask&&a.mask.show().css(a.parent.box)},createMask:function(a){var b=a.measure.call(this.addClass(a.maskedClass),a);a.handler=function(b){return a.maskHandler(b,a)};d(document).bind(a.maskEvents,a.handler);return d(a.maskHtml).addClass(a.maskClass).css(b).css(a.maskCss).appendTo(this)},maskHandler:function(a,b){var c=d(a.target).parents().andSelf();if(c.filter("."+b.classname).length!=
0)return!0;return!b.page&&c.filter("."+b.maskedClass).length==0},place:function(a){var b=a.align,c="top",g="left";typeof b=="object"?b=d.extend(a.calc.call(this,c,g,a),b):(b!="top-left"&&(b=b.split("-"),b.length==1?c=g=b[0]:(c=b[0],g=b[1])),this.hasClass(c)||this.addClass(c),this.hasClass(g)||this.addClass(g),b=a.calc.call(this,c,g,a));this.show().css(a.box=b)},calc:function(a,b,c){var c=d.extend({},c.measure.call(c.parent,c)),g=d.boxModel?this.height():this.innerHeight(),i=d.boxModel?this.width():
this.innerWidth();if(a!="top"){var e=c.height-g;a=="center"?e/=2:a!="bottom"?e=0:d.boxModel&&(e-=h(this,"paddingTop")+h(this,"paddingBottom"));c.top+=e}b!="left"&&(e=c.width-i,b=="center"?e/=2:b!="right"?e=0:d.boxModel&&(e-=h(this,"paddingLeft")+h(this,"paddingRight")),c.left+=e);c.height=g;c.width=i;return c},measure:function(a){return this.box||(this.box=a.page?a.pageBox(a):a.elementBox(this,a))},elementBox:function(a){if(a.css("position")=="absolute")var b={top:0,left:0};else b=a.position(),b.top+=
h(a,"marginTop"),b.left+=h(a,"marginLeft");b.height=a.outerHeight();b.width=a.outerWidth();return b},pageBox:function(a){function b(a,b){var i=document;if(a){var e=b.toLowerCase(),f=d(i)[e](),e=d(window)[e]();return f-h(d(i.body),"marginTop")>e?f:e}f="client"+b;return Math.max(i.documentElement[f],i.body[f])}a=d.boxModel&&a.css.position!="fixed";return{top:0,left:0,height:b(a,"Height"),width:b(a,"Width")}},off:function(a,b){this.data("loading",null);a.maxout&&clearTimeout(a.maxout);if(a.timeout)return clearTimeout(a.timeout);
a.pulse&&a.stopPulse.call(this,a,b);if(a.originalText)a.text=a.originalText;a.mask&&a.stopMask.call(this,a,b);d(window).unbind(a.resizeEvents,a.resizer);a.display&&a.display.remove();a.parent&&a.parent.trigger("loadingEnd",[a])},stopPulse:function(a,b){d.each(a.pulse.split(" "),function(){var c=a[this];c.end&&c.end.call(b.display,a,b);c.interval&&clearInterval(c.interval);c.timeout&&clearTimeout(c.timeout)})},stopMask:function(a,b){this.removeClass(b.maskedClass);d(document).unbind(a.maskEvents,a.handler);
a.mask.remove()}})})(jQuery);
