/*
 Copyright (c) 2009-2011 Petr Vostrel (http://petr.vostrel.cz/)
 Dual licensed under the MIT (MIT-LICENSE.txt)
 and GPL (GPL-LICENSE.txt) licenses.

 jQuery Reel
 http://jquery.vostrel.cz/reel
 Version: 1.1.3
 Updated: 2011-05-08

 Requires jQuery 1.4.2 or higher
*/
jQuery.reel||function(c,Sa,L,h){function s(j){return c.reel.instances.length?c.reel.instances.first().data(j):null}function B(c){return Ta&&"data:image/gif;base64,R0lGODlh"+c}function C(c){return"http://code.vostrel.cz/"+c}function G(c){return+c.toFixed(4)}function V(c,a,l){return M(c,N(a,l))}c.reel={version:"1.1.3",def:{footage:6,frame:1,frames:36,hint:"",horizontal:!0,hotspot:h,indicator:0,klass:"",loops:!0,reversed:h,spacing:0,stitched:0,suffix:"-reel",tooltip:"",area:h,brake:0.5,clickfree:!1,
cw:!1,delay:-1,directional:!1,draggable:!0,entry:h,graph:h,image:h,images:[],inversed:!1,laziness:6,monitor:h,opening:0,orbital:0,path:"",preloader:4,rebound:0.5,revolution:h,row:1,rows:0,speed:0,step:h,steps:h,tempo:36,timeout:2,throwable:!0,vertical:!1,wheelable:!0}};c.fn.reel=function(j){var a=c.extend({},c.reel.def,j),j=function(f){var l=[];f.filter(Va).each(function(){var d=c(this),e=a.images.length&&a.images||a.image||d.attr(Aa),f=W(d.css(Ba)),m=W(d.css(Ca));e&&!(e==Da||!f||!m)&&l.push(d)});
f.filter(O+("."+t)).each(function(){l.push(c(this))});return c(l)}(this),za=[];a.reversed&&(a.cw=!0);a.tooltip&&(a.hint=a.tooltip);a.hotspot&&(a.area=a.hotspot);j.each(function(){var f=c(this),j=f.data(),d=function(a,b){j[a]=b;f.trigger("store",[a,b]);return b},e=function(a){var b=j[a];f.trigger("recall",[a,b]);return b},u={setup:function(x){if(f.hasClass(t))return m.call(x);var b=f.attr(Aa),g=d(P,f.attr(P)||f.attr(P,t+"-"+ +new Date).attr(P)),i=f.attr("style"),n=a.images,p=a.stitched,Ea=a.loops,
j={x:W(f.css(Ba)),y:W(f.css(Ca))},h=d(Fa,a.orbital&&a.footage||a.rows<=1&&n.length||a.frames),k=p?1:Ga(h/a.footage),o={display:"block",width:j.x,height:j.y},g="#"+g+a.suffix,s=f.attr("class"),q={position:"relative",width:j.x,height:j.y},q=c(Q,{id:g.substr(1),"class":s+ga+Wa,css:q}),o=f.wrap(q).attr({"class":t}).css(o).bind(u);za.push((c.reel.instances.push(o[0])&&o)[0]);d(Ha,n.length&&n.length||a.image||b.replace(/^(.*)\.(jpg|jpeg|png|gif)$/,"$1"+a.suffix+".$2"));d(Ia,s);d(v,a.frame);d(Ja,a.spacing);
d(y,j);d(l,0);d(ha,a.steps||a.frames);d(X,a.revolution||p/2||j.x*2);d(ia,k);d(Y,1/(h-(Ea&&!p?0:1)));d(Xa,1/M(h,e(ha)));d(ja,p);d(Ka,p-(Ea?0:j.x));d(Z,g);d(D,d(ka,a.speed)<0);d(H,0);d(I,a.vertical);d(w,(a.row-1)/(a.rows-1));d($,r(1)*(!a.cw&&!p?-1:1));d(R,!1);d(La,a.brake);d(la,!!a.orbital);d(z,a.tempo/(c.reel.lazy?a.laziness:1));d(aa,0);d(Ma,{src:b,style:i||Da});A.bind(E,u.tick);m.call(x);f.trigger("start")},teardown:function(a){f.unbind(k).unbind(u);var b=f.data("events"),d=f.clone().attr(f.data(Ma)).css({background:"transparent"}).removeClass(t).addClass(e(Ia)),
i;for(i in b)c.each(b[i],function(a,b){d.bind(i+"."+b.namespace,b.handler,b.data)});c("img:"+ma,f.parent()).remove();c.reel.instances=c.reel.instances.not("#"+f.attr(P));c(e(Z)).before(d).detach();o=[0,0];A.unbind(E,u.tick).unbind(E,u.opening_tick);ba.unbind(na).unbind(oa);m.call(a)},start:function(){var x=e(y),b=e(Fa),g=M(b,e(ha)),g=d(l,1/g*((a.step||a.frame)-1));d(v,g*b+1);f.attr("id");b=f.parent();g=c(Q,{"class":Ya,css:{position:ca,left:0,top:0,width:x.x,height:x.y,background:pa,opacity:0}}).appendTo(b);
g=d(Na,c(a.area||g));c.reel.touchy?(f.css({WebkitUserSelect:"none",WebkitBackgroundSize:a.images.length?"auto":e(ja)&&e(ja)+"px "+x.y+"px"||x.x*a.footage+"px "+x.y*e(ia)*(a.rows||1)*(a.directional?2:1)+"px"}),g.bind(Za,function(a){f.trigger("down",[a.originalEvent.touches[0].clientX,a.originalEvent.touches[0].clientY,!0])}).bind($a,function(b){f.trigger("slide",[b.originalEvent.touches[0].clientX,b.originalEvent.touches[0].clientY,!0]);return!(a.rows>1||a.orbital||e(R))}).bind(ab,function(){f.trigger("up",
[!0]);return!1}).bind(bb,function(){f.trigger("up",[!0]);return!1})):g.css({cursor:"url("+Oa+"), "+qa}).bind(cb,function(a,b){f.trigger("wheel",[b]);return!1}).bind(db,function(){f.trigger("play")}).bind(a.clickfree?eb:fb,function(a){f.trigger("down",[a.clientX,a.clientY]);return!1}).bind(a.clickfree?gb:"",function(){f.trigger("up");return!1}).disableTextSelect();a.hint&&g.attr(hb,a.hint);a.monitor&&b.append(B=c(Q,{"class":ib,css:{position:ca,left:0,top:0}}))||(B=c());a.indicator&&b.append(N("x"));
a.rows>1&&a.indicator&&b.append(N("y"));f.trigger("preload")},preload:function(d){var b=e(y),g=f.parent(),i=e(Ha),n=a.images,p=!n.length?[i]:[].concat(n),j=f[0];j.frames=p.length;j.preloaded=0;f.trigger("stop");for(g.append(C=c(Q,{"class":jb,css:{position:ca,left:0,top:b.y-a.preloader,height:a.preloader,overflow:ma,backgroundColor:pa}}));p.length;){var l=a.path+p.shift(),h=c(new Image).hide().bind("load"+k,function(){j.preloaded++;c(this).unbind(k);C.css({width:1/j.frames*j.preloaded*b.x});j.frames==
j.preloaded&&(C.remove(),n.length||f.css({backgroundImage:"url("+(a.path+i)+")"}),f.attr({src:kb}).trigger(a.rows>1&&!a.stitched?"rowChange":"frameChange").trigger("loaded").trigger("opening"),m.call(d))});g.append(h);setTimeout(function(a,b){return function(){a.attr({src:b})}}(h,l),0)}},tick:function(c){var b=e(H);if(S)var g=G(b-e(La)/s(z)*S),b=!(b*g<=0||b<r(g))&&d(H,b>r(e(ka))?g:S=q=0);B.text(e(a.monitor));b&&S++;q&&q++;o.push(0)&&o.shift();ra=!0;if(q&&!b)return m.call(c);if(e(da))return m.call(c,
J());var g=e($),i;i=e(D);i=r(1)*(i?-1:1);g*=i;i=(e(sa)?b:r(e(ka))+b)/s(z);b=e(l);g=d(l,b-i*g);m.call(c);g!=b&&f.trigger("fractionChange")},opening:function(){var c=a.entry||a.speed,b=e(l),g=a.opening;d(l,b-c*a.opening);d(aa,g*s(z));A.bind(E,u.opening_tick)},opening_tick:function(c){var b=(a.entry||a.speed)/s(z)*(a.cw?-1:1),g=e(l);d(l,G(g+b));b=d(aa,e(aa)-1);f.trigger("fractionChange");m.call(c);b>1||(A.unbind(E,u.opening_tick),L())},play:function(a){var b=d(ta,!0);d(sa,!b);q=0;m.call(a)},pause:function(a){d(ta,
!1);J();m.call(a)},stop:function(a){var b=d(sa,!0);d(ta,!b);m.call(a)},down:function(c,b,g,i){a.draggable&&(d(da,e(v)),d(H,0),ea=fa(b,g,e(l),e(X),e(w)),J(),o=[0,0],i||(ba.css({cursor:"url("+lb+"), "+qa}).bind(oa,function(a){f.trigger("slide",[a.clientX,a.clientY]);m.call(a);return!1}),a.clickfree||ba.bind(na,function(a){f.trigger("up");m.call(a)})));m.call(c)},up:function(c,b){if(!a.draggable)return m.call(c);d(da,!1);d(R,!1);var g=d(H,!a.throwable?0:r(o[0]+o[1])/60);S=g?1:0;g?q=0:J();o=[0,0];!b&&
ba.unbind(na).unbind(oa)&&e(Na).css({cursor:"url("+Oa+"), "+qa});m.call(c)},slide:function(j,b,g){if(a.draggable&&ra){ra=!1;J();var i={x:b-ea.x,y:g-ea.y};if(r(i.x)>0||r(i.y)>0){ea={x:b,y:g};var n=e(X),p=e(Pa),h=e(I),k=d(l,O(h?g-p.y:b-p.x,e(ua),n,e(va),e(wa),e($)));d(R,e(R)||e(v)!=e(da));(i=o.push(h?i.y:i.x||0)&&o.shift()&&(h?i.y:i.x||0))&&d(D,i<0);a.orbital&&e(la)&&(d(I,r(g-p.y)>r(b-p.x)),p=fa(b,g,k,n,e(w)));if(a.rows>1){var i=e(y).y,h=e(Qa),q=-h*i;d(w,G(c.reel.math.envelope(g-p.y,h,i,q,q+i,-1)))}!(k%
1)&&!a.loops&&fa(b,g,k,n,e(w));f.trigger("fractionChange")}}m.call(j)},wheel:function(c,b){if(!a.wheelable)return m.call(c);var g=Ga(mb(r(b))/2),g=r(g)*(b>0?-1:1),i=0.2*e(X);fa(h,h,e(l),i,e(w));d(l,O(g,e(ua),i,e(va),e(wa),e($)));g&&d(D,g<0);d(H,0);J();m.call(c);f.trigger("fractionChange");return!1},fractionChange:function(j,b){var b=!b?e(l):d(l,b),b=a.loops?b-T(b):V(0,1,b),b=d(l,G(b)),g=e(v),i=d(v,1+T(b/e(Y))),n=a.orbital;d(la,!!n&&(i<=n||i>=a.footage-n+2));!a.loops&&a.rebound&&(!q&&!(b%1)?xa++:xa=
0,xa>=a.rebound*1E3/s(z)&&d(D,!e(D)));var n=e(y),h=(e(I)?n.y:n.x)-a.indicator,k=V(0,h,U(c.reel.math.interpolate(b,-1,h+2))),k=!a.cw||a.stitched?k:h-k;c("."+(ya+".x"),e(Z)).css(e(I)?{left:0,top:k}:{left:k,top:n.y-a.indicator});a.rows>1&&(n=e(y).y-a.indicator,n=V(0,n,U(c.reel.math.interpolate(e(w),-1,n+2))),c("."+(ya+".y"),e(Z)).css({top:n}));if(i==g&&i!=1)return m.call(j);f.trigger(a.rows>1?"rowChange":"frameChange");m.call(j)},rowChange:function(c,b){var g=T(e(l)/e(Y))+1,b=d(w,V(0,1,G(b!=h?(b-1)/
(a.rows-1):e(w))));d(v,g+(a.rows<=1?0:U(b*(a.rows-1))*a.frames));m.call(c);f.trigger("frameChange")},frameChange:function(c,b){var g=!b?e(l):d(l,G(e(Y)*(b-1))),b=d(v,U(b?b:e(v))),i=a.images,j=a.footage,h=e(y),k=a.horizontal;e(I)&&(b=a.inversed?j+1-b:b,b+=j);if(i.length)f.attr({src:a.path+i[b-1]});else{if(a.stitched)i=[-U(g*e(Ka))+K,0+K];else{var g=b%j-1,g=g<0?j-1:g,o=T((b-0.1)/j);o+=a.rows>1?0:e(D)?0:e(ia);j=e(Ja);o*=(k?h.y:h.x)+j;h=g*((k?h.x:h.y)+j);i=i.length?[0,0]:k?[-h+K,-o+K]:[-o+K,-h+K]}f.css({backgroundPosition:i.join(ga)})}m.call(c)}},
m=function(a){Ra||delete this;return a},q,S=0,J=function(){clearTimeout(F);A.unbind(E,u.opening_tick);f.trigger("play");return q=-a.timeout*s(z)},F,L=function(){F=setTimeout(function(){f.trigger("play")},a.delay*1E3||0)},B,C,N=function(d){return c(Q,{"class":[ya,d].join(ga),css:{width:a.indicator,height:a.indicator,overflow:ma,top:e(y).y-a.indicator,left:0,position:ca,backgroundColor:pa}})},xa=0,ea={x:0,y:0},o=o=[0,0],O=a.graph||c.reel.math[a.loops?"hatch":"envelope"],fa=function(e,b,c,f,j){d(ua,
c);d(Qa,j);d(va,a.loops?0:-c*f);d(wa,a.loops?f:f-c*f);return e&&d(Pa,{x:e,y:b})||h},ra=!0,ba=c.browser.opera?A:c.unique(A.add(Sa.top.document));u.setup()});F=F||function Ua(){var a=+new Date,e=s(z);return e?(A.trigger(E),c.reel.cost=(+new Date+c.reel.cost-a)/2,F=setTimeout(Ua,M(4,1E3/e-c.reel.cost))):F=h}();return c(za)};c.reel.math={envelope:function(c,a,h,f,k,d){return a+M(f,N(k,-c*d))/h},hatch:function(c,a,h,f,k,d){c=a+-((c<f?k:0)+c%k)*d/h;return c-T(c)},interpolate:function(c,a,h){return a+c*
(h-a)}};c.reel.touchy=/iphone|ipod|ipad|android/i.test(navigator.userAgent);c.reel.lazy=/iphone|ipod|android/i.test(navigator.userAgent);c.reel.instances=c();c.reel.cost=0;c.reel.leader=s;(function(h){c.each(h,function(){c.fn[this]||(c.fn[this]=function(){return this})})})("mousewheel disableTextSelect enableTextSelect".split(/ /));var A=c(L),L=+c.browser.version.split(".").slice(0,2).join("."),Ra=c.browser.msie,Ta=!(Ra&&L<8),qa="ew-resize",F,t="jquery-reel",Wa=t+"-overlay",ya=t+"-indicator",jb=t+
"-preloader",ib=t+"-monitor",Ya=t+"-interface",kb=B("CAAIAIAAAAAAAAAAACH5BAEAAAAALAAAAAAIAAgAAAIHhI+py+1dAAA7")||C("blank.gif"),Oa=B("EAAQAJECAAAAAP///////wAAACH5BAEAAAIALAAAAAAQABAAQAI3lC8AeBDvgosQxQtne7yvLWGStVBelXBKqDJpNzLKq3xWBlU2nUs4C/O8cCvU0EfZGUwt19FYAAA7")||C("jquery.reel.cursor-drag.gif"),lb=B("EAAQAJECAAAAAP///////wAAACH5BAEAAAIALAAAAAAQABAAQAIslI95EB3MHECxNjBVdE/5b2zcRV1QBabqhwltq41St4hj5konmVioZ6OtEgUAOw==")||C("jquery.reel.cursor-drag-down.gif"),U=Math.round,T=Math.floor,Ga=Math.ceil,
N=Math.min,M=Math.max,r=Math.abs,mb=Math.sqrt,W=parseInt,Na="area",Ma="backup",D="backwards",Y="bit",La="brake",la="center",Ia="classes",da="clicked",Pa="clicked_location",ua="clicked_on",Qa="clicked_row",$="cwish",y="dimensions",l="fraction",v="frame",Fa="frames",wa="hi",ma="hidden",Ha="image",aa="opening_ticks",va="lo",ta="playing",R="reeling",X="revolution",w="row",ia="rows",Ja="spacing",ka="speed",Z="stage",ha="steps",ja="stitched",Ka="stitched_travel",sa="stopped",z="tempo",H="velocity",I="vertical",
Xa="wheel_step",k=".reel",db="dblclick"+k,fb="mousedown"+k,eb="mouseenter"+k,gb="mouseleave"+k,oa="mousemove"+k,na="mouseup"+k,cb="mousewheel"+k,E="tick"+k,bb="touchcancel"+k,ab="touchend"+k,Za="touchstart"+k,$a="touchmove"+k,Da="",ga=" ",ca="absolute",O="div",Q="<"+O+"/>",Ca="height",pa="#000",P="id",Va="img",K="px",Aa="src",hb="title",Ba="width"}(jQuery,window,document);
