(function(f,c){f.ModPlug=f.ModPlug||{plugin:function(e,a){if(!e||f[e]||f.fn[e])return!e?1:f[e]?2:3;var d=f.extend({},{statics:{},methods:{},defaultStatic:c,defaultMethod:c},a),b=function(){var a,i;a=Array.prototype.slice.call(arguments);i=d.defaultStatic instanceof Function?d.defaultStatic.apply(this,a):d.defaultStatic;if(b[i]instanceof Function)return b[i].apply(this,a);f.error("Static method defaulted to '"+i+"' does not exist on 'jQuery."+e+"'")},i={},n={addStatics:function(a){f.extend(b,a);b._mp_api=
n;return this},addMethods:function(a){f.extend(i,a);return this}};n.addStatics(d.statics).addMethods(d.methods);f[e]=b;f.fn[e]=function(a){var b,c;if(i[a]instanceof Function)return b=Array.prototype.slice.call(arguments,1),i[a].apply(this,b);b=Array.prototype.slice.call(arguments);c=d.defaultMethod instanceof Function?d.defaultMethod.apply(this,b):d.defaultMethod;if(i[c]instanceof Function)return i[c].apply(this,b);f.error("Method '"+a+"' defaulted to '"+c+"' does not exist on 'jQuery."+e+"'")};return 0},
module:function(e,a){if(!f[e]||!f[e]._mp_api)return!f[e]?1:2;var d=f.extend({},{statics:{},methods:{}},a);f[e]._mp_api.addStatics(d.statics).addMethods(d.methods);return 0}}})(jQuery);
(function(f,c,e){var a=f.Fracs=f.Fracs||{},d=c(f),b=c(document);a.Rect=function(b,d,e,c){if(!(this instanceof a.Rect))return new a.Rect(b,d,e,c);this.left=Math.round(b);this.top=Math.round(d);this.width=Math.round(e);this.height=Math.round(c);this.right=this.left+this.width;this.bottom=this.top+this.height};a.Rect.prototype={equals:function(a){return this.left===a.left&&this.top===a.top&&this.width===a.width&&this.height===a.height},area:function(){return this.width*this.height},intersection:function(b){var d=
Math.max(this.left,b.left),c=Math.min(this.right,b.right),f=Math.max(this.top,b.top),b=Math.min(this.bottom,b.bottom);c-=d;b-=f;return c>=0&&b>=0?a.Rect(d,f,c,b):e},envelope:function(b){var d=Math.min(this.left,b.left),e=Math.max(this.right,b.right),c=Math.min(this.top,b.top),b=Math.max(this.bottom,b.bottom);return a.Rect(d,c,e-d,b-c)},fracs:function(){return a.Fractions.ofRect(this)}};a.Rect.ofDocument=function(){return a.Rect(0,0,b.width(),b.height())};a.Rect.ofViewport=function(){return a.Rect(d.scrollLeft(),
d.scrollTop(),d.width(),d.height())};a.Rect.ofElement=function(b){var b=c(b),d;if(!b.is(":visible"))return a.Rect(0,0,-1,0);d=b.offset();return a.Rect(d.left,d.top,b.outerWidth(),b.outerHeight())}})(window,jQuery);
(function(f,c,e){var a=f.Fracs=f.Fracs||{};a.Fractions=function(d,b,i,c,f,g){if(!(this instanceof a.Fractions))return new a.Fractions(d,b,i,c,f,g);!d||!b||!i||!c||!f||!g?(this.rects=e,this.possible=this.viewport=this.visible=0):(this.rects={document:d,element:b,viewport:i},this.visible=c,this.viewport=f,this.possible=g)};a.Fractions.prototype={equals:function(a){return this.fracsEqual(a)&&this.rectsEqual(a)},fracsEqual:function(a){return this.visible===a.visible&&this.viewport===a.viewport&&this.possible===
a.possible},rectsEqual:function(a){return!this.rects||!a.rects?this.rects===a.rects:this.rects.document.equals(a.rects.document)&&this.rects.element.equals(a.rects.element)&&this.rects.viewport.equals(a.rects.viewport)}};a.Fractions.ofRect=function(d,b){var c,e,f,g,j,b=b||a.Rect.ofViewport();c=d.intersection(b);if(!c)return a.Fractions();e=a.Rect(c.left-d.left,c.top-d.top,c.width,c.height);f=a.Rect(c.left-b.left,c.top-b.top,c.width,c.height);g=c.area();j=Math.min(d.width,b.width)*Math.min(d.height,
b.height);return a.Fractions(c,e,f,g/d.area(),g/b.area(),g/j)};a.Fractions.ofElement=function(d,b){return a.Fractions.ofRect(a.Rect.ofElement(d),b)}})(window,jQuery);
(function(f){var c=f.Fracs=f.Fracs||{};c.Cursor=function(e,a){if(!(this instanceof c.Mouse))return new c.Mouse(e,a);this.distX=e;this.distY=a;this.distMin=Math.min(e,a);this.distMax=Math.max(e,a)};c.Cursor.prototype={equals:function(c){return this.distX===c.distX&&this.distY===c.distY},dist:function(){return Math.sqrt(this.distX*this.distX+this.distY*this.distY)}};c.Cursor.ofRect=function(e,a,d){return c.Cursor(e<d.left?d.left-e:e>d.right?e-d.right:0,a<d.top?d.top-a:a>d.bottom?a-d.bottom:0)};c.Cursor.ofElement=
function(e,a,d){return c.Cursor.ofRect(e,a,c.Rect.ofElement(d))}})(window,jQuery);
(function(f,c,e){var a=f.Fracs=f.Fracs||{},d=c(f);a.Callbacks=function(){if(!(this instanceof a.Callbacks))return new a.Callbacks;this.callbacks=[]};a.Callbacks.prototype={size:function(){return this.callbacks.length},bind:function(a){a instanceof Function&&c.inArray(a,this.callbacks)===-1&&this.callbacks.push(a)},unbind:function(a){a instanceof Function?(a=c.inArray(a,this.callbacks),a>=0&&this.callbacks.splice(a,1)):this.callbacks=[]},trigger:function(a,d){c.each(this.callbacks,function(c,e){e.apply(a,
d)})}};a.FracsCallbacks=function(b){if(!(this instanceof a.FracsCallbacks))return new a.FracsCallbacks(b);this.callbacks=[];this.element=b;this.prevFracs=this.fracs=e;this.checkProxy=c.proxy(this.check,this);this.autoCheck()};a.FracsCallbacks.prototype=c.extend({},a.Callbacks.prototype,{trigger:function(){a.Callbacks.prototype.trigger.call(this,this.element,[this.fracs,this.prevFracs])},check:function(){var b=this.element instanceof a.Rect?this.element:a.Rect.ofElement(this.element),b=a.Fractions.ofRect(b);
return!this.fracs||!this.fracs.equals(b)?(this.prevFracs=this.fracs,this.fracs=b,this.trigger(),true):false},autoCheck:function(a){d[a===false?"unbind":"bind"]("resize scroll load",this.checkProxy)}});a.ScrollStateCallbacks=function(){if(!(this instanceof a.ScrollStateCallbacks))return new a.ScrollStateCallbacks;this.callbacks=[];this.prevState=this.state=e;this.checkProxy=c.proxy(this.check,this);this.autoCheck()};a.ScrollStateCallbacks.prototype=c.extend({},a.Callbacks.prototype,{trigger:function(){a.Callbacks.prototype.trigger.call(this,
f,[this.state,this.prevState])},check:function(){var b=a.ScrollState();return!this.state||!this.state.equals(b)?(this.prevState=this.state,this.state=b,this.trigger(),true):false},autoCheck:function(a){d[a===false?"unbind":"bind"]("resize scroll load",this.checkProxy)}});a.GroupCallbacks=function(b,d,f){if(!(this instanceof a.GroupCallbacks))return new a.GroupCallbacks(b,d,f);this.callbacks=[];this.group=a.Group(b);this.type=d;this.property=f;this.prevBest=this.best=e;this.checkProxy=c.proxy(this.check,
this);this.autoCheck()};a.GroupCallbacks.prototype=c.extend({},a.Callbacks.prototype,{trigger:function(){a.Callbacks.prototype.trigger.call(this,this.group,[this.best,this.prevBest])},check:function(){var a=this.group[this.type](this.property),a=a.elements.length===0||a.value===0?e:a.elements[0];return!this.best||this.best!==a?(this.prevBest=this.best,this.best=a,this.trigger(),true):false},autoCheck:function(a){d[a===false?"unbind":"bind"]("resize scroll load",this.checkProxy)}});a.CursorCallbacks=
function(d){if(!(this instanceof a.CursorCallbacks))return new a.CursorCallbacks(d);this.callbacks=[];this.element=d;this.prevCursor=this.cursor=e;this.checkProxy=c.proxy(this.check,this);this.autoCheck()};a.CursorCallbacks.prototype=c.extend({},a.Callbacks.prototype,{trigger:function(){a.Callbacks.prototype.trigger.call(this,this.element,[this.cursor,this.prevCursor])},check:function(d){d=a.Cursor.ofElement(d.pageX,d.pageY,this.element);return!this.cursor||!this.cursor.equals(d)?(this.prevCursor=
this.cursor,this.cursor=d,this.trigger(),true):false},autoCheck:function(a){d[a===false?"unbind":"bind"]("cursormove",this.checkProxy)}})})(window,jQuery);
(function(f,c,e){var a=f.Fracs=f.Fracs||{},d=c(f),b=c("html,body");a.ScrollState=function(d,b,c,f,j,o){if(!(this instanceof a.ScrollState))return new a.ScrollState;var p=a.Rect.ofDocument(),h=a.Rect.ofViewport(),q=p.width-h.width,k=p.height-h.height;this.width=d||q<=0?e:h.left/q;this.height=b||k<=0?e:h.top/k;this.left=c||h.left;this.top=f||h.top;this.right=j||p.right-h.right;this.bottom=o||p.bottom-h.bottom};a.ScrollState.prototype={equals:function(a){return this.width===a.width&&this.height===a.height&&
this.left===a.left&&this.top===a.top&&this.right===a.right&&this.bottom===a.bottom}};a.ScrollState.scrollTo=function(a,d,c){c=isNaN(c)?1E3:c;b.stop(true).animate({scrollLeft:a,scrollTop:d},c)};a.ScrollState.scroll=function(b,c,e){a.ScrollState.scrollTo(d.scrollLeft()+b,d.scrollTop()+c,e)};a.ScrollState.scrollToRect=function(d,b,c,e){a.ScrollState.scrollTo(d.left-(b||0),d.top-(c||0),e)};a.ScrollState.scrollToElement=function(d,b,c,e){d=a.Rect.ofElement(d);a.ScrollState.scrollToRect(d,b,c,e)}})(window,
jQuery);
(function(f,c,e){var a=f.Fracs=f.Fracs||{};a.Element=function(d){if(!(this instanceof a.Element))return new a.Element(d);this.element=d;this.prevRect=this.rect=this.prevFracs=this.fracs=e;this.update()};a.Element.prototype={update:function(){var d=a.Fractions.ofElement(this.element),b=a.Rect.ofElement(this.element),c=false;if(!this.fracs||!this.fracs.equals(d))this.prevFracs=this.fracs,this.fracs=d,c=true;if(!this.rect||!this.rect.equals(b))this.prevRect=this.rect,this.rect=b,c=true;return c}}})(window,jQuery);
(function(f,c,e){var a=f.Fracs=f.Fracs||{},d=["possible","visible","viewport"],b="width,height,left,right,top,bottom".split(","),i=function(a){if(c.inArray(a,d)>=0)return"fracs";else if(c.inArray(a,b)>=0)return"rect"},n=function(a,d){return a>d},t=function(a,d){return a<d},g=function(a,d,b){var f,g,j=i(d);if(!j)return{elements:[],value:e};c.each(a,function(a,c){var i;c.update();i=j==="fracs"?c.fracs[d]:c.rect[d];g===e||b(i,g)?(f=[c],g=i):i===g&&f.push(c)});return{elements:f,value:g}},j=function(d){var b=
[];c.each(d,function(d,c){b.push(a.Element(c))});return b},o=function(a){var d=[];c.each(a,function(a,b){d.push(b.element)});return d};a.Group=function(d){if(!(this instanceof a.Group))return new a.Group(d);this.elements=j(d)};a.Group.prototype={max:function(a,d){var b=g(this.elements,a,n);return d===true?o(b.elements):b},min:function(a,d){var b=g(this.elements,a,t);return d===true?o(b.elements):b}}})(window,jQuery);
(function(f,c){var e=f.Fracs=f.Fracs||{},a;c.ModPlug.plugin("fracs",{statics:{document:function(){return e.Rect.ofDocument()},fracs:function(a,b){return e.Fractions.ofRect(a,b)},rect:function(a){return e.Rect.ofElement(a)},round:function(a,b){var c;if(isNaN(b)||b<=0)return Math.round(a);c=Math.pow(10,b);return Math.round(a*c)/c},scroll:function(a,b,c){e.ScrollState.scroll(a,b,c);return this},scrollState:function(d){if(!d)return e.ScrollState();a=a||e.ScrollStateCallbacks();a.bind(d);return this},
scrollTo:function(a,b,c){e.ScrollState.scrollTo(a,b,c);return this},viewport:function(){return e.Rect.ofViewport()}},methods:{bind:function(a){return this.each(function(){var b=c(this),f=b.data("fracs");f||(f=e.FracsCallbacks(this),b.data("fracs",f));f.bind(a)})},check:function(){return this.each(function(){var a=c(this).data("fracs");a&&a.check()})},cursor:function(a,b){return a instanceof Function?this.each(function(){e.CursorCallbacks(this).bind(a)}):e.Cursor.ofElement(a,b,this.get(0))},envelope:function(){var a,
b;this.each(function(){b=e.Rect.ofElement(this);a=a?a.envelope(b):b});return a},fracs:function(){return e.Fractions.ofElement(this.get(0))},max:function(a,b){return b?(e.GroupCallbacks(this,"max",a).bind(b),this):c(e.Group(this).maxHtmlElements(a))},min:function(a,b){return b?(e.GroupCallbacks(this,"min",a).bind(b),this):c(e.Group(this).minHtmlElements(a))},rect:function(){return e.Rect.ofElement(this.get(0))},softLink:function(a,b,f){return this.filter("a[href^=#]").each(function(){var n=c(this);
n.click(function(){e.ScrollState.scrollToElement(c(n.attr("href")).get(0),a,b,f)})})},scrollTo:function(a,b,c){e.ScrollState.scrollToElement(this.get(0),a,b,c);return this},unbind:function(a){return this.each(function(){var b=c(this).data("fracs");b&&b.unbind(a)})}},defaultStatic:function(){return"fracs"},defaultMethod:function(){if(arguments.length===0)return"fracs";else if(arguments[0]instanceof Function)return"bind"}})})(window,jQuery);
(function(f,c,e){var a=f.Fracs=f.Fracs||{},d=c(f),b=c("html,body"),i={crop:false,duration:0,focusWidth:0.5,focusHeight:0.5,autoFocus:true,styles:[{selector:"header,footer,section,article",fillStyle:"rgb(230,230,230)"},{selector:"h1",fillStyle:"rgb(240,140,060)"},{selector:"h2",fillStyle:"rgb(200,100,100)"},{selector:"h3",fillStyle:"rgb(100,200,100)"},{selector:"h4",fillStyle:"rgb(100,100,200)"}],viewportStyle:{fillStyle:"rgba(228,77,38,0.3)"},viewportDragStyle:{fillStyle:"rgba(228,77,38,0.6)"},invertViewport:false};
a.Outline=function(f,t){if(!(this instanceof a.Outline))return new a.Outline(f,t);if(!f.nodeName||f.nodeName.toLowerCase()!=="canvas")return e;var g=c.extend({},i,t),j=c(f),o=j.attr("width"),p=j.attr("height"),h=f.getContext("2d"),q=false,k,m,l,r,s,w=function(a,c,b,d,e){if(b||d){if(d)h.beginPath(),e?(h.rect(0,0,k.width,a.top),h.rect(0,a.top,a.left,a.height),h.rect(a.right,a.top,k.right-a.right,a.height),h.rect(0,a.bottom,k.width,k.bottom-a.bottom)):h.rect(a.left,a.top,a.width,a.height),h.fillStyle=
d,h.fill();if(b)h.beginPath(),h.rect(a.left,a.top,a.width,a.height),h.lineWidth=l?Math.max(c,0.2/l):c,h.strokeStyle=b,h.stroke()}},x=function(){c.each(g.styles,function(b,d){c(d.selector).each(function(){var b=d.strokeWidth,e=d.strokeStyle,f=d.fillStyle,g=c(this),h=a.Rect.ofElement(this);g.css("visibility")==="hidden"||h.width===0||h.height===0||(b=b==="auto"?parseInt(g.css("border-top-width"),10):b,e=e==="auto"?g.css("border-top-color"):e,f=f==="auto"?g.css("background-color"):f,w(h,b,e,f))})})},
u=function(){k=a.Rect.ofDocument();m=a.Rect.ofViewport();l=Math.min(o/k.width,p/k.height);g.crop&&j.attr("width",k.width*l).attr("height",k.height*l);h.setTransform(1,0,0,1,0,0);h.clearRect(0,0,j.width(),j.height());h.scale(l,l);x();var b=q&&g.viewportDragStyle?g.viewportDragStyle:g.viewportStyle;w(m,b.strokeWidth,b.strokeStyle,b.fillStyle,g.invertViewport)},v=function(b){var d=j.fracs("rect");a.ScrollState.scrollTo((b.pageX-d.left)/l-m.width*r,(b.pageY-d.top)/l-m.height*s,g.duration)},y=function(a){q=
false;a.preventDefault();j.css("cursor","pointer").removeClass("dragOn");b.css("cursor","auto");d.unbind("mousemove",v);u()};j.css("cursor","pointer").mousedown(function(a){var c;g.autoFocus&&(c=j.fracs("rect"),r=((a.pageX-c.left)/l-m.left)/m.width,s=((a.pageY-c.top)/l-m.top)/m.height);if(!g.autoFocus||r<0||r>1||s<0||s>1)r=g.focusWidth,s=g.focusHeight;q=true;a.preventDefault();j.css("cursor","crosshair").addClass("dragOn");b.css("cursor","crosshair");d.bind("mousemove",v).one("mouseup",y);v(a)});
d.bind("load resize scroll",u);u();this.redraw=u}})(window,jQuery);(function(f,c){var e=f.Fracs=f.Fracs||{};c.ModPlug.module("fracs",{methods:{outline:function(a){return this.each(function(){var d;a==="redraw"?(d=c(this).data("outline"))&&d.redraw():(d=e.Outline(this,a))&&c(this).data("outline",d)})}}})})(window,jQuery);
