(function(h){ChiliBook={version:"2.2",automatic:true,automaticSelector:"code",lineNumbers:false,codeLanguage:function(j){return(j=h(j).attr("class"))?j:""},recipeLoading:true,recipeFolder:"",replaceSpace:"&#160;",replaceTab:"&#160;&#160;&#160;&#160;",replaceNewLine:"&#160;<br/>",selectionStyle:"position:absolute; z-index:3000; overflow:scroll; width:16em; height:9em; border:1px solid gray; padding:15px; background-color:yellow;",defaultReplacement:'<span class="$0">$$</span>',recipes:{},queue:{},
unique:function(){return(new Date).valueOf()}};h.fn.chili=function(j){function o(b,f,a){function e(a,b,e){var c=a[b][e],i=typeof c._match=="string"?c._match:c._match.source;return{recipe:a,blockName:b,stepName:e,exp:"("+i+")",length:1+(i.replace(/\\./g,"%").replace(/\[.*?\]/g,"%").match(/\((?!\?)/g)||[]).length,replacement:c._replace?c._replace:d.defaultReplacement}}function c(a){for(var b=1,c=[],e=0;e<a.length;e++){var d=a[e].exp,d=d.replace(/\\\\|\\(\d+)/g,function(a,e){return!e?a:"\\"+(b+1+parseInt(e,
10))});c.push(d);b+=a[e].length}a="(?:"+c.join("|")+")";return RegExp("((?:\\s|\\S)*?)"+a+"|((?:\\s|\\S)+)",f._case?"g":"gi")}function g(a){return a.replace(/ +/g,function(a){return a.replace(/ /g,n)})}function i(a){a=a.replace(/&/g,"&amp;").replace(/</g,"&lt;");n&&(a=g(a));return a}function s(a,b,d,i){var h=[e(b,d,i)];return a.replace(c(h),function(){return l.apply({steps:h},arguments)})}function q(a,b,e){function c(a){a=d.recipes[d.recipeFolder+a+".js"];if(!a)throw{msg:"recipe not available"};return a}
if(!b)return i(a);var f=b.split("/"),g="",k="",j="";switch(f.length){case 1:g=f[0];break;case 2:g=f[0];k=f[1];break;case 3:g=f[0];k=f[1];j=f[2];break;default:return i(a)}try{var m;if(""==j)if(""==k){if(""!=g)return m=c(g),o(a,m)}else return m=""==g?e.recipe:c(g),!(k in m)?i(a):o(a,m,k);else{m=""==g?e.recipe:c(g);if(""==k)k=e.blockName;return!(k in m)?i(a):!(j in m[k])?i(a):s(a,m,k,j)}}catch(n){if(n.msg&&n.msg=="recipe not available"&&(f="chili_"+d.unique(),d.recipeLoading)){var l=d.recipeFolder+g+
".js";if(d.queue[l])d.queue[l].push({cue:f,subject:a,module:b,context:e});else try{d.queue[l]=[{cue:f,subject:a,module:b,context:e}],h.ajax({url:l,dataType:"text",success:function(a){d.recipes[l]=window.eval("(function() { var recipe = "+a+"; return recipe; }())");for(var a=d.queue[l],b=0,e=a.length;b<e;b++){var c=q(a[b].subject,a[b].module,a[b].context);d.replaceTab&&(c=c.replace(/\t/g,d.replaceTab));d.replaceNewLine&&(c=c.replace(/\n/g,d.replaceNewLine));h("#"+a[b].cue).replaceWith(c)}}})}catch(p){alert("the recipe for '"+
g+"' was not found in '"+l+"'")}return'<span id="'+f+'">'+i(a)+"</span>"}return i(a)}}function l(){if(!arguments[0])return"";var a=this.steps,b=0,e=2,c=arguments[1],f=arguments[arguments.length-3];if(f)return i(f);else for(var d;d=a[b++];){var g=arguments;if(g[e]){a="";if(h.isFunction(d.replacement)){a=[];b=0;for(f=d.length;b<f;b++)a.push(g[e+b]);a.push(g[g.length-2]);a.push(g[g.length-1]);a=d.replacement.apply({x:function(a,b){return q(a,b,{recipe:d.recipe,blockName:d.blockName})}},a)}else a=d.replacement.replace(/(\\\$)|(?:\$\$)|(?:\$(\d+))/g,
function(a,b,c){return b?"$":c?c=="0"?d.stepName:i(g[e+parseInt(c,10)]):i(g[e])});a=a.replace(/(<span\s+class\s*=\s*(["']))((?:(?!__)\w)+\2\s*>)/ig,"$1"+d.recipe._name+"__$3");return i(c)+a}else e+=d.length}}a||(a="_main",t(f));if(!(a in f))return i(b);var n=d.replaceSpace,j=function(a,b){var c=[],d;for(d in a[b])c.push(e(a,b,d));return c}(f,a),a=c(j);return b.replace(a,function(){return l.apply({steps:j},arguments)})}function t(b){var f=b._name;if(!d.queue[f]){var a=["/* Chili -- "+f+" */"],e;for(e in b)if(e.search(/^_(?!main\b)/)<
0)for(var c in b[e]){var g=b[e][c];if("_style"in g)if(g._style.constructor==String)a.push("."+f+"__"+c+" { "+g._style+" }");else for(var i in g._style)a.push("."+f+"__"+i+" { "+g._style[i]+" }")}a=a.join("\n");if(document.createElement)b=document.createElement("style"),b.type="text/css",b.styleSheet?b.styleSheet.cssText=a:(a=document.createTextNode(a),b.appendChild(a)),document.getElementsByTagName("head")[0].appendChild(b);d.queue[f]=true}}function u(b){var f=d.codeLanguage(b);if(""!=f){var a=d.recipeFolder+
f+".js";if(d.recipeLoading)if(d.queue[a])d.queue[a].push(b);else try{d.queue[a]=[b],h.ajax({url:a,dataType:"text",success:function(b){d.recipes[a]=window.eval("(function() { var recipe = "+b+"; return recipe; }())");for(var b=d.queue[a],e=0,f=b.length;e<f;e++)p(b[e],a)}})}catch(e){alert("the recipe for '"+f+"' was not found in '"+a+"'")}p(b,a)}}function p(b,f){var a=d.recipes[f];if(a){var e=h(b),c=e.text();if(c)if(c=c.replace(/\r\n?/g,"\n"),e.parent().is("pre")&&(h.browser.safari||(c=c.replace(/^\n/g,
""))),a=o(c,a),d.replaceTab&&(a=a.replace(/\t/g,d.replaceTab)),d.replaceNewLine&&(a=a.replace(/\n/g,d.replaceNewLine)),b.innerHTML=a,(h.browser.msie||h.browser.mozilla)&&v(b),a=e.parent(),c=/ln-(\d+)-([\w][\w\-]*)|ln-(\d+)|ln-/.exec(a.attr("class"))){r(b);var g=0;c[1]?(g=parseInt(c[1],10),c=h(".ln-"+c[1]+"-"+c[2]),a=c.index(a[0]),c.slice(0,a).each(function(){g+=h(this).find("li").length})):g=c[3]?parseInt(c[3],10):1;e.find("ol")[0].start=g;h("body").width(h("body").width()-1).width(h("body").width()+
1)}else d.lineNumbers&&r(b)}}function v(b){var d=null;h(b).parents().filter("pre").bind("mousedown",function(){d=this;h.browser.msie?document.selection.empty():window.getSelection().removeAllRanges()}).bind("mouseup",function(a){if(d&&d==this){d=null;var b="";if(h.browser.msie){b=document.selection.createRange().htmlText;if(""==b)return;var b=w(b),c='<textarea style="STYLE">'}else{b=window.getSelection().toString();if(""==b)return;b=b.replace(/\r/g,"").replace(/^# ?/g,"").replace(/\n# ?/g,"\n");c=
'<pre style="STYLE">'}b=h(c.replace(/\bSTYLE\b/,ChiliBook.selectionStyle)).appendTo("body").text(b).attr("id","chili_selection").click(function(){h(this).remove()});c=a.pageY-Math.round(b.height()/2)+"px";a=a.pageX-Math.round(b.width()/2)+"px";b.css({top:c,left:a});h.browser.msie?(b[0].focus(),b[0].select()):(a=window.getSelection(),a.removeAllRanges(),c=document.createRange(),c.selectNodeContents(b[0]),a.addRange(c))}})}function w(b){do var d=ChiliBook.unique();while(b.indexOf(d)>-1);var a="";if(/<br/i.test(b)||
/<li/i.test(b)){/<br/i.test(b)?b=b.replace(/\<br[^>]*?\>/ig,d):/<li/i.test(b)&&(b=b.replace(/<ol[^>]*?>|<\/ol>|<li[^>]*?>/ig,"").replace(/<\/li>/ig,d));var e=h("<pre>").appendTo("body").hide()[0];e.innerHTML=b;a=h(e).text().replace(RegExp(d,"g"),"\r\n");h(e).remove()}return a}function r(b){function f(a,b,d,c){var e=c?"</span>":"",f="";a?f="<li>"+c+b+e+"</li>":d&&(f="<li>"+c+d+e+"</li>");return f}var a=h(b).html(),e=/<br>/.test(a)?"<br>":"<BR>",c="<li>"+d.replaceSpace+"</li>",a=a.replace(/(<span [^>]+>)((?:(?:&nbsp;|\xA0)<br>)+)(.*?)(<\/span>)/ig,
"$2$1$3$4").replace(/(.*?)(<span .*?>)(.*?)(?:<\/span>(?:&nbsp;|\xA0)<br>|<\/span>)/ig,function(a,b,d,c){return/<br>/i.test(c)?(b=b.split(e),a=b.pop(),b=b.join(e),(b?b+e:"")+(a+c).replace(/((.*?)(?:&nbsp;|\xA0)<br>)|(.*)/ig,function(a,b,c,e){return f(b,c,e,d)})):a}).replace(/(<li>.*?<\/li>)|((.*?)(?:&nbsp;|\xA0)<br>)|(.+)/ig,function(a,b,c,d,e){a="";return a=b?b:f(c,d,e,"")}).replace(/<li><\/li>/ig,c);b.innerHTML="<ol>"+a+"</ol>"}var d=h.extend({},ChiliBook,j||{});this.each(function(){var b=h(this);
b.trigger("chili.before_coloring");u(this);b.trigger("chili.after_coloring")});return this};h(function(){ChiliBook.automatic&&h(ChiliBook.automaticSelector).chili()})})(jQuery);
