(function(d){d.fn.slides=function(a){a=d.extend({},d.fn.slides.option,a);return this.each(function(){function l(h,z,A){if(!p&&v){p=true;a.animationStart(j+1);switch(h){case "next":m=j;e=j+1;e=k===e?0:e;r=g*2;h=-g*2;j=e;break;case "prev":m=j;e=j-1;e=e===-1?k-1:e;h=r=0;j=e;break;case "pagination":e=parseInt(A,10);m=d("."+a.paginationClass+" li.current a",c).attr("href").match("[^#/]+$");if(e>m){r=g*2;h=-g*2}else h=r=0;j=e}if(z==="fade")a.crossfade?b.children(":eq("+e+")",c).css({zIndex:10}).fadeIn(a.fadeSpeed,
a.fadeEasing,function(){if(a.autoHeight)b.animate({height:b.children(":eq("+e+")",c).outerHeight()},a.autoHeightSpeed,function(){b.children(":eq("+m+")",c).css({display:"none",zIndex:0});b.children(":eq("+e+")",c).css({zIndex:0});a.animationComplete(e+1);p=false});else{b.children(":eq("+m+")",c).css({display:"none",zIndex:0});b.children(":eq("+e+")",c).css({zIndex:0});a.animationComplete(e+1);p=false}}):b.children(":eq("+m+")",c).fadeOut(a.fadeSpeed,a.fadeEasing,function(){a.autoHeight?b.animate({height:b.children(":eq("+
e+")",c).outerHeight()},a.autoHeightSpeed,function(){b.children(":eq("+e+")",c).fadeIn(a.fadeSpeed,a.fadeEasing)}):b.children(":eq("+e+")",c).fadeIn(a.fadeSpeed,a.fadeEasing,function(){d.browser.msie&&d(this).get(0).style.removeAttribute("filter")});a.animationComplete(e+1);p=false});else{b.children(":eq("+e+")").css({left:r,display:"block"});a.autoHeight?b.animate({left:h,height:b.children(":eq("+e+")").outerHeight()},a.slideSpeed,a.slideEasing,function(){b.css({left:-g});b.children(":eq("+e+")").css({left:g,
zIndex:5});b.children(":eq("+m+")").css({left:g,display:"none",zIndex:0});a.animationComplete(e+1);p=false}):b.animate({left:h},a.slideSpeed,a.slideEasing,function(){b.css({left:-g});b.children(":eq("+e+")").css({left:g,zIndex:5});b.children(":eq("+m+")").css({left:g,display:"none",zIndex:0});a.animationComplete(e+1);p=false})}if(a.pagination){d("."+a.paginationClass+" li.current",c).removeClass("current");d("."+a.paginationClass+" li:eq("+e+")",c).addClass("current")}}}function o(){if(a.pause){clearTimeout(c.data("pause"));
clearInterval(c.data("interval"));w=setTimeout(function(){clearTimeout(c.data("pause"));u=setInterval(function(){l("next",n)},a.play);c.data("interval",u)},a.pause);c.data("pause",w)}else clearInterval(c.data("interval"))}d("."+a.container,d(this)).children().wrapAll('<div class="slides_control"/>');var c=d(this),b=d(".slides_control",c),k=b.children().size(),g=b.children().outerWidth(),s=b.children().outerHeight(),f=a.start-1,n=a.effect.indexOf(",")<0?a.effect:a.effect.replace(" ","").split(",")[0],
x=a.effect.indexOf(",")<0?n:a.effect.replace(" ","").split(",")[1],e=0,m=0,t=0,j=0,v,p,q,r,y,w,u;if(!(k<2)){if(f<0)f=0;if(f>k)f=k-1;if(a.start)j=f;a.randomize&&b.randomize();d("."+a.container,c).css({overflow:"hidden",position:"relative"});b.children().css({position:"absolute",top:0,left:b.children().outerWidth(),zIndex:0,display:"none"});b.css({position:"relative",width:g*3,height:s,left:-g});d("."+a.container,c).css({display:"block"});if(a.autoHeight){b.children().css({height:"auto"});b.animate({height:b.children(":eq("+
f+")").outerHeight()},a.autoHeightSpeed)}if(a.preload&&b.find("img").length){d("."+a.container,c).css({background:"url("+a.preloadImage+") no-repeat 50% 50%"});s=b.find("img:eq("+f+")").attr("src")+"?"+(new Date).getTime();y=d("img",c).parent().attr("class")!="slides_control"?b.children(":eq(0)")[0].tagName.toLowerCase():b.find("img:eq("+f+")");b.find("img:eq("+f+")").attr("src",s).load(function(){b.find(y+":eq("+f+")").fadeIn(a.fadeSpeed,a.fadeEasing,function(){d(this).css({zIndex:5});d("."+a.container,
c).css({background:""});v=true;slidesLoaded()})})}else b.children(":eq("+f+")").fadeIn(a.fadeSpeed,a.fadeEasing,function(){v=true;slidesLoaded()});if(a.bigTarget){b.children().css({cursor:"pointer"});b.children().click(function(){l("next",n);return false})}if(a.hoverPause&&a.play){b.bind("mouseover",function(){clearInterval(c.data("interval"))});b.bind("mouseleave",function(){o()})}if(a.generateNextPrev){d("."+a.container,c).after('<a href="#" class="'+a.prev+'">Prev</a>');d("."+a.prev,c).after('<a href="#" class="'+
a.next+'">Next</a>')}d("."+a.next,c).click(function(h){h.preventDefault();a.play&&o();l("next",n)});d("."+a.prev,c).click(function(h){h.preventDefault();a.play&&o();l("prev",n)});if(a.generatePagination){c.append("<ul class="+a.paginationClass+"></ul>");b.children().each(function(){d("."+a.paginationClass,c).append('<li><a href="#'+t+'">'+(t+1)+"</a></li>");t++})}else d("."+a.paginationClass+" li a",c).each(function(){d(this).attr("href","#"+t);t++});d("."+a.paginationClass+" li:eq("+f+")",c).addClass("current");
d("."+a.paginationClass+" li a",c).click(function(){a.play&&o();q=d(this).attr("href").match("[^#/]+$");j!=q&&l("pagination",x,q);return false});d("a.link",c).click(function(){a.play&&o();q=d(this).attr("href").match("[^#/]+$")-1;j!=q&&l("pagination",x,q);return false});if(a.play){u=setInterval(function(){l("next",n)},a.play);c.data("interval",u)}}})};d.fn.slides.option={preload:false,preloadImage:"/img/loading.gif",container:"slides_container",generateNextPrev:false,next:"next",prev:"prev",pagination:true,
generatePagination:true,paginationClass:"pagination",fadeSpeed:350,fadeEasing:"",slideSpeed:350,slideEasing:"",start:1,effect:"slide",crossfade:false,randomize:false,play:0,pause:0,hoverPause:false,autoHeight:false,autoHeightSpeed:350,bigTarget:false,animationStart:function(){},animationComplete:function(){},slidesLoaded:function(){}};d.fn.randomize=function(a){function l(){return Math.round(Math.random())-0.5}return d(this).each(function(){var o=d(this),c=o.children(),b=c.length;if(b>1){c.hide();
var k=[];for(i=0;i<b;i++)k[k.length]=i;k=k.sort(l);d.each(k,function(g,s){var f=c.eq(s),n=f.clone(true);n.show().appendTo(o);a!==undefined&&a(f,n);f.remove()})}})}})(jQuery);
