(function(d){d.fn.popeye=function(x){function g(d,g){window.console&&window.console.log&&b.debug&&(g=="info"&&window.console.info?window.console.info(d):g=="warn"&&window.console.warn?window.console.warn(d):window.console.log(d))}var b=d.extend({},d.fn.popeye.defaults,x);return this.each(function(){function p(f,k){var k=k||!1,f=f||c,i={backgroundImage:"url("+q[f].src+")"},h={height:"+=0"};if(m)r(),e.fadeTo(b.duration/2,0).animate(N,{queue:!1,duration:b.duration,easing:b.easing,complete:function(){m=
!1;g("$.fn.showThumb: Entering COMPACT MODE","info");a.removeClass(z);a.css("z-index","");A.removeClass("ppy-hidden");B.addClass("ppy-hidden");p();d(this).fadeTo(b.duration/2,1)}});else{if(k){n.addClass(t);e.fadeTo(b.duration/2,0);var C=new Image;C.onload=function(){g("$.fn.popeye.showThumb: Thumbnail "+f+" loaded","info");n.removeClass(t);e.animate(h,1,"linear",function(){e.css(i);d(this).fadeTo(b.duration/2,1);b.caption=="hover"?u(o[f]):b.caption=="permanent"&&b.caption&&H.html(o[f]);D()});C.onload=
function(){}};C.src=q[f].src}else e.css(i),D(),u(o[f],!0);var j=new Image;j.onload=function(){g("$.fn.popeye.showThumb: Image "+f+" loaded","info");j.onload=function(){}};j.src=s[f].href}}function y(f){f=f||c;n.addClass(t);e.fadeTo(b.duration/2,0);d("."+z).css("z-index",b.zindex-1);a.css("z-index",b.zindex);var k=new Image;k.onload=function(){n.removeClass(t);var h={width:k.width,height:k.height},j={backgroundImage:"url("+s[f].href+")",backgroundPosition:"left top"};r();e.animate(h,{queue:!1,duration:b.duration,
easing:b.easing,complete:function(){b.navigation=="hover"&&E();m=!0;g("$.fn.popeye.showImage: Entering ENLARGED MODE","info");a.addClass(z);B.removeClass("ppy-hidden");A.addClass("ppy-hidden");D();d(this).css(j).fadeTo(b.duration/2,1);u(o[f]);var e;e=c;var h=new Image,k=new Image,l=e;l<i-1?l++:l=0;h.src=s[e].href[l];l=e;l<=0?l=i-1:l--;k.src=s[e].href[l]}})};k.src=s[f].href}function D(a){a=a||c;O.text(i);P.text(a+1);g("$.fn.popeye.updateCounter: Displaying image "+(a+1)+" of "+i)}function E(){v.stop().fadeTo(150,
b.opacity)}function F(){v.stop().fadeTo(150,0)}function u(a,c){a&&b.caption?(b.caption&&H.html(a),g("$.fn.popeye.showCaption -> ppyCaptionWrap.outerHeight(true): "+w.outerHeight(!0)),h.css({visibility:"visible"}),b.caption==="permanent"&&!m?h.css(Q):h.animate({height:w.outerHeight(!0)},{queue:!1,duration:90,easing:b.easing})):!a&&!c&&r()}function r(){var a={visibility:"hidden",overflow:"hidden"};h.animate({height:"0px"},{queue:!1,duration:90,easing:b.easing,complete:function(){h.css(a)}})}function x(){c<=
0?c=i-1:c--;m?y(c):p(c,!0);return c}function R(){c<i-1?c++:c=0;m?y(c):p(c,!0);return c}function S(){I.css(T);a.css(U);a.wrap(I);n=e.wrap(n).parent();w=h.wrapInner(w).children().eq(0);p();b.navigation=="hover"&&(F(),a.hover(function(){E()},function(){F()}),v.hover(function(){E()},function(){F()}));J?(a.addClass(V),K.remove(),L.remove(),W.remove()):(K.click(x),L.click(R));b.caption=="hover"&&(r(),a.hover(function(){u(o[c])},function(){r(!0)}));A.click(function(){y();return!1});B.click(function(){p(c);
return!1})}d(this).addClass("ppy-active");for(var a=d(this),q=a.find(".ppy-imglist > li > a > img"),s=a.find(".ppy-imglist > li > a"),i=q.length,J=i==1?!0:!1,m=!1,c=0,z="ppy-expanded",t="ppy-loading",V="ppy-single-image",I=d('<div class="ppy-placeholder"></div>'),n=d('<div class="ppy-stagewrap"></div>'),w=d('<div class="ppy-captionwrap"></div>'),G=a.find(".ppy-outer"),e=a.find(".ppy-stage"),v=a.find(".ppy-nav"),K=a.find(".ppy-prev"),L=a.find(".ppy-next"),A=a.find(".ppy-switch-enlarge"),B=a.find(".ppy-switch-compact").addClass("ppy-hidden"),
h=a.find(".ppy-caption"),H=a.find(".ppy-text"),W=a.find(".ppy-counter"),P=a.find(".ppy-current"),O=a.find(".ppy-total"),U={position:"absolute",width:"auto",height:"auto",margin:0,top:0,left:b.direction=="right"?0:"auto",right:b.direction=="left"?0:"auto"},N={height:e.height(),width:e.width()},Q={height:h.height()},T={height:b.caption=="hover"?G.outerHeight():a.outerHeight(),width:b.caption=="hover"?G.outerWidth():a.outerWidth(),"float":a.css("float"),marginTop:a.css("margin-top"),marginRight:a.css("margin-right"),
marginBottom:a.css("margin-bottom"),marginLeft:a.css("margin-left")},o=[],j=0;j<q.length;j++){var M=a.find(".ppy-imglist li").eq(j).find(".ppy-extcaption");o[j]=M.length>0?M.html():q[j].alt}!e.length||!v.length||!G.length?g("$.fn.popeye: Incorrect HTML structure","warn"):i===0?g("$.fn.popeye: No images found","warn"):(J?g("$.fn.popeye -> SingleImageMode started"):g("$.fn.popeye -> "+i+" thumbnails found."),S())})};d.fn.popeye.defaults={navigation:"hover",caption:"hover",zindex:1E4,direction:"right",
duration:240,opacity:0.8,easing:"swing",debug:!1}})(jQuery);jQuery("head").append('<style type="text/css"> .ppy-imglist { position: absolute; top: -1000em; left: -1000em; } </style>');
