(function(k,e,v){var m=function(){var a=["Moz","Webkit","Khtml","O","Ms"];return function(b,c){var c=c||document.documentElement,d=c.style,f;if(typeof d[b]==="string")return b;for(var b=b.charAt(0).toUpperCase()+b.slice(1),e=0,h=a.length;e<h;e++)if(f=a[e]+b,typeof d[f]==="string")return f}}(),n=m("transform"),s=document.documentElement,w=" -o- -moz- -ms- -webkit- -khtml- ".split(" "),o=[{name:"csstransforms",getResult:function(){return!!n}},{name:"csstransforms3d",getResult:function(){var a=!!m("perspective");
if(a){var b=document.createElement("style"),c=document.createElement("div"),a="@media ("+w.join("transform-3d),(")+"modernizr)";b.textContent=a+"{#modernizr{height:3px}}";(document.head||document.getElementsByTagName("head")[0]).appendChild(b);c.id="modernizr";s.appendChild(c);a=c.offsetHeight===3;b.parentNode.removeChild(b);c.parentNode.removeChild(c)}return!!a}},{name:"csstransitions",getResult:function(){return!!m("transitionProperty")}}],i,t=o.length;if(k.Modernizr)for(i=0;i<t;i++){var p=o[i];
Modernizr.hasOwnProperty(p.name)||Modernizr.addTest(p.name,p.getResult)}else k.Modernizr=function(){var a={_version:"1.6ish: miniModernizr for Isotope"},b=[],c,d;for(i=0;i<t;i++)c=o[i],d=c.getResult(),a[c.name]=d,c=(d?"":"no-")+c.name,b.push(c);s.className+=" "+b.join(" ");return a}();if(Modernizr.csstransforms){var z=Modernizr.csstransforms3d?{translate:function(a){return"translate3d("+a[0]+"px, "+a[1]+"px, 0) "},scale:function(a){return"scale3d("+a+", "+a+", 1) "}}:{translate:function(a){return"translate("+
a[0]+"px, "+a[1]+"px) "},scale:function(a){return"scale("+a+") "}},u=function(a,b,c){var d=e.data(a,"isoTransform")||{},f={},g,h={};f[b]=c;e.extend(d,f);for(g in d)b=d[g],h[g]=z[g](b);g=(h.translate||"")+(h.scale||"");e.data(a,"isoTransform",d);a.style[n]=g};e.cssNumber.scale=!0;e.cssHooks.scale={set:function(a,b){typeof b==="string"&&(b=parseFloat(b));u(a,"scale",b)},get:function(a){return(a=e.data(a,"isoTransform"))&&a.scale?a.scale:1}};e.fx.step.scale=function(a){e.cssHooks.scale.set(a.elem,a.now+
a.unit)};e.cssNumber.translate=!0;e.cssHooks.translate={set:function(a,b){u(a,"translate",b)},get:function(a){return(a=e.data(a,"isoTransform"))&&a.translate?a.translate:[0,0]}}}var q=e.event,r;q.special.smartresize={setup:function(){e(this).bind("resize",q.special.smartresize.handler)},teardown:function(){e(this).unbind("resize",q.special.smartresize.handler)},handler:function(a,b){var c=this,d=arguments;a.type="smartresize";r&&clearTimeout(r);r=setTimeout(function(){jQuery.event.handle.apply(c,
d)},b==="execAsap"?0:100)}};e.fn.smartresize=function(a){return a?this.bind("smartresize",a):this.trigger("smartresize",["execAsap"])};e.Isotope=function(a,b){this.element=e(b);this._create(a);this._init()};var l=["overflow","position","width","height"];e.Isotope.settings={resizable:!0,layoutMode:"masonry",containerClass:"isotope",itemClass:"isotope-item",hiddenClass:"isotope-hidden",hiddenStyle:Modernizr.csstransforms&&!e.browser.opera?{opacity:0,scale:0.001}:{opacity:0},visibleStyle:Modernizr.csstransforms&&
!e.browser.opera?{opacity:1,scale:1}:{opacity:1},animationEngine:e.browser.opera?"jquery":"best-available",animationOptions:{queue:!1,duration:800},sortBy:"original-order",sortAscending:!0,resizesContainer:!0,transformsEnabled:!0,itemPositionDataEnabled:!1};e.Isotope.prototype={_create:function(a){this.options=e.extend(!0,{},e.Isotope.settings,a);this.styleQueue=[];this.elemCount=0;a=this.element[0].style;this.originalStyle={};for(var b=0,c=l.length;b<c;b++){var d=l[b];this.originalStyle[d]=a[d]||
null}this.element.css({overflow:"hidden",position:"relative"});this._updateAnimationEngine();this._updateUsingTransforms();this.options.getSortData=e.extend(this.options.getSortData,{"original-order":function(a,b){return b.elemCount}});this.reloadItems();a=e(document.createElement("div")).prependTo(this.element);this.offset=a.position();a.remove();var f=this;setTimeout(function(){f.element.addClass(f.options.containerClass)},0);this.options.resizable&&e(k).bind("smartresize.isotope",function(){f.resize()})},
_getAtoms:function(a){var b=this.options.itemSelector,a=b?a.filter(b).add(a.find(b)):a,b={position:"absolute"};if(this.usingTransforms)b.left=0,b.top=0;a.css(b).addClass(this.options.itemClass);this.updateSortData(a,!0);return a},_init:function(a){this.$filteredAtoms=this._filter(this.$allAtoms);this._sort();this.reLayout(a)},option:function(a){if(e.isPlainObject(a)){this.options=e.extend(!0,this.options,a);for(var b in a)this._updateOption(b)}},_updateOption:function(a){a="_update"+a.charAt(0).toUpperCase()+
a.slice(1);if(this[a])this[a]()},_updateAnimationEngine:function(){switch(this.options.animationEngine.toLowerCase().replace(/[ _\-]/g,"")){case "css":case "none":this.isUsingJQueryAnimation=!1;break;case "jquery":this.isUsingJQueryAnimation=!0;break;default:this.isUsingJQueryAnimation=!Modernizr.csstransitions}this._updateUsingTransforms()},_updateTransformsEnabled:function(){this._updateUsingTransforms()},_updateUsingTransforms:function(){this.getPositionStyles=(this.usingTransforms=this.options.transformsEnabled&&
Modernizr.csstransforms&&Modernizr.csstransitions&&!this.isUsingJQueryAnimation)?this._translate:this._positionAbs},_filter:function(a){var b=this.options.filter===""?"*":this.options.filter;if(b){var c=this.options.hiddenClass,d="."+c,f=a.not(d),e=a.filter(d),d=e,a=a.filter(b);b!=="*"&&(d=e.filter(b),b=f.not(b).toggleClass(c),b.addClass(c),this.styleQueue.push({$el:b,style:this.options.hiddenStyle}));this.styleQueue.push({$el:d,style:this.options.visibleStyle});d.removeClass(c)}return a},updateSortData:function(a,
b){var c=this,d=this.options.getSortData,f,g;a.each(function(){f=e(this);g={};for(var a in d)g[a]=d[a](f,c);e.data(this,"isotope-sort-data",g);b&&c.elemCount++})},_sort:function(){var a=this.options.sortBy,b=this._getSorter,c=this.options.sortAscending?1:-1;this.$filteredAtoms.sort(function(d,f){var e=b(d,a),h=b(f,a);e===h&&a!=="original-order"&&(e=b(d,"original-order"),h=b(f,"original-order"));return(e>h?1:e<h?-1:0)*c})},_getSorter:function(a,b){return e.data(a,"isotope-sort-data")[b]},_translate:function(a,
b){return{translate:[a,b]}},_positionAbs:function(a,b){return{left:a,top:b}},_pushPosition:function(a,b,c){b+=this.offset.left;c+=this.offset.top;var d=this.getPositionStyles(b,c);this.styleQueue.push({$el:a,style:d});this.options.itemPositionDataEnabled&&a.data("isotope-item-position",{x:b,y:c})},layout:function(a,b){var c=this.options.layoutMode;this["_"+c+"Layout"](a);this.options.resizesContainer&&this.styleQueue.push({$el:this.element,style:this["_"+c+"GetContainerSize"]()});var d=!this.isLaidOut?
"css":this.isUsingJQueryAnimation?"animate":"css",f=this.options.animationOptions;e.each(this.styleQueue,function(a,b){b.$el[d](b.style,f)});this.styleQueue=[];b&&b.call(a);this.isLaidOut=!0},resize:function(){this["_"+this.options.layoutMode+"ResizeChanged"]()&&this.reLayout()},reLayout:function(a){this["_"+this.options.layoutMode+"Reset"]();this.layout(this.$filteredAtoms,a)},addItems:function(a,b){var c=this._getAtoms(a);this.$allAtoms=this.$allAtoms.add(c);b&&b(c)},insert:function(a,b){this.element.append(a);
var c=this;this.addItems(a,function(a){a=c._filter(a);c.$filteredAtoms=c.$filteredAtoms.add(a)});this._sort();this.reLayout(b)},appended:function(a,b){var c=this;this.addItems(a,function(a){c.$filteredAtoms=c.$filteredAtoms.add(a);c.layout(a,b)})},reloadItems:function(){this.$allAtoms=this._getAtoms(this.element.children())},remove:function(a){this.$allAtoms=this.$allAtoms.not(a);this.$filteredAtoms=this.$filteredAtoms.not(a);a.remove()},_shuffleArray:function(a){var b,c,d=a.length;if(d)for(;--d;)c=
~~(Math.random()*(d+1)),b=a[c],a[c]=a[d],a[d]=b;return a},shuffle:function(a){this.options.sortBy="shuffle";this.$allAtoms=this._shuffleArray(this.$allAtoms);this.$filteredAtoms=this._filter(this.$allAtoms);this.reLayout(a)},destroy:function(){var a=this.usingTransforms;this.$allAtoms.removeClass(this.options.hiddenClass+" "+this.options.itemClass).each(function(){this.style.position=null;this.style.top=null;this.style.left=null;this.style.opacity=null;a&&(this.style[n]=null)});for(var b=this.element[0].style,
c=0,d=l.length;c<d;c++){var f=l[c];b[f]=this.originalStyle[f]}this.element.unbind(".isotope").removeClass(this.options.containerClass).removeData("isotope");e(k).unbind(".isotope")},_getSegments:function(a){var b=this.options.layoutMode,c=a?"rowHeight":"columnWidth",d=a?"Height":"Width",f=a?"rows":"cols",a=this.element[a?"height":"width"](),d=this.options[b]&&this.options[b][c]||this.$filteredAtoms["outer"+d](!0)||a,a=Math.floor(a/d),a=Math.max(a,1);this[b][f]=a;this[b][c]=d},_checkIfSegmentsChanged:function(a){var b=
this.options.layoutMode,c=a?"rows":"cols",d=this[b][c];this._getSegments(a);return this[b][c]!==d},_masonryReset:function(){this.masonry={};this._getSegments();var a=this.masonry.cols;for(this.masonry.colYs=[];a--;)this.masonry.colYs.push(0)},_masonryLayout:function(a){var b=this,c=b.masonry;a.each(function(){var a=e(this),f=Math.ceil(a.outerWidth(!0)/c.columnWidth),f=Math.min(f,c.cols);if(f===1)b._masonryPlaceBrick(a,c.colYs);else{var g=c.cols+1-f,h=[],i,j;for(j=0;j<g;j++)i=c.colYs.slice(j,j+f),
h[j]=Math.max.apply(Math,i);b._masonryPlaceBrick(a,h)}})},_masonryPlaceBrick:function(a,b){for(var c=Math.min.apply(Math,b),d=0,f=0,e=b.length;f<e;f++)if(b[f]===c){d=f;break}x=this.masonry.columnWidth*d;y=c;this._pushPosition(a,x,y);c+=a.outerHeight(!0);e=this.masonry.cols+1-e;for(f=0;f<e;f++)this.masonry.colYs[d+f]=c},_masonryGetContainerSize:function(){return{height:Math.max.apply(Math,this.masonry.colYs)}},_masonryResizeChanged:function(){return this._checkIfSegmentsChanged()},_fitRowsReset:function(){this.fitRows=
{x:0,y:0,height:0}},_fitRowsLayout:function(a){var b=this,c=this.element.width(),d=this.fitRows;a.each(function(){var a=e(this),g=a.outerWidth(!0),h=a.outerHeight(!0);if(d.x!==0&&g+d.x>c)d.x=0,d.y=d.height;b._pushPosition(a,d.x,d.y);d.height=Math.max(d.y+h,d.height);d.x+=g})},_fitRowsGetContainerSize:function(){return{height:this.fitRows.height}},_fitRowsResizeChanged:function(){return!0},_cellsByRowReset:function(){this.cellsByRow={index:0};this._getSegments();this._getSegments(!0)},_cellsByRowLayout:function(a){var b=
this,c=this.cellsByRow;a.each(function(){var a=e(this),f=~~(c.index/c.cols),g=(c.index%c.cols+0.5)*c.columnWidth-a.outerWidth(!0)/2,f=(f+0.5)*c.rowHeight-a.outerHeight(!0)/2;b._pushPosition(a,g,f);c.index++})},_cellsByRowGetContainerSize:function(){return{height:Math.ceil(this.$filteredAtoms.length/this.cellsByRow.cols)*this.cellsByRow.rowHeight+this.offset.top}},_cellsByRowResizeChanged:function(){return this._checkIfSegmentsChanged()},_straightDownReset:function(){this.straightDown={y:0}},_straightDownLayout:function(a){var b=
this;a.each(function(){var a=e(this);b._pushPosition(a,0,b.straightDown.y);b.straightDown.y+=a.outerHeight(!0)})},_straightDownGetContainerSize:function(){return{height:this.straightDown.y}},_straightDownResizeChanged:function(){return!0},_masonryHorizontalReset:function(){this.masonryHorizontal={};this._getSegments(!0);var a=this.masonryHorizontal.rows;for(this.masonryHorizontal.rowXs=[];a--;)this.masonryHorizontal.rowXs.push(0)},_masonryHorizontalLayout:function(a){var b=this,c=b.masonryHorizontal;
a.each(function(){var a=e(this),f=Math.ceil(a.outerHeight(!0)/c.rowHeight),f=Math.min(f,c.rows);if(f===1)b._masonryHorizontalPlaceBrick(a,c.rowXs);else{var g=c.rows+1-f,h=[],i,j;for(j=0;j<g;j++)i=c.rowXs.slice(j,j+f),h[j]=Math.max.apply(Math,i);b._masonryHorizontalPlaceBrick(a,h)}})},_masonryHorizontalPlaceBrick:function(a,b){for(var c=Math.min.apply(Math,b),d=0,f=0,e=b.length;f<e;f++)if(b[f]===c){d=f;break}x=c;y=this.masonryHorizontal.rowHeight*d;this._pushPosition(a,x,y);c+=a.outerWidth(!0);e=this.masonryHorizontal.rows+
1-e;for(f=0;f<e;f++)this.masonryHorizontal.rowXs[d+f]=c},_masonryHorizontalGetContainerSize:function(){return{width:Math.max.apply(Math,this.masonryHorizontal.rowXs)}},_masonryHorizontalResizeChanged:function(){return this._checkIfSegmentsChanged(!0)},_fitColumnsReset:function(){this.fitColumns={x:0,y:0,width:0}},_fitColumnsLayout:function(a){var b=this,c=this.element.height(),d=this.fitColumns;a.each(function(){var a=e(this),g=a.outerWidth(!0),h=a.outerHeight(!0);if(d.y!==0&&h+d.y>c)d.x=d.width,
d.y=0;b._pushPosition(a,d.x,d.y);d.width=Math.max(d.x+g,d.width);d.y+=h})},_fitColumnsGetContainerSize:function(){return{width:this.fitColumns.width}},_fitColumnsResizeChanged:function(){return!0},_cellsByColumnReset:function(){this.cellsByColumn={index:0};this._getSegments();this._getSegments(!0)},_cellsByColumnLayout:function(a){var b=this,c=this.cellsByColumn;a.each(function(){var a=e(this),f=c.index%c.rows,g=(~~(c.index/c.rows)+0.5)*c.columnWidth-a.outerWidth(!0)/2,f=(f+0.5)*c.rowHeight-a.outerHeight(!0)/
2;b._pushPosition(a,g,f);c.index++})},_cellsByColumnGetContainerSize:function(){return{width:Math.ceil(this.$filteredAtoms.length/this.cellsByColumn.rows)*this.cellsByColumn.columnWidth}},_cellsByColumnResizeChanged:function(){return this._checkIfSegmentsChanged(!0)},_straightAcrossReset:function(){this.straightAcross={x:0}},_straightAcrossLayout:function(a){var b=this;a.each(function(){var a=e(this);b._pushPosition(a,b.straightAcross.x,0);b.straightAcross.x+=a.outerWidth(!0)})},_straightAcrossGetContainerSize:function(){return{width:this.straightAcross.x}},
_straightAcrossResizeChanged:function(){return!0}};e.fn.imagesLoaded=function(a){var b=this.find("img"),c=b.length,d=this;b.length||a.call(this);b.bind("load",function(){--c<=0&&a.call(d)}).each(function(){if(this.complete||this.complete===v){var a=this.src;this.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";this.src=a}});return this};e.fn.isotope=function(a){if(typeof a==="string"){var b=Array.prototype.slice.call(arguments,1);this.each(function(){var c=e.data(this,
"isotope");if(!c)return e.error("cannot call methods on isotope prior to initialization; attempted to call method '"+a+"'");if(!e.isFunction(c[a])||a.charAt(0)==="_")return e.error("no such method '"+a+"' for isotope instance");c[a].apply(c,b)})}else this.each(function(){var b=e.data(this,"isotope");b?(b.option(a),b._init()):e.data(this,"isotope",new e.Isotope(a,this))});return this}})(window,jQuery);
