(function(f){function h(c){c.elem.style[c.prop]=parseInt(c.now,10)+c.unit}var p={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,
215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},i=function(c){return c&&c.indexOf("#")==
-1&&c.indexOf("(")==-1?"rgb("+p[c].toString()+")":c};f.extend(f.fx.step,{borderTopWidth:h,borderBottomWidth:h,borderLeftWidth:h,borderRightWidth:h});f.fn.revertFlip=function(){return this.each(function(){var c=f(this);c.flip(c.data("flipRevertedSettings"))})};f.fn.flip=function(c){return this.each(function(){var d=f(this),a,e,j,k;if(d.data("flipLock"))return false;var l={direction:function(b){switch(b){case "tb":return"bt";case "bt":return"tb";case "lr":return"rl";case "rl":return"lr";default:return"bt"}}(c.direction),
bgColor:i(c.color)||"#999",color:i(c.bgColor)||d.css("background-color"),content:d.html(),speed:c.speed||500,onBefore:c.onBefore||function(){},onEnd:c.onEnd||function(){},onAnimation:c.onAnimation||function(){}};d.data("flipRevertedSettings",l).data("flipLock",1).data("flipSettings",l);a={width:d.width(),height:d.height(),bgColor:i(c.bgColor)||d.css("background-color"),fontSize:d.css("font-size")||"12px",direction:c.direction||"tb",toColor:i(c.color)||"#999",speed:c.speed||500,top:d.offset().top,
left:d.offset().left,target:c.content||null,transparent:"transparent",dontChangeColor:c.dontChangeColor||false,onBefore:c.onBefore||function(){},onEnd:c.onEnd||function(){},onAnimation:c.onAnimation||function(){}};e=d.css("visibility","hidden").clone(true).data("flipLock",1).appendTo("body").html("").css({visibility:"visible",position:"absolute",left:a.left,top:a.top,margin:0,zIndex:9999});var m=function(){return{backgroundColor:a.transparent,fontSize:0,lineHeight:0,borderTopWidth:0,borderLeftWidth:0,
borderRightWidth:0,borderBottomWidth:0,borderTopColor:a.transparent,borderBottomColor:a.transparent,borderLeftColor:a.transparent,borderRightColor:a.transparent,background:"none",borderStyle:"solid",height:0,width:0}},n=function(){var b=a.height/100*25,g=m();g.width=a.width;return{start:g,first:{borderTopWidth:0,borderLeftWidth:b,borderRightWidth:b,borderBottomWidth:0,borderTopColor:"#999",borderBottomColor:"#999",top:a.top+a.height/2,left:a.left-b},second:{borderBottomWidth:0,borderTopWidth:0,borderLeftWidth:0,
borderRightWidth:0,borderTopColor:a.transparent,borderBottomColor:a.transparent,top:a.top,left:a.left}}},o=function(){var b=a.height/100*25,g=m();g.height=a.height;return{start:g,first:{borderTopWidth:b,borderLeftWidth:0,borderRightWidth:0,borderBottomWidth:b,borderLeftColor:"#999",borderRightColor:"#999",top:a.top-b,left:a.left+a.width/2},second:{borderTopWidth:0,borderLeftWidth:0,borderRightWidth:0,borderBottomWidth:0,borderLeftColor:a.transparent,borderRightColor:a.transparent,top:a.top,left:a.left}}};
j={tb:function(){var b=n();b.start.borderTopWidth=a.height;b.start.borderTopColor=a.bgColor;b.second.borderBottomWidth=a.height;b.second.borderBottomColor=a.toColor;return b},bt:function(){var b=n();b.start.borderBottomWidth=a.height;b.start.borderBottomColor=a.bgColor;b.second.borderTopWidth=a.height;b.second.borderTopColor=a.toColor;return b},lr:function(){var b=o();b.start.borderLeftWidth=a.width;b.start.borderLeftColor=a.bgColor;b.second.borderRightWidth=a.width;b.second.borderRightColor=a.toColor;
return b},rl:function(){var b=o();b.start.borderRightWidth=a.width;b.start.borderRightColor=a.bgColor;b.second.borderLeftWidth=a.width;b.second.borderLeftColor=a.toColor;return b}}[a.direction]();k=function(){var b=a.target;return b&&b.jquery?b.html():b};e.queue(function(){a.onBefore(e,d);e.html("").css(j.start);e.dequeue()});e.animate(j.first,a.speed);e.queue(function(){a.onAnimation(e,d);e.dequeue()});e.animate(j.second,a.speed);e.queue(function(){a.dontChangeColor||d.css({backgroundColor:a.toColor});
d.css({visibility:"visible"});var b=k();b&&d.html(b);e.remove();a.onEnd(e,d);d.removeData("flipLock");e.dequeue()})})}})(jQuery);
