$.jCore={functions:[],plugins:[],extend:function(a,e){if(typeof a=="function")return $.jCore.functions[$.jCore.functions.length]=a,$(document).each(a),true;typeof a=="string"&&typeof e=="undefined"&&(e=a,a="");$.jCore.plugins[$.jCore.plugins.length]={selector:a,plugin:e}},url:{genPathFromString:function(a){a=a.replace(/(<([^>]+)>)/ig,"");a=a.replace(" ","-");return a=a.replace(/([^a-z^0-9^_^-]*)/ig,"")}},tooltip:{display:function(a,e){$.loading(false);e==true?$.loading(true,{html:a,text:"",max:5E3}):
$.loading(true,{text:a,max:5E3})}},form:{INPUT_TYPE_TEXT:1,INPUT_TYPE_EMAIL:2,INPUT_TYPE_FILE:12,appendEntryTo:function(a,e,c,b,d,f,g){if(typeof a=="undefined")return false;d="";d+="<div class='form-entry form-entry-"+$.jCore.url.genPathFromString(c)+"'><div class='form-entry-title'>"+e+"</div><div class='form-entry-content'>";d+=b==this.INPUT_TYPE_TEXT||b==this.INPUT_TYPE_EMAIL?"<input type='text' name='"+c+"' class='text-entry' value='"+f+"' "+g+"/> ":b==this.INPUT_TYPE_FILE?"<input type='file' name='"+
c+"' class='file-entry' value='"+f+"' "+g+"/> ":"This type is not supported yet! ";d+="<a href='javascript://' class='remove-link' onclick=\"$.jCore.form.removeEntry(this);\">Remove</a></div></div>";$(a).append(d);return true},removeEntry:function(a){if(typeof a=="undefined")return false;$(a).closest(".form-entry").remove();return true}},hasFlash:function(){if(navigator.plugins&&navigator.plugins.length){if(navigator.plugins["Shockwave Flash"])return true;if(navigator.plugins["Shockwave Flash 2.0"])return true}else if(navigator.mimeTypes&&
navigator.mimeTypes.length){var a=navigator.mimeTypes["application/x-shockwave-flash"];return a&&a.enabledPlugin}else try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),true}catch(e){try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),true}catch(c){try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),true}catch(b){}}}return false},modules:{}};
$.fn.extend({jCore:function(){this.each(function(){var a=$(this);typeof $.loading!="undefined"&&$.loading({onAjax:true,delay:1E3});typeof $().fcToggle!="undefined"&&a.find(".fc-title").fcToggle();typeof $().mailme!="undefined"&&a.find(".mailme").mailme();typeof $().rating!="undefined"&&a.find(".star-rating").rating();typeof $().corner!="undefined"&&(a.find(".rounded-corners-top").corner("top 5px"),a.find(".rounded-corners-bottom").corner("bottom 5px"),a.find(".rounded-corners").corner("5px"));typeof $().dropDownMenu!=
"undefined"&&a.find("#main-menu .menu").dropDownMenu();if(typeof JCORE_VERSION=="undefined"||JCORE_VERSION<"0.6")a.find(".list tbody tr").mouseenter(function(){$(this).addClass("hilight")}),a.find(".list tbody tr").mouseleave(function(){$(this).removeClass("hilight")});a.find(".confirm-link").click(function(){var a=$(this),b=confirm((a.attr("title")||a.attr("original-title")||a.attr("value")||a.text()||"Please confirm your action")+"?!");if(b&&this.tagName.toLowerCase()=="a"){var a=a.attr("href"),
d=a.match(/.*&(.*?)=(.*?)$/);if(d&&d[1]&&d[2])return b=$("<form action='"+a+"' method='post'><input type='hidden' name='_SecurityToken' value='"+JCORE_SECURITY_TOKEN+"' /><input type='hidden' name='"+d[1]+"' value='"+d[2]+"' /></form>"),$("body").append(b),b.submit(),false}return b});typeof $().ajaxLink!="undefined"&&a.find(".ajax-link").ajaxLink();typeof $().ajaxDownloadLink!="undefined"&&a.find(".ajax-download-link").ajaxDownloadLink();typeof $().ajaxForm!="undefined"&&a.find("form.ajax-form").ajaxForm();
typeof $().ajaxContentLink!="undefined"&&a.find(".ajax-content-link").ajaxContentLink();typeof $().ajaxLightboxLink!="undefined"&&a.find(".ajax-lightbox-link").ajaxLightboxLink();typeof $().ajaxPaging!="undefined"&&a.find(".paging-ajax a").ajaxPaging();a.find(".checkbox-all").click(function(){var a=$(this),b=this.checked,d="form";a.attr("alt")&&(d=a.attr("alt"));a.parents(d).find("input[type=checkbox]").each(function(){this.checked=b})});typeof $().datepicker!="undefined"&&a.find(".calendar-input").each(function(){var a=
"",b=$(this);b.is(".timestamp")?(a=new Date,a="yy-mm-dd "+a.getHours()+":"+a.getMinutes()+":00"):a="yy-mm-dd";b.datepicker({showAnim:"fadeIn",dateFormat:a}).after($("<a class='clear-calendar-input'>&nbsp;</a>").click(function(){$(this).parent().find("input").val("");return false})).after($("<a class='show-calendar-input'>&nbsp;</a>").click(function(){$(this).parent().find("input").focus();return false}))});typeof $().ColorPicker!="undefined"&&a.find(".color-input").each(function(){$(this).ColorPicker({onBeforeShow:function(){$(this).ColorPickerSetColor(this.value)}}).after($("<a class='clear-color-input'>&nbsp;</a>").click(function(){$(this).parent().find("input").val("");
return false})).after($("<a class='show-color-input'>&nbsp;</a>").click(function(){$(this).parent().find("input").focus();return false}))});typeof $().lightBox!="undefined"&&$(function(){var c=[];a.find("a[rel^=lightbox]").each(function(){if(typeof c[this.rel]=="undefined")c[this.rel]=this.rel,c.length++});if(c.length)for(var b in c)typeof c[b]=="string"&&a.find('a[rel="'+c[b].replace(/([^a-z0-9\-_])/g,"$1")+'"]').lightBox()});typeof $().lightBox!="undefined"&&$(function(){var c=[];a.find("a[rel^=videolightbox]").each(function(){if(typeof c[this.rel]==
"undefined")c[this.rel]=this.rel,c.length++});if(c.length)for(var b in c)typeof c[b]=="string"&&a.find('a[rel="'+c[b].replace(/([^a-z0-9\-_])/g,"$1")+'"]').lightBox({disableSlideShow:true,disableDownload:true,ajaxContent:true,fixedNavigation:true,txtImage:"Video"})});typeof $().qtip!="undefined"&&a.find(".qtip").qtip({style:{name:"cream",tip:true},position:{adjust:{screen:true}}});typeof $().tipsy!="undefined"&&(a.find(".list td[title]").tipsy({delayIn:100,html:true,gravity:"w"}),a.find(".tip,.list a[title],.admin-section-item [title],.button[title],.attachment [title],.star-rating [title],.comment-rating-up,.comment-rating-down").tipsy({delayIn:100,
html:true}),a.find(".calendar-input[title],.timestamp[title],.color-input[title]").tipsy({trigger:"focus",gravity:"w",offset:50}),a.find("input[type=file][title]").tipsy({delayIn:100,trigger:"hover",gravity:"w"}),a.find("input[title],textarea[title],select[title]").tipsy({trigger:"focus",gravity:"w"}));typeof $().tabby!="undefined"&&a.find("textarea.code-editor").tabby();typeof $().keypad!="undefined"&&a.find('input[type="password"]').keypad({showAnim:"fadeIn",duration:"fast",keypadOnly:false,layout:$.keypad.qwertyLayout})});
if($.jCore.plugins.length>0)for(var a=0;a<$.jCore.plugins.length;a++)if($.jCore.plugins[a].selector)if(typeof $.jCore.plugins[a].plugin=="function")this.find($.jCore.plugins[a].selector).each($.jCore.plugins[a].plugin);else{if(typeof $.fn[$.jCore.plugins[a].plugin]!="undefined")this.find($.jCore.plugins[a].selector)[$.jCore.plugins[a].plugin]()}else this[$.jCore.plugins[a].plugin]();if($.jCore.functions.length>0)for(a=0;a<$.jCore.functions.length;a++)this.each($.jCore.functions[a]);return this}});
