(function(h){ChiliBook={version:"2.2",automatic:true,automaticSelector:"code",lineNumbers:false,codeLanguage:function(A){return(A=h(A).attr("class"))?A:""},recipeLoading:true,recipeFolder:"",replaceSpace:"&#160;",replaceTab:"&#160;&#160;&#160;&#160;",replaceNewLine:"&#160;<br/>",selectionStyle:"position:absolute; z-index:3000; overflow:scroll; width:16em; height:9em; border:1px solid gray; padding:15px; background-color:yellow;",defaultReplacement:'<span class="$0">$$</span>',recipes:{},queue:{},
unique:function(){return(new Date).valueOf()}};h.fn.chili=function(A){function D(c,i,a){function d(b,m,n){var p=b[m][n],j=typeof p._match=="string"?p._match:p._match.source;return{recipe:b,blockName:m,stepName:n,exp:"("+j+")",length:1+(j.replace(/\\./g,"%").replace(/\[.*?\]/g,"%").match(/\((?!\?)/g)||[]).length,replacement:p._replace?p._replace:f.defaultReplacement}}function e(b){for(var m=1,n=[],p=0;p<b.length;p++){var j=b[p].exp;j=j.replace(/\\\\|\\(\d+)/g,function(l,o){return!o?l:"\\"+(m+1+parseInt(o,
10))});n.push(j);m+=b[p].length}b="(?:"+n.join("|")+")";b="((?:\\s|\\S)*?)"+b+"|((?:\\s|\\S)+)";return RegExp(b,i._case?"g":"gi")}function k(b){return b.replace(/ +/g,function(m){return m.replace(/ /g,t)})}function g(b){b=b.replace(/&/g,"&amp;").replace(/</g,"&lt;");if(t)b=k(b);return b}function u(b,m,n,p){var j=[d(m,n,p)];return b.replace(e(j),function(){return v.apply({steps:j},arguments)})}function s(b,m,n){function p(r){r=f.recipes[f.recipeFolder+r+".js"];if(!r)throw{msg:"recipe not available"};
return r}if(!m)return g(b);var j=m.split("/"),l="",o="",w="";switch(j.length){case 1:l=j[0];break;case 2:l=j[0];o=j[1];break;case 3:l=j[0];o=j[1];w=j[2];break;default:return g(b)}try{var q;if(""==w)if(""==o){if(""!=l){q=p(l);return D(b,q)}}else{q=""==l?n.recipe:p(l);if(!(o in q))return g(b);return D(b,q,o)}else{q=""==l?n.recipe:p(l);if(""==o)o=n.blockName;if(!(o in q))return g(b);if(!(w in q[o]))return g(b);return u(b,q,o,w)}}catch(y){if(y.msg&&y.msg=="recipe not available"){j="chili_"+f.unique();
if(f.recipeLoading){var x=f.recipeFolder+l+".js";if(f.queue[x])f.queue[x].push({cue:j,subject:b,module:m,context:n});else try{f.queue[x]=[{cue:j,subject:b,module:m,context:n}];h.ajax({url:x,dataType:"text",success:function(r){f.recipes[x]=window.eval("(function() { var recipe = "+r+"; return recipe; }())");r=f.queue[x];for(var z=0,G=r.length;z<G;z++){var B=s(r[z].subject,r[z].module,r[z].context);if(f.replaceTab)B=B.replace(/\t/g,f.replaceTab);if(f.replaceNewLine)B=B.replace(/\n/g,f.replaceNewLine);
h("#"+r[z].cue).replaceWith(B)}}})}catch(L){alert("the recipe for '"+l+"' was not found in '"+x+"'")}return'<span id="'+j+'">'+g(b)+"</span>"}}return g(b)}}function v(){if(!arguments[0])return"";var b=this.steps,m=0,n=2,p=arguments[1],j=arguments[arguments.length-3];if(j)return g(j);else for(var l;l=b[m++];){var o=arguments;if(o[n]){b="";if(h.isFunction(l.replacement)){b=[];m=0;for(j=l.length;m<j;m++)b.push(o[n+m]);b.push(o[o.length-2]);b.push(o[o.length-1]);b=l.replacement.apply({x:function(w,q){return s(w,
q,{recipe:l.recipe,blockName:l.blockName})}},b)}else b=l.replacement.replace(/(\\\$)|(?:\$\$)|(?:\$(\d+))/g,function(w,q,y){return q?"$":y?y=="0"?l.stepName:g(o[n+parseInt(y,10)]):g(o[n])});b=b.replace(/(<span\s+class\s*=\s*(["']))((?:(?!__)\w)+\2\s*>)/ig,"$1"+l.recipe._name+"__$3");return g(p)+b}else n+=l.length}}if(!a){a="_main";H(i)}if(!(a in i))return g(c);var t=f.replaceSpace,C=function(b,m){var n=[],p;for(p in b[m])n.push(d(b,m,p));return n}(i,a);a=e(C);return c.replace(a,function(){return v.apply({steps:C},
arguments)})}function H(c){var i=c._name;if(!f.queue[i]){var a=["/* Chili -- "+i+" */"],d;for(d in c)if(d.search(/^_(?!main\b)/)<0)for(var e in c[d]){var k=c[d][e];if("_style"in k)if(k._style.constructor==String)a.push("."+i+"__"+e+" { "+k._style+" }");else for(var g in k._style)a.push("."+i+"__"+g+" { "+k._style[g]+" }")}a=a=a.join("\n");if(document.createElement){c=document.createElement("style");c.type="text/css";if(c.styleSheet)c.styleSheet.cssText=a;else{a=document.createTextNode(a);c.appendChild(a)}document.getElementsByTagName("head")[0].appendChild(c)}f.queue[i]=
true}}function I(c){var i=f.codeLanguage(c);if(""!=i){var a=f.recipeFolder+i+".js";if(f.recipeLoading)if(f.queue[a])f.queue[a].push(c);else try{f.queue[a]=[c];h.ajax({url:a,dataType:"text",success:function(e){f.recipes[a]=window.eval("(function() { var recipe = "+e+"; return recipe; }())");e=f.queue[a];for(var k=0,g=e.length;k<g;k++)E(e[k],a)}})}catch(d){alert("the recipe for '"+i+"' was not found in '"+a+"'")}E(c,a)}}function E(c,i){var a=f.recipes[i];if(a){var d=h(c),e=d.text();if(e){e=e.replace(/\r\n?/g,
"\n");if(d.parent().is("pre"))h.browser.safari||(e=e.replace(/^\n/g,""));a=D(e,a);if(f.replaceTab)a=a.replace(/\t/g,f.replaceTab);if(f.replaceNewLine)a=a.replace(/\n/g,f.replaceNewLine);c.innerHTML=a;if(h.browser.msie||h.browser.mozilla)J(c);a=d.parent();if(e=/ln-(\d+)-([\w][\w\-]*)|ln-(\d+)|ln-/.exec(a.attr("class"))){F(c);var k=0;if(e[1]){k=parseInt(e[1],10);e=h(".ln-"+e[1]+"-"+e[2]);a=e.index(a[0]);e.slice(0,a).each(function(){k+=h(this).find("li").length})}else k=e[3]?parseInt(e[3],10):1;d.find("ol")[0].start=
k;h("body").width(h("body").width()-1).width(h("body").width()+1)}else f.lineNumbers&&F(c)}}}function J(c){var i=null;h(c).parents().filter("pre").bind("mousedown",function(){i=this;h.browser.msie?document.selection.empty():window.getSelection().removeAllRanges()}).bind("mouseup",function(a){if(i&&i==this){i=null;var d="";if(h.browser.msie){d=document.selection.createRange().htmlText;if(""==d)return;d=K(d);var e='<textarea style="STYLE">'}else{d=window.getSelection().toString();if(""==d)return;d=
d.replace(/\r/g,"").replace(/^# ?/g,"").replace(/\n# ?/g,"\n");e='<pre style="STYLE">'}d=h(e.replace(/\bSTYLE\b/,ChiliBook.selectionStyle)).appendTo("body").text(d).attr("id","chili_selection").click(function(){h(this).remove()});e=a.pageY-Math.round(d.height()/2)+"px";a=a.pageX-Math.round(d.width()/2)+"px";d.css({top:e,left:a});if(h.browser.msie){d[0].focus();d[0].select()}else{a=window.getSelection();a.removeAllRanges();e=document.createRange();e.selectNodeContents(d[0]);a.addRange(e)}}})}function K(c){do var i=
ChiliBook.unique();while(c.indexOf(i)>-1);var a="";if(/<br/i.test(c)||/<li/i.test(c)){if(/<br/i.test(c))c=c.replace(/\<br[^>]*?\>/ig,i);else if(/<li/i.test(c))c=c.replace(/<ol[^>]*?>|<\/ol>|<li[^>]*?>/ig,"").replace(/<\/li>/ig,i);var d=h("<pre>").appendTo("body").hide()[0];d.innerHTML=c;a=h(d).text().replace(RegExp(i,"g"),"\r\n");h(d).remove()}return a}function F(c){function i(k,g,u,s){var v=s?"</span>":"",t="";if(k)t="<li>"+s+g+v+"</li>";else if(u)t="<li>"+s+u+v+"</li>";return t}var a=h(c).html(),
d=/<br>/.test(a)?"<br>":"<BR>",e="<li>"+f.replaceSpace+"</li>";a=a.replace(/(<span [^>]+>)((?:(?:&nbsp;|\xA0)<br>)+)(.*?)(<\/span>)/ig,"$2$1$3$4").replace(/(.*?)(<span .*?>)(.*?)(?:<\/span>(?:&nbsp;|\xA0)<br>|<\/span>)/ig,function(k,g,u,s){if(/<br>/i.test(s)){g=g.split(d);k=g.pop();g=g.join(d);return(g?g+d:"")+(k+s).replace(/((.*?)(?:&nbsp;|\xA0)<br>)|(.*)/ig,function(v,t,C,b){return i(t,C,b,u)})}else return k}).replace(/(<li>.*?<\/li>)|((.*?)(?:&nbsp;|\xA0)<br>)|(.+)/ig,function(k,g,u,s,v){k="";
return k=g?g:i(u,s,v,"")}).replace(/<li><\/li>/ig,e);c.innerHTML="<ol>"+a+"</ol>"}var f=h.extend({},ChiliBook,A||{});this.each(function(){var c=h(this);c.trigger("chili.before_coloring");I(this);c.trigger("chili.after_coloring")});return this};h(function(){ChiliBook.automatic&&h(ChiliBook.automaticSelector).chili()})})(jQuery);
