/*
 Copyright (c) 2009-2010 Petr Vostrel (http://petr.vostrel.cz/)
 Dual licensed under the MIT (MIT-LICENSE.txt)
 and GPL (GPL-LICENSE.txt) licenses.

 jQuery Reel
 http://jquery.vostrel.cz/reel
 Version: 1.1
 Updated: 2010-11-27

 Requires jQuery 1.4.2 or higher
*/
jQuery.reel||function(k,ca,Ta,q){function H(m){return+m.toFixed(4)}function S(m,a,w){return T(m,za(a,w))}k.reel={version:"1.1",def:{footage:6,frame:1,frames:36,hint:"",horizontal:true,hotspot:q,indicator:0,klass:"",loops:true,reversed:q,spacing:0,stitched:q,suffix:"-reel",tooltip:"",area:q,brake:0.5,clickfree:false,cw:false,delay:-1,directional:false,draggable:true,entry:q,graph:q,image:q,images:[],inversed:false,laziness:8,monitor:q,opening:0,orbital:0,path:"",preloader:4,rebound:0.5,revolution:q,
row:1,rows:0,speed:0,step:q,steps:q,tempo:36,timeout:2,throwable:true,vertical:false,wheelable:true}};k.fn.reel=function(m){var a=k.extend({},k.reel.def,m);m=function(f){var e=[];f.filter(Ua).each(function(){var c=k(this),s=a.images.length&&a.images||a.image||c.attr(Aa),l=U(c.css(Ba)),x=U(c.css(Ca));!s||s==Da||!l||!x||e.push(c)});f.filter(Ea+("."+z)).each(function(){e.push(k(this))});return k(e)}(this);var w=[],I=a.tempo/=Va?a.laziness:1,J=1E3/I;a.reversed&&(a.cw=true);a.tooltip&&(a.hint=a.tooltip);
a.hotspot&&(a.area=a.hotspot);da=da||function f(){A.trigger(F);return setTimeout(f,J)}();m.each(function(){var f=k(this),e=function(h,b){f.data(h,b);f.trigger("store",[h,b]);return b},c=function(h){var b=f.data(h);f.trigger("recall",[h,b]);return b},s={setup:function(h){if(f.hasClass(z))return l.call(h);var b=f.attr(Aa),d=f.attr(Wa),g=f.attr("style"),i=a.images,j=a.stitched,n=a.loops,p={x:U(f.css(Ba)),y:U(f.css(Ca))},t=e(Fa,a.orbital&&a.footage||a.rows<=1&&i.length||a.frames),C=j?1:Ga(t/a.footage),
v={display:"block",width:p.x,height:p.y};d="#"+d+a.suffix;var Ha=f.attr("className"),ea={position:"relative",width:p.x,height:p.y};ea=k(O,{id:d.substr(1),className:Ha+V+Xa,css:ea});v=f.wrap(ea).attr({className:z}).css(v).bind(s);w.push(v[0]);e(fa,i.length&&i.length||a.image||b.replace(/^(.*)\.(jpg|jpeg|png|gif)$/,"$1"+a.suffix+".$2"));e(Ia,Ha);e(D,a.frame);e(Ja,a.spacing);e(E,p);e(o,0);e(ga,a.steps||a.frames);e(W,a.revolution||j/2||p.x*2);e(ha,C);e(X,1/(t-(n&&!j?0:1)));e(Ya,1/T(t,c(ga)));e(ia,j);
e(Ka,j-(n?0:p.x));e(Y,d);e(G,e(ja,a.speed)<0);e(K,0);e(L,a.vertical);e(B,(a.row-1)/(a.rows-1));e(Z,u(1)*(!a.cw&&!j?-1:1));e(La,{src:b,style:g||Da});da&&A.bind(F,s.tick);l.call(h);f.trigger("start")},teardown:function(h){f.unbind(r).unbind(s);var b=f.data("events"),d=f.clone().attr(f.data(La)).removeClass(z).addClass(c(Ia)),g;for(g in b)k.each(b[g],function(i,j){d.bind(g+"."+j.namespace,j.handler,j.data)});k("img:hidden",f.parent()).remove();k(c(Y)).before(d).detach();y=[0,0];A.unbind(ka).unbind(la).unbind(F,
s.tick).unbind(F,s.opening_tick);l.call(h)},start:function(){var h=c(E),b=c(Fa),d=T(b,c(ga));d=e(o,1/d*((a.step||a.frame)-1));e(D,d*b+1);f.attr("id");b=f.parent();d=k(O,{className:Za,css:{position:$,left:0,top:0,width:h.x,height:h.y,background:ma,opacity:0}}).appendTo(b);d=e(Ma,k(a.area||d));if($a){f.css({WebkitUserSelect:"none",WebkitBackgroundSize:a.images.length?"auto":c(ia)&&c(ia)+"px "+h.y+"px"||h.x*a.footage+"px "+h.y*c(ha)*(a.rows||1)*(a.directional?2:1)+"px"});d.bind(ab,function(g){f.trigger("down",
[g.originalEvent.touches[0].clientX,g.originalEvent.touches[0].clientY,true]);return false}).bind(bb,function(g){f.trigger("slide",[g.originalEvent.touches[0].clientX,g.originalEvent.touches[0].clientY,true]);return false}).bind(cb,function(){f.trigger("up",[true]);return false}).bind(db,function(){f.trigger("up",[true]);return false})}else d.css({cursor:"url("+Na+"), "+na}).bind(eb,function(g,i){f.trigger("wheel",[i]);return false}).bind(fb,function(){f.trigger("play")}).bind(a.clickfree?gb:hb,function(g){f.trigger("down",
[g.clientX,g.clientY]);return false}).bind(a.clickfree?ib:"",function(){f.trigger("up");return false}).disableTextSelect();a.hint&&d.attr(jb,a.hint);a.monitor&&b.append(oa=k(O,{className:kb,css:{position:$,left:0,top:0}}))||(oa=k());a.indicator&&b.append(Oa("x"));a.rows>1&&a.indicator&&b.append(Oa("y"));f.trigger("preload")},preload:function(h){var b=c(E),d=f.parent(),g=c(fa),i=a.images;g=!i.length?[g]:[].concat(i);var j=f[0];j.frames=g.length;j.preloaded=0;f.trigger("stop");for(d.append(pa=k(O,{className:lb,
css:{position:$,left:0,top:b.y-a.preloader,height:a.preloader,backgroundColor:ma}}));g.length;){i=a.path+g.shift();var n=k(new Image).bind("load"+r,function(){j.preloaded++;k(this).unbind(r);pa.css({width:1/j.frames*j.preloaded*b.x});if(j.frames==j.preloaded){pa.remove();f.trigger(a.rows>1&&!a.stitched?"rowChange":"frameChange");f.attr({src:mb}).trigger("loaded");f.trigger("opening");l.call(h)}});d.append(n.hide().attr({src:i}))}},tick:function(h){var b=c(K);if(P){var d=H(b-nb*P);b=!(b*d<=0||b<u(d))&&
e(K,b>u(c(ja))?d:P=x=0)}oa.text(c(a.monitor));b&&P++;x&&x++;y.push(0)&&y.shift();slidable=true;if(x&&!b)return l.call(h);if(c(qa))return l.call(h,M());d=c(Z);var g;g=c(G);g=u(1)*(g?-1:1);d=d*g;g=(c(ra)?b:u(c(ja))+b)/a.tempo;b=c(o);d=e(o,b-g*d);l.call(h);d!=b&&f.trigger("fractionChange")},opening:function(){var h=a.entry||a.speed,b=c(o),d=a.opening;e(o,b-h*a.opening);e(sa,d*I);A.bind(F,s.opening_tick)},opening_tick:function(h){var b=(a.entry||a.speed)/a.tempo*(a.cw?-1:1),d=c(o);e(o,H(d+b));b=e(sa,
c(sa)-1);f.trigger("fractionChange");l.call(h);if(!(b>1)){A.unbind(F,s.opening_tick);ob()}},play:function(h){var b=e(ta,true);e(ra,!b);x=0;l.call(h)},pause:function(h){e(ta,false);M();l.call(h)},stop:function(h){var b=e(ra,true);e(ta,!b);l.call(h)},down:function(h,b,d,g){if(a.draggable){e(qa,true);e(K,0);aa=ba(b,d,c(o),c(W),c(B));M();y=[0,0];if(!g){A.css({cursor:"url("+pb+"), "+na}).bind(la,function(i){f.trigger("slide",[i.clientX,i.clientY]);l.call(i);return false});a.clickfree||A.bind(ka,function(i){f.trigger("up");
l.call(i)})}}l.call(h)},up:function(h,b){if(!a.draggable)return l.call(h);e(qa,false);var d=e(K,!a.throwable?0:u(y[0]+y[1])/60);P=d?1:0;d?x=0:M();y=[0,0];!b&&A.unbind(ka).unbind(la)&&c(Ma).css({cursor:"url("+Na+"), "+na});l.call(h)},slide:function(h,b,d){if(a.draggable&&slidable){slidable=false;M();var g={x:b-aa.x,y:d-aa.y};if(u(g.x)>0||u(g.y)>0){aa={x:b,y:d};var i=c(W),j=c(Pa),n=c(L),p=e(o,Qa(n?d-j.y:b-j.x,c(ua),i,c(va),c(wa),c(Z)));(g=y.push(n?g.y:g.x||0)&&y.shift()&&(n?g.y:g.x||0))&&e(G,g<0);if(a.orbital)var t=
a.orbital,C=a.footage,v=c(D);if(a.orbital&&(v<=t||v>=C-t+2&&v<=C+t-1||v==2*C-t+2)){e(L,u(d-j.y)>u(b-j.x));j=ba(b,d,p,i,c(B))}if(a.rows>1){t=c(E).y;C=c(Ra);v=-C*t;e(B,H(k.reel.math.envelope(d-j.y,C,t,v,v+t,-1)))}!(p%1)&&!a.loops&&ba(b,d,p,i,c(B));f.trigger("fractionChange")}}l.call(h)},wheel:function(h,b){if(!a.wheelable)return l.call(h);var d=Ga(qb(u(b))/2);d=u(d)*(b>0?-1:1);var g=0.2*c(W);ba(q,q,c(o),g,c(B));e(o,Qa(d,c(ua),g,c(va),c(wa),c(Z)));d&&e(G,d<0);e(K,0);M();l.call(h);f.trigger("fractionChange");
return false},fractionChange:function(h,b){b=!b?c(o):e(o,b);b=a.loops?b-Q(b):S(0,1,b);b=e(o,H(b));var d=c(D),g=e(D,1+Q(b/c(X)));if(!a.loops&&a.rebound){!x&&!(b%1)?xa++:xa=0;xa>=a.rebound*1E3/a.tempo&&e(G,!c(G))}var i=c(E),j=(c(L)?i.y:i.x)-a.indicator,n=S(0,j,R(k.reel.math.interpolate(b,-1,j+2)));n=!a.cw||a.stitched?n:j-n;k("."+(ya+".x"),c(Y)).css(c(L)?{left:0,top:n}:{left:n,top:i.y-a.indicator});if(a.rows>1){i=c(E).y-a.indicator;i=S(0,i,R(k.reel.math.interpolate(c(B),-1,i+2)));k("."+(ya+".y"),c(Y)).css({top:i})}if(g==
d)return l.call(h);f.trigger(a.rows>1?"rowChange":"frameChange");l.call(h)},rowChange:function(h,b){var d=Q(c(o)/c(X))+1;b=e(B,S(0,1,H(b!=q?(b-1)/(a.rows-1):c(B))));e(D,d+(a.rows<=1?0:R(b*(a.rows-1))*a.frames));l.call(h);f.trigger("frameChange")},frameChange:function(h,b){var d=!b?c(o):e(o,H(c(X)*(b-1)));b=e(D,R(b?b:c(D)));var g=a.images,i=a.footage,j=c(E),n=a.horizontal;if(c(L)){b=a.inversed?i+1-b:b;b+=i}if(g.length){g=g[b-1];f.attr({src:a.path+g})}else{if(a.stitched)n=[-R(d*c(Ka))+N,0+N];else{d=
b%i-1;d=d<0?i-1:d;var p=Q((b-0.1)/i);p+=a.rows>1?0:c(G)?0:c(ha);i=c(Ja);p=p*((n?j.y:j.x)+i);j=d*((n?j.x:j.y)+i);n=g.length?[0,0]:n?[-j+N,-p+N]:[-p+N,-j+N]}g=c(fa);f.css({background:"url("+(a.path+g)+")"+V+n.join(V)})}l.call(h)}},l=function(h){rb||delete this;return h},x,P=0,M=function(){clearTimeout(Sa);A.unbind(F,s.opening_tick);f.trigger("play");return x=-a.timeout*a.tempo},Sa,ob=function(){Sa=setTimeout(function(){f.trigger("play")},a.delay*1E3||0)},oa,pa,Oa=function(h){return k(O,{className:[ya,
h].join(V),css:{width:a.indicator,height:a.indicator,top:c(E).y-a.indicator,left:0,position:$,backgroundColor:ma}})},xa=0,aa={x:0,y:0},y=y=[0,0],nb=a.brake/a.tempo,Qa=a.graph||k.reel.math[a.loops?"hatch":"envelope"],ba=function(h,b,d,g,i){e(ua,d);e(Ra,i);e(va,a.loops?0:-d*g);e(wa,a.loops?g:g-d*g);return h&&e(Pa,{x:h,y:b})||q};s.setup()});return k(w)};k.reel.math={envelope:function(m,a,w,I,J,f){return a+T(I,za(J,-m*f))/w},hatch:function(m,a,w,I,J,f){m=(m<I?J:0)+m%J;m=a+-m*f/w;return m-Q(m)},interpolate:function(m,
a,w){return a+m*(w-a)}};(function(m){k.each(m,function(){k.fn[this]||(k.fn[this]=function(){return this})})})("mousewheel disableTextSelect enableTextSelect".split(/ /));var A=k(Ta);ca=navigator.userAgent;var $a=/iphone|ipod|ipad|android/i.test(ca),Va=/iphone|ipod|ipad/i.test(ca),rb=k.browser.msie,na="ew-resize",da,z="jquery-reel",Xa=z+"-overlay",ya=z+"-indicator",lb=z+"-preloader",kb=z+"-monitor",Za=z+"-interface",mb="data:image/gif;base64,R0lGODlhCAAIAIAAAAAAAAAAACH5BAEAAAAALAAAAAAIAAgAAAIHhI+py+1dAAA7",
Na="data:image/gif;base64,R0lGODlhEAAQAJECAAAAAP///////wAAACH5BAEAAAIALAAAAAAQABAAQAI3lC8AeBDvgosQxQtne7yvLWGStVBelXBKqDJpNzLKq3xWBlU2nUs4C/O8cCvU0EfZGUwt19FYAAA7",pb="data:image/gif;base64,R0lGODlhEAAQAJECAAAAAP///////wAAACH5BAEAAAIALAAAAAAQABAAQAIslI95EB3MHECxNjBVdE/5b2zcRV1QBabqhwltq41St4hj5konmVioZ6OtEgUAOw==",R=Math.round,Q=Math.floor,Ga=Math.ceil,za=Math.min,T=Math.max,u=Math.abs,qb=Math.sqrt,U=parseInt,Ma="area",La="backup",G="backwards",X="bit",Ia="classes",qa="clicked",Pa="clicked_location",
ua="clicked_on",Ra="clicked_row",Z="cwish",E="dimensions",o="fraction",D="frame",Fa="frames",wa="hi",fa="image",sa="opening_ticks",va="lo",ta="playing",W="revolution",B="row",ha="rows",Ja="spacing",ja="speed",Y="stage",ga="steps",ia="stitched",Ka="stitched_travel",ra="stopped",K="velocity",L="vertical",Ya="wheel_step",r=".reel",fb="dblclick"+r,hb="mousedown"+r,gb="mouseenter"+r,ib="mouseleave"+r,la="mousemove"+r,ka="mouseup"+r,eb="mousewheel"+r,F="tick"+r,db="touchcancel"+r,cb="touchend"+r,ab="touchstart"+
r,bb="touchmove"+r,Da="",V=" ",$="absolute",Ea="div",O="<"+Ea+"/>",Ca="height",ma="#000",Wa="id",Ua="img",N="px",Aa="src",jb="title",Ba="width"}(jQuery,window,document);
