$.jCore={url:{genPathFromString:function(a){a=a.replace(/(<([^>]+)>)/ig,"");a=a.replace(" ","-");return a=a.replace(/([^a-z^0-9^_^-]*)/ig,"")}},tooltip:{display:function(a,b){$.loading(!1);b==!0?$.loading(!0,{html:a,text:"",max:5E3}):$.loading(!0,{text:a,max:5E3})}},form:{INPUT_TYPE_TEXT:1,INPUT_TYPE_EMAIL:2,INPUT_TYPE_FILE:12,appendEntryTo:function(a,b,c,e,d,f,g){if(typeof a=="undefined")return!1;d="";d+="<div class='form-entry form-entry-"+$.jCore.url.genPathFromString(c)+"'><div class='form-entry-title'>"+
b+"</div><div class='form-entry-content'>";d+=e==this.INPUT_TYPE_TEXT||e==this.INPUT_TYPE_EMAIL?"<input type='text' name='"+c+"' class='text-entry' value='"+f+"' "+g+"/> ":e==this.INPUT_TYPE_FILE?"<input type='file' name='"+c+"' class='file-entry' value='"+f+"' "+g+"/> ":"This type is not supported yet! ";d+="<a href='javascript://' class='remove-link' onclick=\"$.jCore.form.removeEntry(this);\">Remove</a></div></div>";$(a).append(d);return!0},removeEntry:function(a){if(typeof a=="undefined")return!1;
$(a).closest(".form-entry").remove();return!0}},hasFlash:function(){if(navigator.plugins&&navigator.plugins.length){if(navigator.plugins["Shockwave Flash"])return!0;if(navigator.plugins["Shockwave Flash 2.0"])return!0}else if(navigator.mimeTypes&&navigator.mimeTypes.length){var a=navigator.mimeTypes["application/x-shockwave-flash"];return a&&a.enabledPlugin}else try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),!0}catch(b){try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),
!0}catch(c){try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),!0}catch(e){}}}return!1},modules:{}};
$.fn.extend({jCore:function(){return this.each(function(){typeof $.loading!="undefined"&&$.loading({onAjax:!0,delay:1E3});typeof $(this).fcToggle!="undefined"&&$(this).find(".fc-title").fcToggle();typeof $(this).mailme!="undefined"&&$(this).find(".mailme").mailme();typeof $(this).rating!="undefined"&&$(this).find(".star-rating").rating();typeof $(this).corner!="undefined"&&($(this).find(".rounded-corners-top").corner("top 5px"),$(this).find(".rounded-corners-bottom").corner("bottom 5px"),$(this).find(".rounded-corners").corner("5px"));
typeof $(this).dropDownMenu!="undefined"&&$(this).find("#main-menu .menu").dropDownMenu();if(typeof JCORE_VERSION=="undefined"||JCORE_VERSION<"0.6")$(this).find(".list tbody tr").mouseenter(function(){$(this).addClass("hilight")}),$(this).find(".list tbody tr").mouseleave(function(){$(this).removeClass("hilight")});$(this).find(".confirm-link").click(function(){var a=$(this);return confirm((a.attr("title")||a.attr("original-title")||a.attr("value")||a.text()||"Please confirm your action")+"?!")});
typeof $(this).ajaxLink!="undefined"&&$(this).find(".ajax-link").ajaxLink();typeof $(this).ajaxDownloadLink!="undefined"&&$(this).find(".ajax-download-link").ajaxDownloadLink();typeof $(this).ajaxForm!="undefined"&&$(this).find("form.ajax-form").ajaxForm();typeof $(this).ajaxContentLink!="undefined"&&$(this).find(".ajax-content-link").ajaxContentLink();typeof $(this).ajaxLightboxLink!="undefined"&&$(this).find(".ajax-lightbox-link").ajaxLightboxLink();typeof $(this).ajaxPaging!="undefined"&&$(this).find(".paging-ajax a").ajaxPaging();
$(this).find(".checkbox-all").click(function(){var a=$(this),b=this.checked,c="form";a.attr("alt")&&(c=a.attr("alt"));a.parents(c).find("input[type=checkbox]").each(function(){this.checked=b})});typeof $(this).datepicker!="undefined"&&$(this).find(".calendar-input").each(function(){var a="";$(this).is(".timestamp")?(a=new Date,a="yy-mm-dd "+a.getHours()+":"+a.getMinutes()+":00"):a="yy-mm-dd";$(this).datepicker({showAnim:"fadeIn",dateFormat:a}).after($("<a class='clear-calendar-input'>&nbsp;</a>").click(function(){$(this).parent().find("input").val("");
return!1})).after($("<a class='show-calendar-input'>&nbsp;</a>").click(function(){$(this).parent().find("input").focus();return!1}))});typeof $(this).ColorPicker!="undefined"&&$(this).find(".color-input").each(function(){$(this).ColorPicker({onBeforeShow:function(){$(this).ColorPickerSetColor(this.value)}}).after($("<a class='clear-color-input'>&nbsp;</a>").click(function(){$(this).parent().find("input").val("");return!1})).after($("<a class='show-color-input'>&nbsp;</a>").click(function(){$(this).parent().find("input").focus();
return!1}))});typeof $(this).lightBox!="undefined"&&$(function(){var a=[];$(this).find("a[rel^=lightbox]").each(function(){if(typeof a[this.rel]=="undefined")a[this.rel]=this.rel,a.length++});if(a.length)for(var b in a)typeof a[b]=="string"&&$(this).find('a[rel="'+a[b].replace(/([^a-z0-9\-_])/g,"$1")+'"]').lightBox()});typeof $(this).lightBox!="undefined"&&$(function(){var a=[];$(this).find("a[rel^=videolightbox]").each(function(){if(typeof a[this.rel]=="undefined")a[this.rel]=this.rel,a.length++});
if(a.length)for(var b in a)typeof a[b]=="string"&&$(this).find('a[rel="'+a[b].replace(/([^a-z0-9\-_])/g,"$1")+'"]').lightBox({disableSlideShow:!0,disableDownload:!0,ajaxContent:!0,fixedNavigation:!0,txtImage:"Video"})});typeof $(this).qtip!="undefined"&&$(this).find(".qtip").qtip({style:{name:"cream",tip:!0},position:{adjust:{screen:!0}}});typeof $(this).tipsy!="undefined"&&($(this).find(".list td[title]").tipsy({delayIn:100,html:!0,gravity:"w"}),$(this).find(".tip,.list a[title],.admin-section-item [title],.button[title],.attachment [title],.star-rating [title],.comment-rating-up,.comment-rating-down").tipsy({delayIn:100,
html:!0}),$(this).find(".calendar-input[title],.timestamp[title],.color-input[title]").tipsy({trigger:"focus",gravity:"w",offset:50}),$(this).find("input[type=file][title]").tipsy({delayIn:100,trigger:"hover",gravity:"w"}),$(this).find("input[title],textarea[title],select[title]").tipsy({trigger:"focus",gravity:"w"}));typeof $(this).tabby!="undefined"&&$(this).find("textarea.code-editor").tabby();typeof $(this).keypad!="undefined"&&$(this).find('input[type="password"]').keypad({showAnim:"fadeIn",
duration:"fast",keypadOnly:!1,layout:$.keypad.qwertyLayout})})}});
