(function(d){d.fn.slides=function(a){a=d.extend({},d.fn.slides.option,a);return this.each(function(){function p(){if(a.pause){clearTimeout(b.data("pause"));clearInterval(b.data("interval"));pauseTimeout=setTimeout(function(){clearTimeout(b.data("pause"));playInterval=setInterval(function(){j("next",k)},a.play);b.data("interval",playInterval)},a.pause);b.data("pause",pauseTimeout)}else clearInterval(b.data("interval"))}function j(g,w,x){if(!q&&u){q=true;switch(g){case "next":n=l;e=l+1;e=m===e?0:e;
r=f*2;g=-f*2;l=e;break;case "prev":n=l;e=l-1;e=e===-1?m-1:e;g=r=0;l=e;break;case "pagination":e=parseInt(x,10);n=d("."+a.paginationClass+" li.current a",b).attr("rel");if(e>n){r=f*2;g=-f*2}else g=r=0;l=e}if(w==="fade")a.crossfade?c.children(":eq("+e+")",b).css({zIndex:10}).fadeIn(a.fadeSpeed,function(){c.children(":eq("+n+")",b).css({display:"none",zIndex:0});d(this).css({zIndex:0});q=false}):c.children(":eq("+n+")",b).fadeOut(a.fadeSpeed,function(){a.autoHeight?c.animate({height:c.children(":eq("+
e+")",b).outerHeight()},a.autoHeightSpeed,function(){c.children(":eq("+e+")",b).fadeIn(b.data("slides").fadeSpeed)}):c.children(":eq("+e+")",b).fadeIn(a.fadeSpeed,function(){d.browser.msie&&d(this).get(0).style.removeAttribute("filter")});q=false});else{c.children(":eq("+e+")").css({left:r,display:"block"});a.autoHeight?c.animate({left:g,height:c.children(":eq("+e+")").outerHeight()},a.slideSpeed,function(){c.css({left:-f});c.children(":eq("+e+")").css({left:f,zIndex:5});c.children(":eq("+n+")").css({left:f,
display:"none",zIndex:0});q=false}):c.animate({left:g},a.slideSpeed,function(){c.css({left:-f});c.children(":eq("+e+")").css({left:f,zIndex:5});c.children(":eq("+n+")").css({left:f,display:"none",zIndex:0});q=false})}if(a.pagination){d("."+a.paginationClass+" li.current",b).removeClass("current");d("."+a.paginationClass+" li a:eq("+e+")",b).parent().addClass("current")}}}d("."+a.container,d(this)).children().wrapAll('<div class="slides_control"/>');var b=d(this),c=d(".slides_control",b),m=c.children().size(),
f=c.children().outerWidth(),s=c.children().outerHeight(),h=a.start-1,k=a.effect.indexOf(",")<0?a.effect:a.effect.replace(" ","").split(",")[0],y=a.effect.indexOf(",")<0?k:a.effect.replace(" ","").split(",")[1],e=0,n=0,t=0,l=0,u,q,v,r;if(!(m<2)){if(a.start)l=h;a.randomize&&c.randomize();d("."+a.container,b).css({overflow:"hidden",position:"relative"});c.css({position:"relative",width:f*3,height:s,left:-f});c.children().css({position:"absolute",top:0,left:f,zIndex:0,display:"none"});a.autoHeight&&c.animate({height:c.children(":eq("+
h+")").outerHeight()},o.autoHeightSpeed);if(a.preload&&c.children()[0].tagName=="IMG"){b.css({background:"url("+a.preloadImage+") no-repeat 50% 50%"});s=d("img:eq("+h+")",b).attr("src")+"?"+(new Date).getTime();d("img:eq("+h+")",b).attr("src",s).load(function(){d(this).fadeIn(a.fadeSpeed,function(){d(this).css({zIndex:5});b.css({background:""});u=true})})}else c.find(":eq("+h+")").fadeIn(a.fadeSpeed,function(){u=true});if(a.bigTarget){c.children().css({cursor:"pointer"});c.children().click(function(){j("next",
k);return false})}if(a.hoverPause&&a.play){c.children().bind("mouseover",function(){clearInterval(b.data("interval"))});c.children().bind("mouseleave",function(){p()})}if(a.generateNextPrev){d("."+a.container,b).after('<a href="#" class="'+a.prev+'">Prev</a>');d("."+a.prev,b).after('<a href="#" class="'+a.next+'">Next</a>')}d("."+a.next,b).click(function(g){g.preventDefault();a.play&&p();j("next",k)});d("."+a.prev,b).click(function(g){g.preventDefault();a.play&&p();j("prev",k)});if(a.generatePagination){b.append("<ul class="+
a.paginationClass+"></ul>");c.children().each(function(){d("."+a.paginationClass,b).append("<li><a rel="+t+' href="#">'+(t+1)+"</a></li>");t++})}else d("."+a.paginationClass+" li a",b).each(function(){d(this).attr("rel",t);t++});d("."+a.paginationClass+" li a:eq("+h+")",b).parent().addClass("current");d("."+a.paginationClass+" li a",b).click(function(){a.play&&p();v=d(this).attr("rel");l!=v&&j("pagination",y,v);return false});if(a.play){playInterval=setInterval(function(){j("next",k)},a.play);b.data("interval",
playInterval)}}})};d.fn.slides.option={preload:false,preloadImage:"/img/loading.gif",container:"slides_container",generateNextPrev:false,next:"next",prev:"prev",pagination:true,generatePagination:true,paginationClass:"pagination",fadeSpeed:350,slideSpeed:350,start:1,effect:"slide",crossfade:false,randomize:false,play:0,pause:0,hoverPause:false,autoHeight:false,autoHeightSpeed:350,bigTarget:false};d.fn.randomize=function(a){function p(){return Math.round(Math.random())-0.5}return d(this).each(function(){var j=
d(this),b=j.children(),c=b.length;if(c>1){b.hide();var m=[];for(i=0;i<c;i++)m[m.length]=i;m=m.sort(p);d.each(m,function(f,s){var h=b.eq(s),k=h.clone(true);k.show().appendTo(j);a!==undefined&&a(h,k);h.remove()})}})}})(jQuery);
