(function(k){function D(b,c,a){var g=p(c/1E3,6)+"s",f=a instanceof Array?"cubic-bezier("+p(a[0],6)+","+p(a[1],6)+","+p(a[2],6)+","+p(a[3],6)+")":a,d={};d["-webkit-transform"]=b;d["-moz-transform"]=b;d["-o-transform"]=b;d.transform=b;if(c){d["-webkit-transition-duration"]=g;d["-o-transition-duration"]=g}if(a){d["-webkit-transition-timing-function"]=f;d["-o-transition-timing-function"]=f}return d}function x(b,c,a){return[b.a*c+b.c*a+b.e,b.b*c+b.d*a+b.f]}function y(b){b='<div class="debuglabel" style="left:'+
b[0]+"px;top:"+b[1]+'px;"></div>';k("#debug").append(b)}function J(b,c,a){b||(b=v(new q));E=(new Date).getTime();if(u){clearInterval(u);u=null}if(a.easing)a.easingfunction=K(a.easing,a.duration);u=setInterval(function(){var g=b,f=(new Date).getTime()-E,d;d=a.easingfunction?a.easingfunction(f/a.duration):f/a.duration;if(f>a.duration){clearInterval(u);u=null;d=1}a.root.css(D(F(L(g,c,d))))},1)}function v(b){var c=G(b);b=c.a;var a=c.b,g=c.c,f=c.d,d=c.e;c=c.f;if(Math.abs(b*f-a*g)<0.01)console.log("fail!");
else{var e=Math.sqrt(b*b+a*a);b/=e;a/=e;var h=b*g+a*f;g-=b*h;f-=a*h;var i=Math.sqrt(g*g+f*f);g/=i;f/=i;h/=i;if(b*f-a*g<0){b=-b;a=-a;e=-e;i=-i}return{tx:d,ty:c,r:Math.atan2(a,b),k:Math.atan(h),sx:e,sy:i}}}function F(b){var c="translate("+p(b.tx,6)+"px,"+p(b.ty,6)+"px) ";c+="rotate("+p(b.r,6)+"rad) skewX("+p(b.k,6)+"rad) ";c+="scale("+p(b.sx,6)+","+p(b.sy,6)+")";return c}function H(b,c){var a=b[0];if(!a||!a.ownerDocument)return null;var g=new q;if(a===a.ownerDocument.body){var f=jQuery.offset.bodyOffset(a);
a=new q;a=a.translate(f.left,f.top);return g=g.multiply(a)}jQuery.offset.initialize();f=a.offsetParent;var d=a.ownerDocument,e,h=d.documentElement,i=d.body,o=c[0];e=(d=d.defaultView)?d.getComputedStyle(a,null):a.currentStyle;var j=a.offsetTop,l=a.offsetLeft;j=z().translate(l,j);j=j.multiply(z(a));for(g=j.multiply(g);(a=a.parentNode)&&a!==i&&a!==h&&a!==o;){l=j=0;if(jQuery.offset.supportsFixedPosition&&e.position==="fixed")break;e=d?d.getComputedStyle(a,null):a.currentStyle;j-=a.scrollTop;l-=a.scrollLeft;
if(a===f){j+=a.offsetTop;l+=a.offsetLeft;if(jQuery.offset.doesNotAddBorder&&!(jQuery.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(a.nodeName))){j+=parseFloat(e.borderTopWidth)||0;l+=parseFloat(e.borderLeftWidth)||0}f=a.offsetParent}if(jQuery.offset.subtractsBorderForOverflowNotVisible&&e.overflow!=="visible"){j+=parseFloat(e.borderTopWidth)||0;l+=parseFloat(e.borderLeftWidth)||0}e=e;j=z().translate(l,j);j=j.multiply(z(a));g=j.multiply(g)}l=j=0;if(e.position==="relative"||e.position===
"static"){j+=i.offsetTop;l+=i.offsetLeft}if(jQuery.offset.supportsFixedPosition&&e.position==="fixed"){j+=Math.max(h.scrollTop,i.scrollTop);l+=Math.max(h.scrollLeft,i.scrollLeft)}a=(new q).translate(l,j);return g=g.multiply(a)}function K(b,c){var a=[];if(b instanceof Array)a=b;else switch(b){case "linear":a=[0,0,1,1];break;case "ease":a=[0.25,0.1,0.25,1];break;case "ease-in":a=[0.42,0,1,1];break;case "ease-out":a=[0,0,0.58,1];break;case "ease-in-out":a=[0.42,0,0.58,1]}return function(g){return M(g,
a[0],a[1],a[2],a[3],c)}}function M(b,c,a,g,f,d){function e(s,A){var n,t,m,r;m=s;for(t=0;t<8;t++){r=((h*m+i)*m+o)*m-s;if((r>=0?r:0-r)<A)return m;n=(3*h*m+2*i)*m+o;if((n>=0?n:0-n)<1.0E-6)break;m-=r/n}n=0;t=1;m=s;if(m<n)return n;if(m>t)return t;for(;n<t;){r=((h*m+i)*m+o)*m;if((r-s>=0?r-s:0-(r-s))<A)break;if(s>r)n=m;else t=m;m=(t-n)*0.5+n}return m}var h=0,i=0,o=0,j=0,l=0,B=0;o=3*c;i=3*(g-c)-o;h=1-o-i;B=3*a;l=3*(f-a)-B;j=1-B-l;return function(s,A){var n=e(s,A);return((j*n+l)*n+B)*n}(b,1/(200*d))}function G(b){var c;
if(b instanceof PureCSSMatrix)c=b.m.elements;else if(b instanceof Matrix)c=b.elements;if(!c)return{a:b.a,b:b.b,c:b.c,d:b.d,e:b.e,f:b.f};return{a:c[0][0],b:c[1][0],c:c[0][1],d:c[1][1],e:c[0][2],f:c[1][2]}}function z(b){return(b=I(b))?new q(b):new q}function L(b,c,a){var g={},f;for(f in b)if(b.hasOwnProperty(f))g[f]=b[f]+(c[f]-b[f])*a;return g}function p(b,c){c=Math.abs(parseInt(c,10))||0;var a=Math.pow(10,c);return Math.round(b*a)/a}function I(b){return k(b).css("-webkit-transform")||k(b).css("-moz-transform")||
k(b).css("-o-transform")||k(b).css("transform")}var E,u,C=/([0-9.\-e]+)/g,N=/([a-z]+)\(([^\)]+)\)/g,O=/deg$/,q,w;k.zoomMooz={};k.zoomMooz.setup=function(b){w=jQuery.extend({targetsize:0.9,scalemode:"both",duration:1E3,easing:"ease",root:k(document.body),nativeanimation:false},b);q=PureCSSMatrix};k.fn.debug=function(b){w||k.zoomMooz.setup();b=jQuery.extend(w,b);k("#debug").length===0?k(b.root).append('<div id="debug"><div>'):k("#debug").html("");this.each(function(){if(k(this)[0]!=b.root[0]){var c=
k(this),a=H(c,b.root);a=G(a);y(x(a,0,0));y(x(a,0,c.outerHeight()));y(x(a,c.outerWidth(),c.outerHeight()));y(x(a,c.outerWidth(),0))}})};k.fn.zoomTo=function(b){w||k.zoomMooz.setup();b=jQuery.extend(w,b);this.each(function(){var c=k(this),a=b,g=I(a.root),f;f=g?new q(g):new q;f=v(f);for(var d=0,e;(e=N.exec(g))!==null;){var h=e[1].toLowerCase();e=e[2].split(",");if(h=="matrix"){h=$M([[parseFloat(e[0]),parseFloat(e[2]),parseFloat(e[4].match(C))],[parseFloat(e[1]),parseFloat(e[3]),parseFloat(e[5].match(C))],
[0,0,1]]);d+=v(h).r}else if(h=="rotate"){h=e[0];e=parseFloat(h.match(C));if(h.match(O))e=2*Math.PI*e/360;d+=e}}f.r=d;if(c[0]===a.root[0])c=v(new q);else{g=H(c,a.root);a:{g=g?g.inverse():null;var i=a.targetsize,o=a.scalemode;d=a.root;e=k(d).width();h=k(d).height();var j=e/c.outerWidth(),l=h/c.outerHeight();if(o=="width")i=i*j;else if(o=="height")i=i*l;else if(o=="both")i=i*Math.min(j,l);else{console.log("wrong zoommode");c=void 0;break a}o=(e-c.outerWidth()*i)/2;c=(h-c.outerHeight()*i)/2;e=e/2;h=h/
2;j=Number(e).toFixed(6)+"px "+Number(h).toFixed(6)+"px";d.css("-webkit-transform-origin",j);d.css("-o-transform-origin",j);d.css("-moz-transform-origin",j);d=new q;d=d.translate(-e,-h);d=d.translate(o,c);d=d.scale(i,i);if(g)d=d.multiply(g);c=d=d.translate(e,h)}c=v(c)}c=c;if(Math.abs(f.r-c.r)>Math.PI)if(c.r<f.r)for(;Math.abs(f.r-c.r)>Math.PI;)c.r+=2*Math.PI;else for(;Math.abs(f.r-c.r)>Math.PI;)c.r-=2*Math.PI;c=c;k.browser.mozilla||k.browser.opera||!a.nativeanimation?J(f,c,a):a.root.css(D(F(c),a.duration,
a.easing))});return this}})(jQuery);
