(function(a){a.fn.bMap=function(b){eachOptions=b;return this.each(function(){obj=a(this);var c={mapCenter:[51,0],mapZoom:1,mapCanvas:obj.attr("id"),mapSidebar:"none",mapLayerbar:"none",mapType:google.maps.MapTypeId.ROADMAP,loadMsg:"<h2>Loading...</h2>"};c=a.extend(c,eachOptions);obj.data("bMap",new bMap(c))})}})(jQuery);
function bMap(a){a=$.extend({mapCenter:[51,0],mapZoom:1,mapCanvas:"map",mapSidebar:"none",mapLayerbar:"none",mapType:google.maps.MapTypeId.ROADMAP,loadMsg:"<h2>Loading...</h2>"},a);this.mapSidebar=a.mapSidebar;this.useSidebar=this.mapSidebar!="none"?true:false;this.mapLayerbar=a.mapLayerbar;this.useLayerbar=this.mapLayerbar!="none"?true:false;this.LyrArr=[];var b={zoom:a.mapZoom,center:new google.maps.LatLng(a.mapCenter[0],a.mapCenter[1]),mapTypeId:a.mapType};this.map=new google.maps.Map(document.getElementById(a.mapCanvas),
b);this.mapCanvas=a.mapCanvas;$("#"+this.mapCanvas).append("<div id='"+this.mapCanvas+"bMapLoadMsg' class='bMapLoadMsg'>"+a.loadMsg+"</div>");$("#"+this.mapCanvas+"bMapLoadMsg").css("left",$("#map").width()/2-50);$("#"+this.mapCanvas+"bMapLoadMsg").css("top",$("#map").height()/2-50);if(a.icons)this.icons=a.icons;a.markers&&this.insertMarkers(a.markers);this.infoWindow=new google.maps.InfoWindow;this.geoCoder=new google.maps.Geocoder}
bMap.prototype.insertMarkers=function(a){tmpThis=this;var b=tmpThis.LyrArr.length;a=$.extend({name:"Layer"+b,type:"marker",visible:"true"},a);tmpThis.LyrArr[b]=a;tmpThis.LyrArr[b].toggleLayer=function(){if(this.visible!="false"){this.visible="false";i=0;for(j=this.data.length;i<j;i++){this.data[i].setMap(null);tmpThis.infoWindow.close()}$("#bMapLyr"+b).addClass("bLyrHide");$("#"+tmpThis.mapSidebar+' div[rel^="'+b+'"]').slideUp("fast");return false}else{this.visible="true";i=0;for(j=this.data.length;i<
j;i++)this.data[i].setMap(tmpThis.map);$("#bMapLyr"+b).removeClass("bLyrHide");$("#"+tmpThis.mapSidebar+' div[rel^="'+b+'"]').slideDown("fast");return true}};jQuery.each(a.data,function(c,d){var e=new google.maps.LatLng(d.lat,d.lng);tmpThis.LyrArr[b].data[c]=d.icon?new google.maps.Marker({position:e,map:tmpThis.map,icon:d.icon}):new google.maps.Marker({position:e,map:tmpThis.map});if(d.title){var f="<h2>"+d.title+"</h2>";if(d.body)f+=d.body;google.maps.event.addListener(tmpThis.LyrArr[b].data[c],
"click",function(){tmpThis.infoWindow.setContent(f);tmpThis.infoWindow.open(tmpThis.map,tmpThis.LyrArr[b].data[c]);$("#"+tmpThis.mapSidebar+" div").removeClass("bSideSelect");$("#"+tmpThis.mapSidebar+' div[rel="'+b+" "+c+'"]').addClass("bSideSelect");var g=$("#"+tmpThis.mapSidebar).scrollTop()+$("#"+tmpThis.mapSidebar+' div[rel="'+b+" "+c+'"]').position().top-($("#"+tmpThis.mapSidebar).offset().top+$("#"+tmpThis.mapSidebar).height()/2);$("#"+tmpThis.mapSidebar).animate({scrollTop:g},500)});google.maps.event.addListener(tmpThis.LyrArr[b].data[c],
"infowindowclose",function(){$("#"+tmpThis.mapSidebar+' div[rel="'+b+" "+c+'"]').removeClass("bSideSelect")})}tmpThis.useSidebar&&$('<div rel="'+b+" "+c+'">'+d.title+"</div>").click(function(){google.maps.event.trigger(tmpThis.LyrArr[b].data[c],"click");$("#"+tmpThis.mapSidebar+" div").removeClass("bSideSelect");$(this).addClass("bSideSelect")}).appendTo("#"+tmpThis.mapSidebar)});if(a.visible!="true"){i=0;for(j=tmpThis.LyrArr[b].data.length;i<j;i++){tmpThis.LyrArr[b].data[i].setMap(null);$("#"+tmpThis.mapSidebar+
' div[rel^="'+b+'"]').hide()}$("#bMapLyr"+b).addClass("bLyrHide");return false}this.refreshLayerbar();return this};bMap.prototype.AJAXMarkers=function(a){a=$.extend({serviceURL:"mapService.php",action:"getMarkers",vars:[],options:{}},a);var b=this;$("#"+this.mapCanvas+"bMapLoadMsg").show();$.getJSON(a.serviceURL,{action:a.action,vars:a.vars},function(c){a.options=$.extend(c,a.options);b.insertMarkers(a.options);$("#"+b.mapCanvas+"bMapLoadMsg").hide()});return this};
bMap.prototype.insertLine=function(a){tmpThis=this;var b=tmpThis.LyrArr.length;a=$.extend({name:"Layer"+b,type:"line",visible:"true",color:"#00F",weight:5,opacity:1},a);tmpThis.LyrArr[b]=a;tmpThis.LyrArr[b].toggleLayer=function(){if(this.visible!="false"){this.visible="false";this.data.setMap(null);$("#bMapLyr"+b).addClass("bLyrHide");return false}else{this.visible="true";this.data.setMap(tmpThis.map);$("#bMapLyr"+b).removeClass("bLyrHide");return true}};var c=[];jQuery.each(a.data,function(d,e){c.push(new google.maps.LatLng(e.lat,
e.lng))});tmpThis.LyrArr[b].data=new google.maps.Polyline({path:c,strokeColor:tmpThis.LyrArr[b].color,strokeOpacity:parseFloat(tmpThis.LyrArr[b].opacity),strokeWeight:parseInt(tmpThis.LyrArr[b].weight)});tmpThis.LyrArr[b].data.setMap(tmpThis.map);a.visible!="true"&&tmpThis.LyrArr[b].data.setMap(null);this.refreshLayerbar();return this};
bMap.prototype.AJAXLine=function(a){a=$.extend({serviceURL:"mapService.php",action:"getLine",vars:[]},a);var b=this;$("#"+this.mapCanvas+"bMapLoadMsg").show();$.post(a.serviceURL,{action:a.action,vars:a.vars},function(c){b.insertLine(c);$("#"+b.mapCanvas+"bMapLoadMsg").hide()},"json");return this};
bMap.prototype.insertPolygon=function(a){tmpThis=this;var b=tmpThis.LyrArr.length;a=$.extend({name:"Layer"+b,type:"polygon",visible:"true",color:"#00F",weight:5,opacity:0.5},a);tmpThis.LyrArr[b]=a;tmpThis.LyrArr[b].toggleLayer=function(){if(this.visible!="false"){this.visible="false";this.data.setMap(null);$("#bMapLyr"+b).addClass("bLyrHide");return false}else{this.visible="true";this.data.setMap(tmpThis.map);$("#bMapLyr"+b).removeClass("bLyrHide");return true}};var c=[];jQuery.each(a.data,function(d,
e){c.push(new google.maps.LatLng(e.lat,e.lng))});tmpThis.LyrArr[b].data=new google.maps.Polygon({path:c,strokeColor:tmpThis.LyrArr[b].color,strokeOpacity:1,strokeWeight:parseInt(tmpThis.LyrArr[b].weight),fillColor:tmpThis.LyrArr[b].color,fillOpacity:parseFloat(tmpThis.LyrArr[b].opacity)});tmpThis.LyrArr[b].data.setMap(tmpThis.map);a.visible!="true"&&tmpThis.LyrArr[b].data.setMap(null);this.refreshLayerbar();return this};
bMap.prototype.AJAXPolygon=function(a){a=$.extend({serviceURL:"mapService.php",action:"getPolygon",vars:[]},a);var b=this;$("#"+this.mapCanvas+"bMapLoadMsg").show();$.post(a.serviceURL,{action:a.action,vars:a.vars},function(c){b.insertPolygon(c);$("#"+b.mapCanvas+"bMapLoadMsg").hide()},"json");return this};
bMap.prototype.removeAllLayers=function(){i=0;for(j=this.LyrArr.length;i<j;i++){if(this.LyrArr[i].type=="marker"){i2=0;for(j2=this.LyrArr[i].data.length;i2<j2;i2++)this.LyrArr[i].data[i2].setMap(null);this.infoWindow.close()}else this.LyrArr[i].data.setMap(null);this.LyrArr[i].data=0;this.useSidebar&&$("#"+this.mapSidebar+' div[rel^="'+i+'"]').remove()}this.LyrArr.length=0;this.refreshLayerbar();return this};
bMap.prototype.removeLayer=function(a){if(this.LyrArr[a].type=="marker"){i2=0;for(j2=this.LyrArr[a].data.length;i2<j2;i2++)this.LyrArr[a].data[i2].setMap(null)}else this.LyrArr[a].data.setMap(null);this.LyrArr[a].data=0;this.useSidebar&&$("#"+this.mapSidebar+' div[rel^="'+a+'"]').remove();this.refreshLayerbar();return this};
bMap.prototype.popLayer=function(){var a=this.LyrArr.length-1,b=this.LyrArr.pop();if(b.type=="marker"){i2=0;for(j2=b.data.length;i2<j2;i2++)b.data[i2].setMap(null)}else b.data.setMap(null);b.data=0;this.useSidebar&&$("#"+this.mapSidebar+' div[rel^="'+a+'"]').remove();this.refreshLayerbar();return this};
bMap.prototype.shiftLayer=function(){i3=0;for(j3=this.LyrArr.length;i3<j3;i3++)if(this.LyrArr[i3].data!=0){var a=i3;break}if(this.LyrArr[a].type=="marker"){i2=0;for(j2=this.LyrArr[a].data.length;i2<j2;i2++)this.LyrArr[a].data[i2].setMap(null)}else this.LyrArr[a].data.setMap(null);this.LyrArr[a].data=0;this.LyrArr[a].name="";this.LyrArr[a].type="";this.useSidebar&&$("#"+this.mapSidebar+' ^"'+a+'"]').remove();this.refreshLayerbar();return this};
bMap.prototype.refreshLayerbar=function(){if(this.mapLayerbar){var a=this;$("#"+this.mapLayerbar).html("");for(var b=0,c=this.LyrArr.length;b<c;b++)if(this.LyrArr[b].data!=0)$("<div "+(this.LyrArr[b].visible!="false"?"":"class='bLyrHide' ")+"id='bMapLyr"+b+"' rel='"+b+"'>"+this.LyrArr[b].name+"</div>").click(function(){a.LyrArr[$(this).attr("rel")].toggleLayer()}).appendTo("#"+this.mapLayerbar)}};
bMap.prototype.centerAtAddress=function(a){var b=this;this.geoCoder.geocode({address:a},function(c,d){d==google.maps.GeocoderStatus.OK&&b.map.setCenter(c[0].geometry.location)});return this};
