(function(c,A,H){function S(){console&&(console.info||console.log||c.noop).apply(this,arguments)}function O(b){var a;if(!b||"object"!==typeof b)return n;if("object"!==typeof b.metadata)b.metadata={type:b.metadata};if("content"in b){if("object"!==typeof b.content||b.content.jquery)b.content={text:b.content};a=b.content.text||n;if(!c.isFunction(a)&&(!a&&!a.attr||a.length<1||"object"===typeof a&&!a.jquery))b.content.text=n;if("title"in b.content){if("object"!==typeof b.content.title)b.content.title=
{text:b.content.title};a=b.content.title.text||n;if(!c.isFunction(a)&&(!a&&!a.attr||a.length<1||"object"===typeof a&&!a.jquery))b.content.title.text=n}}if("position"in b&&"object"!==typeof b.position)b.position={my:b.position,at:b.position};if("show"in b&&"object"!==typeof b.show)b.show=b.show.jquery?{target:b.show}:{event:b.show};if("hide"in b&&"object"!==typeof b.hide)b.hide=b.hide.jquery?{target:b.hide}:{event:b.hide};if("style"in b&&"object"!==typeof b.style)b.style={classes:b.style};c.each(v,
function(){this.sanitize&&this.sanitize(b)});return b}function U(b,a,d,j){function h(e){for(var b=0,c,g=a,e=e.split(".");g=g[e[b++]];)b<e.length&&(c=g);return[c||a,e.pop()]}function k(){var e=a.style.widget;g.toggleClass(Q,e).toggleClass(T,!e);s.content.toggleClass(Q+"-content",e);s.titlebar&&s.titlebar.toggleClass(Q+"-header",e);s.button&&s.button.toggleClass(B+"-icon",!e)}function i(){if(s.title)s.titlebar.remove(),s.titlebar=s.title=s.button=y,e.reposition()}function l(){var b=a.content.title.button,
f=typeof b==="string"?b:"Close tooltip";s.button&&s.button.remove();s.button=b.jquery?b:c("<a />",{"class":"ui-state-default "+(a.style.widget?"":B+"-icon"),title:f,"aria-label":f}).prepend(c("<span />",{"class":"ui-icon ui-icon-close",html:"&times;"}));s.button.appendTo(s.titlebar).attr("role","button").hover(function(e){c(this).toggleClass("ui-state-hover",e.type==="mouseenter")}).click(function(a){g.hasClass(G)||e.hide(a);return n}).bind("mousedown keydown mouseup keyup mouseout",function(e){c(this).toggleClass("ui-state-active ui-state-focus",
e.type.substr(-4)==="down")});e.redraw()}function f(){var b=D+"-title";s.titlebar&&i();s.titlebar=c("<div />",{"class":B+"-titlebar "+(a.style.widget?"ui-widget-header":"")}).append(s.title=c("<div />",{id:b,"class":B+"-title","aria-atomic":q})).insertBefore(s.content);a.content.title.button?l():e.rendered&&e.redraw()}function u(a,f){var d=s.title;if(!e.rendered||!a)return n;c.isFunction(a)&&(a=a.call(b,x.event,e)||"");a.jquery&&a.length>0?d.empty().append(a.css({display:"block"})):d.html(a);e.redraw();
f!==n&&e.rendered&&g.is(":visible")&&e.reposition(x.event)}function p(a,f){function d(a){function b(){clearTimeout(e.timers.img[this]);c(this).unbind(m);if((t=t.not(this)).length===0)e.redraw(),f!==n&&e.reposition(x.event),a()}var t;if((t=h.find("img:not([height]):not([width])")).length===0)return b.call(t);t.each(function(a,t){(function V(){if(t.height&&t.width)return b.call(t);e.timers.img[t]=setTimeout(V,1E3)})();c(t).bind("error"+m+" load"+m,b)})}var h=s.content;if(!e.rendered||!a)return n;c.isFunction(a)&&
(a=a.call(b,x.event,e)||"");a.jquery&&a.length>0?h.empty().append(a.css({display:"block"})):h.html(a);e.rendered<0?g.queue("fx",d):(w=0,d(c.noop));return e}function o(){function t(b){if(g.hasClass(G))return n;i.show.trigger("qtip-"+d+"-inactive");clearTimeout(e.timers.show);clearTimeout(e.timers.hide);var c=function(){e.toggle(q,b)};a.show.delay>0?e.timers.show=setTimeout(c,a.show.delay):c()}function f(b){if(g.hasClass(G))return n;var t=c(b.relatedTarget||b.target),d=t.closest(I)[0]===g[0],t=t[0]===
i.show[0];clearTimeout(e.timers.show);clearTimeout(e.timers.hide);j.target==="mouse"&&d||a.hide.fixed&&/mouse(out|leave|move)/.test(b.type)&&(d||t)?b.preventDefault():a.hide.delay>0?e.timers.hide=setTimeout(function(){e.hide(b)},a.hide.delay):e.hide(b)}function h(b){if(g.hasClass(G))return n;clearTimeout(e.timers.inactive);e.timers.inactive=setTimeout(function(){e.hide(b)},a.hide.inactive)}function k(a){g.is(":visible")&&e.reposition(a)}var j=a.position,i={show:a.show.target,hide:a.hide.target,viewport:c(j.viewport),
document:c(document),window:c(A)},E={show:c.trim(""+a.show.event).split(" "),hide:c.trim(""+a.hide.event).split(" ")},l=c.browser.msie&&parseInt(c.browser.version,10)===6;g.bind("mouseenter"+m+" mouseleave"+m,function(a){var b=a.type==="mouseenter";b&&e.focus(a);g.toggleClass(W,b)});if(a.hide.fixed)i.hide=i.hide.add(g),g.bind("mouseover"+m,function(){g.hasClass(G)||clearTimeout(e.timers.hide)});/mouse(out|leave)/i.test(a.hide.event)?a.hide.leave&&i.window.bind("mouse"+(a.hide.leave.indexOf("frame")>
-1?"out":"leave")+m,function(a){/select|option/.test(a.target)&&!a.relatedTarget&&e.hide(a)}):/mouse(over|enter)/i.test(a.show.event)&&i.hide.bind("mouseleave"+m,function(){clearTimeout(e.timers.show)});(""+a.hide.event).indexOf("unfocus")>-1&&i.document.bind("mousedown"+m,function(a){var t=c(a.target);!g.hasClass(G)&&g.is(":visible");t.parents(I).length===0&&t.add(b).length>1&&e.hide(a)});"number"===typeof a.hide.inactive&&(i.show.bind("qtip-"+d+"-inactive",h),c.each(z.inactiveEvents,function(a,
e){i.hide.add(s.tooltip).bind(e+m+"-inactive",h)}));c.each(E.hide,function(a,e){var b=c.inArray(e,E.show),d=c(i.hide);b>-1&&d.add(i.show).length===d.length||e==="unfocus"?(i.show.bind(e+m,function(a){g.is(":visible")?f(a):t(a)}),delete E.show[b]):i.hide.bind(e+m,f)});c.each(E.show,function(a,e){i.show.bind(e+m,t)});"number"===typeof a.hide.distance&&i.show.bind("mousemove"+m,function(b){var c=x.origin||{},t=a.hide.distance,g=Math.abs;(g(b.pageX-c.pageX)>=t||g(b.pageY-c.pageY)>=t)&&e.hide(b)});j.target===
"mouse"&&(i.show.bind("mousemove"+m,function(a){J={pageX:a.pageX,pageY:a.pageY,type:"mousemove"}}),j.adjust.mouse&&(a.hide.event&&g.bind("mouseleave"+m,function(a){(a.relatedTarget||a.target)!==i.show[0]&&e.hide(a)}),i.document.bind("mousemove"+m,function(a){!g.hasClass(G)&&g.is(":visible")&&e.reposition(a||J)})));if(j.adjust.resize||i.viewport.length)(c.event.special.resize?i.viewport:i.window).bind("resize"+m,k);(i.viewport.length||l&&g.css("position")==="fixed")&&i.viewport.bind("scroll"+m,k)}
function C(){var b=[a.show.target[0],a.hide.target[0],e.rendered&&s.tooltip[0],a.position.container[0],a.position.viewport[0],A,document];e.rendered?c([]).pushStack(c.grep(b,function(a){return typeof a==="object"})).unbind(m):a.show.target.unbind(m+"-create")}var e=this,E=document.body,D=B+"-"+d,N=0,w=0,g=c(),m=".qtip-"+d,s,x;e.id=d;e.rendered=n;e.elements=s={target:b};e.timers={img:{}};e.options=a;e.checks={};e.plugins={};e.cache=x={event:{},target:c(),disabled:n,attr:j};e.checks.builtin={"^id$":function(a,
e,b){a=b===q?z.nextid:b;e=B+"-"+a;if(a!==n&&a.length>0&&!c("#"+e).length)g[0].id=e,s.content[0].id=e+"-content",s.title[0].id=e+"-title"},"^content.text$":function(a,e,b){p(b)},"^content.title.text$":function(a,e,b){if(!b)return i();!s.title&&b&&f();u(b)},"^content.title.button$":function(a,b,c){a=s.button;b=s.title;e.rendered&&(c?(b||f(),l()):a.remove())},"^position.(my|at)$":function(a,e,b){"string"===typeof b&&(a[e]=new v.Corner(b))},"^position.container$":function(a,b,c){e.rendered&&g.appendTo(c)},
"^show.ready$":function(){e.rendered?e.toggle(q):e.render(1)},"^style.classes$":function(a,e,b){c.attr(g[0],"class",B+" qtip ui-helper-reset "+b)},"^style.widget|content.title":k,"^events.(render|show|move|hide|focus|blur)$":function(a,e,b){g[(c.isFunction(b)?"":"un")+"bind"]("tooltip"+e,b)},"^(show|hide|position).(event|target|fixed|inactive|leave|distance|viewport|adjust)":function(){var e=a.position;g.attr("tracking",e.target==="mouse"&&e.adjust.mouse);C();o()}};c.extend(e,{render:function(t){if(e.rendered)return e;
var d=a.content.title.text,i=a.position,h=c.Event("tooltiprender");c.attr(b[0],"aria-describedby",D);g=s.tooltip=c("<div/>",{id:D,"class":B+" qtip ui-helper-reset "+T+" "+a.style.classes,width:a.style.width||"",tracking:i.target==="mouse"&&i.adjust.mouse,role:"alert","aria-live":"polite","aria-atomic":n,"aria-describedby":D+"-content","aria-hidden":q}).toggleClass(G,x.disabled).data("qtip",e).appendTo(a.position.container).append(s.content=c("<div />",{"class":B+"-content",id:D+"-content","aria-atomic":q}));
e.rendered=-1;w=1;d&&(f(),u(d));p(a.content.text,n);e.rendered=q;k();c.each(a.events,function(a,e){c.isFunction(e)&&g.bind(a==="toggle"?"tooltipshow tooltiphide":"tooltip"+a,e)});c.each(v,function(){this.initialize==="render"&&this(e)});o();g.queue("fx",function(b){h.originalEvent=x.event;g.trigger(h,[e]);w=0;e.redraw();(a.show.ready||t)&&e.toggle(q,x.event);b()});return e},get:function(e){switch(e.toLowerCase()){case "dimensions":e={height:g.outerHeight(),width:g.outerWidth()};break;case "offset":e=
v.offset(g,a.position.container);break;default:e=h(e.toLowerCase()),e=e[0][e[1]],e=e.precedance?e.string():e}return e},set:function(b,f){var d=/^position\.(my|at|adjust|target|container)|style|content|show\.ready/i,i=/^content\.(title|attr)|style/i,k=n,m=n,j=e.checks,E;"string"===typeof b?(E=b,b={},b[E]=f):b=c.extend(q,{},b);c.each(b,function(a,e){var g=h(a.toLowerCase()),f;f=g[0][g[1]];g[0][g[1]]="object"===typeof e&&e.nodeType?c(e):e;b[a]=[g[0],g[1],e,f];k=d.test(a)||k;m=i.test(a)||m});O(a);N=w=
1;c.each(b,function(a,b){var c,g,f;for(c in j)for(g in j[c])if(f=RegExp(g,"i").exec(a))b.push(f),j[c][g].apply(e,b)});N=w=0;g.is(":visible")&&e.rendered&&(k&&e.reposition(a.position.target==="mouse"?y:x.event),m&&e.redraw());return e},toggle:function(b,f){function i(){b?(c.browser.msie&&g[0].style.removeAttribute("filter"),g.css("overflow","")):g.css({display:"",visibility:"",opacity:"",left:"",top:""})}if(!e.rendered)if(b)e.render(1);else return e;var h=b?"show":"hide",k=a[h],m=g.is(":visible"),
j=!f||x.target[0]===f.target,E=a.position,l=a.content;(typeof b).search("boolean|number")&&(b=!m);if(!g.is(":animated")&&m===b&&j)return e;if(f){if(/over|enter/.test(f.type)&&/out|leave/.test(x.event.type)&&f.target===a.show.target[0]&&g.has(f.relatedTarget).length)return e;x.event=c.extend({},f)}m=c.Event("tooltip"+h);m.originalEvent=f?x.event:y;g.trigger(m,[e,90]);if(m.isDefaultPrevented())return e;c.attr(g[0],"aria-hidden",!b);b?(x.origin=c.extend({},J),e.focus(f),c.isFunction(l.text)&&p(l.text,
n),c.isFunction(l.title.text)&&u(l.title.text,n),!P&&E.target==="mouse"&&E.adjust.mouse&&(c(document).bind("mousemove.qtip",function(a){J={pageX:a.pageX,pageY:a.pageY,type:"mousemove"}}),P=q),e.reposition(f),k.solo&&c(I,k.solo).not(g).qtip("hide",m)):(clearTimeout(e.timers.show),delete x.origin,P&&!c(I+'[tracking="true"]:visible',k.solo).not(g).length&&(c(document).unbind("mousemove.qtip"),P=n),e.blur(f));j&&g.stop(0,1);k.effect===n?(g[h](),i.call(g)):c.isFunction(k.effect)?(k.effect.call(g,e),g.queue("fx",
function(a){i();a()})):g.fadeTo(90,b?1:0,i);b&&k.target.trigger("qtip-"+d+"-inactive");return e},show:function(a){return e.toggle(q,a)},hide:function(a){return e.toggle(n,a)},focus:function(a){if(!e.rendered)return e;var b=c(I),f=parseInt(g[0].style.zIndex,10),d=z.zindex+b.length,a=c.extend({},a),i;if(!g.hasClass(M)&&(i=c.Event("tooltipfocus"),i.originalEvent=a,g.trigger(i,[e,d]),!i.isDefaultPrevented()))f!==d&&(b.each(function(){this.style.zIndex>f&&(this.style.zIndex-=1)}),b.filter("."+M).qtip("blur",
a)),g.addClass(M)[0].style.zIndex=d;return e},blur:function(a){var a=c.extend({},a),b;g.removeClass(M);b=c.Event("tooltipblur");b.originalEvent=a;g.trigger(b,[e]);return e},reposition:function(b,f){if(!e.rendered||N)return e;N=1;var d=a.position.target,i=a.position,h=i.my,k=i.at,m=i.adjust,j=m.method.split(" "),l=g.outerWidth(),u=g.outerHeight(),D=0,s=0,q=c.Event("tooltipmove"),p=g.css("position")==="fixed",o=i.viewport,r={left:0,top:0},w=e.plugins.tip,C={horizontal:j[0],vertical:j[1]||j[0],left:function(a){var b=
C.horizontal==="shift",e=o.offset.left+o.scrollLeft,c=h.x==="left"?l:h.x==="right"?-l:-l/2,d=k.x==="left"?D:k.x==="right"?-D:-D/2,g=w&&w.size?w.size.width||0:0,f=w&&w.corner&&w.corner.precedance==="x"&&!b?g:0,i=e-a+f,j=a+l-o.width-e+f,d=c-(h.precedance==="x"||h.x===h.y?d:0),f=h.x==="center";if(b)f=w&&w.corner.precedance==="y"?g:0,d=(h.x==="left"?1:-1)*c-f,r.left+=i>0?i:j>0?-j:0,r.left=Math.max(o.offset.left+(f&&w.corner.x==="center"?w.offset:0),a-d,Math.min(Math.max(o.offset.left+o.width,a+d),r.left));
else{if(i>0&&(h.x!=="left"||j>0))r.left-=d+(f?0:2*m.x);else if(j>0&&(h.x!=="right"||i>0))r.left-=f?-d:d+2*m.x;r.left!==a&&f&&(r.left-=m.x);if(r.left<e&&-r.left>j)r.left=a}return r.left-a},top:function(a){var b=C.vertical==="shift",e=o.offset.top+o.scrollTop,c=h.y==="top"?u:h.y==="bottom"?-u:-u/2,d=k.y==="top"?s:k.y==="bottom"?-s:-s/2,f=w&&w.size?w.size.height||0:0,g=w&&w.corner&&w.corner.precedance==="y"&&!b?f:0,i=e-a+g,e=a+u-o.height-e+g,d=c-(h.precedance==="y"||h.x===h.y?d:0),g=h.y==="center";if(b)g=
w&&w.corner.precedance==="x"?f:0,d=(h.y==="top"?1:-1)*c-g,r.top+=i>0?i:e>0?-e:0,r.top=Math.max(o.offset.top+(g&&w.corner.x==="center"?w.offset:0),a-d,Math.min(Math.max(o.offset.top+o.height,a+d),r.top));else{if(i>0&&(h.y!=="top"||e>0))r.top-=d+(g?0:2*m.y);else if(e>0&&(h.y!=="bottom"||i>0))r.top-=g?-d:d+2*m.y;r.top!==a&&g&&(r.top-=m.y);if(r.top<0&&-r.top>e)r.top=a}return r.top-a}};if(c.isArray(d)&&d.length===2)k={x:"left",y:"top"},r={left:d[0],top:d[1]};else if(d==="mouse"&&(b&&b.pageX||x.event.pageX))k=
{x:"left",y:"top"},b=b&&(b.type==="resize"||b.type==="scroll")?x.event:b&&b.pageX&&b.type==="mousemove"?b:J&&(m.mouse||!b||!b.pageX)?{pageX:J.pageX,pageY:J.pageY}:!m.mouse&&x.origin?x.origin:b,r={top:b.pageY,left:b.pageX};else{d==="event"?d=b&&b.target&&b.type!=="scroll"&&b.type!=="resize"?x.target=c(b.target):x.target:x.target=c(d);d=c(d).eq(0);if(d.length===0)return e;else d[0]===document||d[0]===A?(D=v.iOS?A.innerWidth:d.width(),s=v.iOS?A.innerHeight:d.height(),d[0]===A&&(r={top:!p||v.iOS?(o||
d).scrollTop():0,left:!p||v.iOS?(o||d).scrollLeft():0})):d.is("area")&&v.imagemap?r=v.imagemap(d,k):d[0].namespaceURI==="http://www.w3.org/2000/svg"&&v.svg?r=v.svg(d,k):(D=d.outerWidth(),s=d.outerHeight(),r=v.offset(d,i.container,p));if(r.offset)D=r.width,s=r.height,r=r.offset;r.left+=k.x==="right"?D:k.x==="center"?D/2:0;r.top+=k.y==="bottom"?s:k.y==="center"?s/2:0}r.left+=m.x+(h.x==="right"?-l:h.x==="center"?-l/2:0);r.top+=m.y+(h.y==="bottom"?-u:h.y==="center"?-u/2:0);o.jquery&&d[0]!==A&&d[0]!==
E&&C.vertical+C.horizontal!=="nonenone"?(o={elem:o,height:o[(o[0]===A?"h":"outerH")+"eight"](),width:o[(o[0]===A?"w":"outerW")+"idth"](),scrollLeft:p?0:o.scrollLeft(),scrollTop:p?0:o.scrollTop(),offset:o.offset()||{left:0,top:0}},r.adjusted={left:C.horizontal!=="none"?C.left(r.left):0,top:C.vertical!=="none"?C.top(r.top):0}):r.adjusted={left:0,top:0};g.attr("class",function(){return c.attr(this,"class").replace(/ui-tooltip-pos-\w+/i,"")}).addClass(B+"-pos-"+h.abbreviation());q.originalEvent=c.extend({},
b);g.trigger(q,[e,r,o.elem||o]);if(q.isDefaultPrevented())return e;delete r.adjusted;f===n||isNaN(r.left)||isNaN(r.top)||d==="mouse"||!c.isFunction(i.effect)?g.css(r):c.isFunction(i.effect)&&(i.effect.call(g,e,c.extend({},r)),g.queue(function(a){c(this).css({opacity:"",height:""});c.browser.msie&&this.style.removeAttribute("filter");a()}));N=0;return e},redraw:function(){if(e.rendered<1||w)return e;var b=a.position.container,c,d,f;w=1;a.style.width?g.css("width",a.style.width):(g.css("width","").addClass(K),
c=g.width()+1,d=g.css("max-width")||"",f=g.css("min-width")||"",b=(d+f).indexOf("%")>-1?b.width()/100:0,d=(d.indexOf("%")>-1?b:1)*parseInt(d,10)||c,f=(f.indexOf("%")>-1?b:1)*parseInt(f,10)||0,c=d+f?Math.min(Math.max(c,f),d):c,g.css("width",Math.round(c)).removeClass(K));w=0;return e},disable:function(a){var b=G;"boolean"!==typeof a&&(a=!(g.hasClass(b)||x.disabled));e.rendered?(g.toggleClass(b,a),c.attr(g[0],"aria-disabled",a)):x.disabled=!!a;return e},enable:function(){return e.disable(n)},destroy:function(){var a=
b[0],d=c.attr(a,L);e.rendered&&(g.remove(),c.each(e.plugins,function(){this.destroy&&this.destroy()}));clearTimeout(e.timers.show);clearTimeout(e.timers.hide);C();c.removeData(a,"qtip");d&&(c.attr(a,"title",d),b.removeAttr(L));b.removeAttr("aria-describedby").unbind(".qtip");delete R[e.id];return b}})}function X(b,a){var d,j,h,k,i=c(this),l=c(document.body),f=this===document?l:i;j=i.metadata?i.metadata(a.metadata):y;k=a.metadata.type==="html5"&&j?j[a.metadata.name]:y;var u=i.data(a.metadata.name||
"qtipopts");try{u=typeof u==="string"?(new Function("return "+u))():u}catch(p){S("Unable to parse HTML5 attribute data: "+u)}k=c.extend(q,{},z.defaults,a,typeof u==="object"?O(u):y,O(k||j));j=k.position;k.id=b;if("boolean"===typeof k.content.text)if(h=i.attr(k.content.attr),k.content.attr!==n&&h)k.content.text=h;else return S("Unable to locate content for tooltip! Aborting render of tooltip on element: ",i),n;if(j.container===n)j.container=l;if(j.target===n)j.target=f;if(k.show.target===n)k.show.target=
f;if(k.show.solo===q)k.show.solo=l;if(k.hide.target===n)k.hide.target=f;if(k.position.viewport===q)k.position.viewport=j.container;j.at=new v.Corner(j.at);j.my=new v.Corner(j.my);if(c.data(this,"qtip"))if(k.overwrite)i.qtip("destroy");else if(k.overwrite===n)return n;c.attr(this,"title")&&(c.attr(this,L,c.attr(this,"title")),this.removeAttribute("title"));d=new U(i,k,b,!!h);c.data(this,"qtip",d);i.bind("remove.qtip",function(){d.destroy()});return d}function Y(b){var a=this,d=b.elements.tooltip,j=
b.options.content.ajax,h=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi;b.checks.ajax={"^content.ajax":function(b,c,h){c==="ajax"&&(j=h);c==="once"?a.init():j&&j.url?a.load():d.unbind(".qtip-ajax")}};c.extend(a,{init:function(){if(j&&j.url)d.unbind(".qtip-ajax")[j.once?"one":"bind"]("tooltipshow.qtip-ajax",a.load);return a},load:function(k,i){function l(){o&&(d.css("visibility",""),i=n)}if(k&&k.isDefaultPrevented())return a;var f=j.url.indexOf(" "),u=j.url,p,o=j.once&&!j.loading&&i;o&&d.css("visibility",
"hidden");f>-1&&(p=u.substr(f),u=u.substr(0,f));c.ajax(c.extend({success:function(a){p&&(a=c("<div/>").append(a.replace(h,"")).find(p));b.set("content.text",a);l()},error:function(a,e,c){b.set("content.text",e+": "+c);l()},context:b},j,{url:u}));return a}});a.init()}function Z(b,a,c){var j=Math.ceil(a/2),h=Math.ceil(c/2),a={bottomright:[[0,0],[a,c],[a,0]],bottomleft:[[0,0],[a,0],[0,c]],topright:[[0,c],[a,0],[a,c]],topleft:[[0,0],[0,c],[a,c]],topcenter:[[0,c],[j,0],[a,c]],bottomcenter:[[0,0],[a,0],
[j,c]],rightcenter:[[0,0],[a,h],[0,c]],leftcenter:[[a,0],[a,c],[0,h]]};a.lefttop=a.bottomright;a.righttop=a.bottomleft;a.leftbottom=a.topright;a.rightbottom=a.topleft;return a[b.string()]}function $(b){function a(a,d,j){if(i.tip){var a=c.extend({},h.corner),d=j.adjusted,l=b.options.position.adjust.method.split(" "),o=l[0],l=l[1]||l[0],g={left:n,top:n,x:0,y:0},m,u={},p;if(h.corner.fixed!==q){if(o==="shift"&&a.precedance==="x"&&d.left&&a.y!=="center")a.precedance=a.precedance==="x"?"y":"x";else if(o===
"flip"&&d.left)a.x=a.x==="center"?d.left>0?"left":"right":a.x==="left"?"right":"left";if(l==="shift"&&a.precedance==="y"&&d.top&&a.x!=="center")a.precedance=a.precedance==="y"?"x":"y";else if(l==="flip"&&d.top)a.y=a.y==="center"?d.top>0?"top":"bottom":a.y==="top"?"bottom":"top";a.string()!==f.corner&&(f.top!==d.top||f.left!==d.left)&&h.update(a,n)}m=h.position(a,d);if(m.right!==H)m.left=-m.right;if(m.bottom!==H)m.top=-m.bottom;m.user=Math.max(0,k.offset);if(g.left=o==="shift"&&!!d.left)if(a.x==="center")u["margin-left"]=
g.x=m["margin-left"]-d.left;else{p=m.right!==H?[d.left,-m.left]:[-d.left,m.left];if((g.x=Math.max(p[0],p[1]))>p[0])j.left-=d.left,g.left=n;u[m.right!==H?"right":"left"]=g.x}if(g.top=l==="shift"&&!!d.top)if(a.y==="center")u["margin-top"]=g.y=m["margin-top"]-d.top;else{p=m.bottom!==H?[d.top,-m.top]:[-d.top,m.top];if((g.y=Math.max(p[0],p[1]))>p[0])j.top-=d.top,g.top=n;u[m.bottom!==H?"bottom":"top"]=g.y}i.tip.css(u).toggle(!(g.x&&g.y||a.x==="center"&&g.y||a.y==="center"&&g.x));j.left-=m.left.charAt?m.user:
o!=="shift"||g.top||!g.left&&!g.top?m.left:0;j.top-=m.top.charAt?m.user:l!=="shift"||g.left||!g.left&&!g.top?m.top:0;f.left=d.left;f.top=d.top;f.corner=a.string()}}function d(a,b,c){var b=!b?a[a.precedance]:b,d=l.hasClass(K),a=i.titlebar&&a.y==="top"?i.titlebar:i.content,b="border-"+b+"-width";l.addClass(K);a=parseInt(a.css(b),10);a=(c?a||parseInt(l.css(b),10):a)||0;l.toggleClass(K,d);return a}function j(a){var b=a.precedance==="y",c=u[b?"width":"height"],d=u[b?"height":"width"],f=a.string().indexOf("center")>
-1,g=c*(f?0.5:1),i=Math.pow,a=Math.round,h=Math.sqrt(i(g,2)+i(d,2)),g=[o/g*h,o/d*h];g[2]=Math.sqrt(i(g[0],2)-i(o,2));g[3]=Math.sqrt(i(g[1],2)-i(o,2));f=(h+g[2]+g[3]+(f?0:g[0]))/h;c=[a(f*d),a(f*c)];return{height:c[b?0:1],width:c[b?1:0]}}var h=this,k=b.options.style.tip,i=b.elements,l=i.tooltip,f={top:0,left:0,corner:""},u={width:k.width,height:k.height},p={},o=k.border||0,C=!!(c("<canvas />")[0]||{}).getContext;h.corner=y;h.mimic=y;h.border=o;h.offset=k.offset;h.size=u;b.checks.tip={"^position.my|style.tip.(corner|mimic|border)$":function(){h.init()||
h.destroy();b.reposition()},"^style.tip.(height|width)$":function(){u={width:k.width,height:k.height};h.create();h.update();b.reposition()},"^content.title.text|style.(classes|widget)$":function(){i.tip&&h.update()}};c.extend(h,{init:function(){var b=h.detectCorner()&&(C||c.browser.msie);b&&(h.create(),h.update(),l.unbind(".qtip-tip").bind("tooltipmove.qtip-tip",a));return b},detectCorner:function(){var a=k.corner,c=b.options.position,d=c.at,c=c.my.string?c.my.string():c.my;if(a===n||c===n&&d===n)return n;
else if(a===q)h.corner=new v.Corner(c);else if(!a.string)h.corner=new v.Corner(a),h.corner.fixed=q;return h.corner.string()!=="centercenter"},detectColours:function(){var a,d,f=i.tip.css({backgroundColor:"",border:""});a=h.corner;var j=a[a.precedance],n="border-"+j+"-color";d="border"+j.charAt(0)+j.substr(1)+"Color";var j=/rgba?\(0, 0, 0(, 0)?\)|transparent/i,g=c(document.body).css("color"),m=b.elements.content.css("color"),o=i.titlebar&&(a.y==="top"||a.y==="center"&&f.position().top+u.height/2+k.offset<
i.titlebar.outerHeight(1))?i.titlebar:i.content;l.addClass(K);p.fill=a=f.css("background-color");p.border=d=f[0].style[d]||l.css(n);if(!a||j.test(a))if(p.fill=o.css("background-color")||"transparent",j.test(p.fill))p.fill=l.css("background-color")||a;if(!d||j.test(d)||d===g)if(p.border=o.css(n)||"transparent",j.test(p.border)||p.border===m)p.border=d;c("*",f).add(f).css("background-color","transparent").css("border","");l.removeClass(K)},create:function(){var a=u.width,b=u.height;i.tip&&i.tip.remove();
i.tip=c("<div />",{"class":"ui-tooltip-tip"}).css({width:a,height:b}).prependTo(l);C?c("<canvas />").appendTo(i.tip)[0].getContext("2d").save():i.tip.html('<vml:shape coordorigin="0,0" style="display:inline-block; position:absolute; behavior:url(#default#VML);"></vml:shape><vml:shape coordorigin="0,0" style="display:inline-block; position:absolute; behavior:url(#default#VML);"></vml:shape>')},update:function(a,b){var f=i.tip,l=f.children(),w=u.width,g=u.height,m=k.mimic,s=Math.round,x,t,F;if(!a)a=
h.corner;m===n?m=a:(m=new v.Corner(m),m.precedance=a.precedance,m.x==="inherit"?m.x=a.x:m.y==="inherit"?m.y=a.y:m.x===m.y&&(m[a.precedance]=a[a.precedance]));x=m.precedance;h.detectColours();if(p.border!=="transparent"&&p.border!=="#123456"){o=d(a,y,q);if(k.border===0&&o>0)p.fill=p.border;h.border=o=k.border!==q?k.border:o}else h.border=o=0;t=Z(m,w,g);h.size=F=j(a);f.css(F);f=a.precedance==="y"?[s(m.x==="left"?o:m.x==="right"?F.width-w-o:(F.width-w)/2),s(m.y==="top"?F.height-g:0)]:[s(m.x==="left"?
F.width-w:0),s(m.y==="top"?o:m.y==="bottom"?F.height-g-o:(F.height-g)/2)];C?(l.attr(F),l=l[0].getContext("2d"),l.restore(),l.save(),l.clearRect(0,0,3E3,3E3),l.translate(f[0],f[1]),l.beginPath(),l.moveTo(t[0][0],t[0][1]),l.lineTo(t[1][0],t[1][1]),l.lineTo(t[2][0],t[2][1]),l.closePath(),l.fillStyle=p.fill,l.strokeStyle=p.border,l.lineWidth=o*2,l.lineJoin="miter",l.miterLimit=100,o&&l.stroke(),l.fill()):(t="m"+t[0][0]+","+t[0][1]+" l"+t[1][0]+","+t[1][1]+" "+t[2][0]+","+t[2][1]+" xe",f[2]=o&&/^(r|b)/i.test(a.string())?
parseFloat(c.browser.version,10)===8?2:1:0,l.css({antialias:""+(m.string().indexOf("center")>-1),left:f[0]-f[2]*Number(x==="x"),top:f[1]-f[2]*Number(x==="y"),width:w+o,height:g+o}).each(function(a){var b=c(this);b[b.prop?"prop":"attr"]({coordsize:w+o+" "+(g+o),path:t,fillcolor:p.fill,filled:!!a,stroked:!a}).css({display:o||a?"block":"none"});!a&&b.html()===""&&b.html('<vml:stroke weight="'+o*2+'px" color="'+p.border+'" miterlimit="1000" joinstyle="miter"  style="behavior:url(#default#VML); display:inline-block;" />')}));
b!==n&&h.position(a)},position:function(a){var b=i.tip,f={},u=Math.max(0,k.offset),p,g,m;if(k.corner===n||!b)return n;a=a||h.corner;p=a.precedance;g=j(a);m=[a.x,a.y];p==="x"&&m.reverse();c.each(m,function(b,h){var j,k;if(h==="center")j=p==="y"?"left":"top",f[j]="50%",f["margin-"+j]=-Math.round(g[p==="y"?"width":"height"]/2)+u;else{j=d(a,h,q);k=c.browser.mozilla;var m=a.y+(k?"":"-")+a.x;k=(k?"-moz-":c.browser.webkit?"-webkit-":"")+(k?"border-radius-"+m:"border-"+m+"-radius");k=parseInt((i.titlebar&&
a.y==="top"?i.titlebar:i.content).css(k),10)||parseInt(l.css(k),10)||0;f[h]=b?o?d(a,h):0:u+(k>j?k:0)}});f[a[p]]-=g[p==="x"?"width":"height"];b.css({top:"",bottom:"",left:"",right:"",margin:""}).css(f);return f},destroy:function(){i.tip&&i.tip.remove();l.unbind(".qtip-tip")}});h.init()}function aa(b){var a=this,d=b.options.show.modal,j=b.elements,h=j.tooltip,k=".qtipmodal"+b.id,i=c(document.body),l;b.checks.modal={"^show.modal.(on|blur)$":function(){a.init();j.overlay.toggle(h.is(":visible"))}};c.extend(a,
{init:function(){if(!d.on)return a;l=a.create();h.attr("is-modal-qtip",q).unbind(".qtipmodal").unbind(k).bind("tooltipshow.qtipmodal tooltiphide.qtipmodal",function(b,c,d){if((c=b.originalEvent)&&b.type==="tooltiphide"&&/mouse(leave|enter)/.test(c.type)&&c.relatedTarget.closest(l[0]).length)b.preventDefault();else a[b.type.replace("tooltip","")](b,d)}).bind("tooltipfocus.qtipmodal",function(a,b,c){l[0].style.zIndex=c}).bind("tooltipblur.qtipmodal",function(a){c("[is-modal-qtip]:visible").not(h).last().qtip("focus",
a)});d.escape&&c(A).unbind(k).bind("keydown"+k,function(a){a.keyCode===27&&h.hasClass(M)&&b.hide(a)});d.blur&&j.overlay.unbind(k).bind("click"+k,function(a){h.hasClass(M)&&b.hide(a)});return a},create:function(){var a=c("#qtip-overlay");if(a.length)return j.overlay=a;l=j.overlay=c("<div />",{id:"qtip-overlay",html:"<div></div>",mousedown:function(){return n}}).insertBefore(c(I).last());c(A).unbind(".qtipmodal").bind("resize.qtipmodal",function(){l.css({height:c(A).height(),width:c(A).width()})}).triggerHandler("resize");
return l},toggle:function(b,j,p){if(b&&b.isDefaultPrevented())return a;var b=d.effect,o=j?"show":"hide",v=l.is(":visible"),e=c("[is-modal-qtip]:visible").not(h);l||(l=a.create());if(l.is(":animated")&&v===j||!j&&e.length)return a;j?(l.css({left:0,top:0}),l.toggleClass("blurs",d.blur),i.delegate("*","focusin"+k,function(a){c(a.target).closest(I)[0]!==h[0]&&c("a, :input, img",h).add(h).focus()})):i.undelegate("*","focus"+k);l.stop(q,n);if(c.isFunction(b))b.call(l,j);else if(b===n)l[o]();else l.fadeTo(parseInt(p,
10)||90,j?1:0,function(){j||c(this).hide()});j||l.queue(function(a){l.css({left:"",top:""});a()});return a},show:function(b,c){return a.toggle(b,q,c)},hide:function(b,c){return a.toggle(b,n,c)},destroy:function(){var a=l;a&&((a=c("[is-modal-qtip]").not(h).length<1)?(j.overlay.remove(),c(A).unbind(".qtipmodal")):j.overlay.unbind(".qtipmodal"+b.id),i.undelegate("*","focus"+k));return h.removeAttr("is-modal-qtip").unbind(".qtipmodal")}});a.init()}function ba(b){var a=this,d=b.elements,j=d.tooltip,h=
".bgiframe-"+b.id;c.extend(a,{init:function(){d.bgiframe=c('<iframe class="ui-tooltip-bgiframe" frameborder="0" tabindex="-1" src="javascript:\'\';"  style="display:block; position:absolute; z-index:-1; filter:alpha(opacity=0); -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";"></iframe>');d.bgiframe.appendTo(j);j.bind("tooltipmove"+h,a.adjust)},adjust:function(){var a=b.get("dimensions"),c=b.plugins.tip,h=d.tip,f;f=parseInt(j.css("border-left-width"),10)||0;f={left:-f,top:-f};c&&h&&
(c=c.corner.precedance==="x"?["width","left"]:["height","top"],f[c[1]]-=h[c[0]]());d.bgiframe.css(f).css(a)},destroy:function(){d.bgiframe.remove();j.unbind(h)}});a.init()}var q=!0,n=!1,y=null,z,v,J,R={},B="ui-tooltip",Q="ui-widget",G="ui-state-disabled",I="div.qtip."+B,T=B+"-default",M=B+"-focus",W=B+"-hover",K=B+"-fluid",L="oldtitle",P=n;z=c.fn.qtip=function(b,a,d){var j=(""+b).toLowerCase(),h=y,k=j==="disable"?[q]:c.makeArray(arguments).slice(1),i=k[k.length-1],l=this[0]?c.data(this[0],"qtip"):
y;if(!arguments.length&&l||j==="api")return l;else if("string"===typeof b)return this.each(function(){var b=c.data(this,"qtip");if(!b)return q;if(i&&i.timeStamp)b.cache.event=i;if((j==="option"||j==="options")&&a)if(c.isPlainObject(a)||d!==H)b.set(a,d);else return h=b.get(a),n;else b[j]&&b[j].apply(b[j],k)}),h!==y?h:this;else if("object"===typeof b||!arguments.length)return l=O(c.extend(q,{},b)),z.bind.call(this,l,i)};z.bind=function(b,a){return this.each(function(d){function j(a){function b(){f.render(typeof a===
"object"||h.show.ready);k.show.add(k.hide).unbind(l)}if(f.cache.disabled)return n;f.cache.event=c.extend({},a);f.cache.target=a?c(a.target):[H];h.show.delay>0?(clearTimeout(f.timers.show),f.timers.show=setTimeout(b,h.show.delay),i.show!==i.hide&&k.hide.bind(i.hide,function(){clearTimeout(f.timers.show)})):b()}var h,k,i,l,f,d=c.isArray(b.id)?b.id[d]:b.id,d=!d||d===n||d.length<1||R[d]?z.nextid++:R[d]=d;l=".qtip-"+d+"-create";f=X.call(this,d,b);if(f===n)return q;h=f.options;c.each(v,function(){this.initialize===
"initialize"&&this(f)});k={show:h.show.target,hide:h.hide.target};i={show:c.trim(""+h.show.event).replace(/ /g,l+" ")+l,hide:c.trim(""+h.hide.event).replace(/ /g,l+" ")+l};/mouse(over|enter)/i.test(i.show)&&!/mouse(out|leave)/i.test(i.hide)&&(i.hide+=" mouseleave"+l);k.show.bind(i.show,j);(h.show.ready||h.prerender)&&j(a)})};v=z.plugins={Corner:function(b){b=(""+b).replace(/([A-Z])/," $1").replace(/middle/gi,"center").toLowerCase();this.x=(b.match(/left|right/i)||b.match(/center/)||["inherit"])[0].toLowerCase();
this.y=(b.match(/top|bottom|center/i)||["inherit"])[0].toLowerCase();this.precedance=b.charAt(0).search(/^(t|b)/)>-1?"y":"x";this.string=function(){return this.precedance==="y"?this.y+this.x:this.x+this.y};this.abbreviation=function(){var a=this.x.substr(0,1),b=this.y.substr(0,1);return a===b?a:a==="c"||a!=="c"&&b!=="c"?b+a:a+b}},offset:function(b,a,d){function j(a,b){h.left+=b*a.scrollLeft();h.top+=b*a.scrollTop()}var h=b.offset(),b=a,k=0,i=document.body,l;if(b){do if(b.css("position")!=="static"&&
(l=b[0]===i?{left:parseInt(b.css("left"),10)||0,top:parseInt(b.css("top"),10)||0}:b.position(),h.left-=l.left+(parseInt(b.css("borderLeftWidth"),10)||0),h.top-=l.top+(parseInt(b.css("borderTopWidth"),10)||0),k++),b[0]===i)break;while(b=b.offsetParent());(a[0]!==i||k>1)&&j(a,1);(v.iOS<4.1&&v.iOS>3.1||!v.iOS&&d)&&j(c(A),-1)}return h},iOS:parseFloat((""+(/CPU.*OS ([0-9_]{1,3})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||[0,""])[1]).replace("undefined","3_2").replace("_","."))||n,fn:{attr:function(b,
a){if(this.length){var d=this[0],j=c.data(d,"qtip");if(b==="title")if(arguments.length<2)return c.attr(d,L);else if(typeof j==="object")return j&&j.rendered&&j.options.content.attr==="title"&&j.cache.attr&&j.set("content.text",a),c.fn.attr_replacedByqTip.apply(this,arguments),c.attr(d,L,c.attr(d,"title")),this.removeAttr("title")}},clone:function(){c([]);return c.fn.clone_replacedByqTip.apply(this,arguments).filter("[oldtitle]").each(function(){c.attr(this,"title",c.attr(this,L));this.removeAttribute(L)}).end()},
remove:c.ui?y:function(b,a){c(this).each(function(){a||(!b||c.filter(b,[this]).length)&&c("*",this).add(this).each(function(){c(this).triggerHandler("remove")})})}}};c.each(v.fn,function(b,a){if(!a)return q;var d=c.fn[b+"_replacedByqTip"]=c.fn[b];c.fn[b]=function(){return a.apply(this,arguments)||d.apply(this,arguments)}});z.version="2.0.0pre";z.nextid=0;z.inactiveEvents="click dblclick mousedown mouseup mousemove mouseleave mouseenter".split(" ");z.zindex=15E3;z.defaults={prerender:n,id:n,overwrite:q,
content:{text:q,attr:"title",title:{text:n,button:n}},position:{my:"top left",at:"bottom right",target:n,container:n,viewport:n,adjust:{x:0,y:0,mouse:q,resize:q,method:"flip flip"},effect:function(b,a){c(this).stop().animate(a,200)}},show:{target:n,event:"mouseenter",effect:q,delay:90,solo:n,ready:n},hide:{target:n,event:"mouseleave",effect:q,delay:0,fixed:n,inactive:n,leave:"window",distance:n},style:{classes:"",widget:n,width:n},events:{render:y,move:y,show:y,hide:y,toggle:y,focus:y,blur:y}};v.ajax=
function(b){var a=b.plugins.ajax;return"object"===typeof a?a:b.plugins.ajax=new Y(b)};v.ajax.initialize="render";v.ajax.sanitize=function(b){var a=b.content;if(a&&"ajax"in a){a=a.ajax;if(typeof a!=="object")a=b.content.ajax={url:a};if("boolean"!==typeof a.once&&a.once)a.once=!!a.once}};c.extend(q,z.defaults,{content:{ajax:{loading:q,once:q}}});v.tip=function(b){var a=b.plugins.tip;return"object"===typeof a?a:b.plugins.tip=new $(b)};v.tip.initialize="render";v.tip.sanitize=function(b){var a=b.style;
if(a&&"tip"in a){a=b.style.tip;if(typeof a!=="object")b.style.tip={corner:a};if(!/string|boolean/i.test(typeof a.corner))a.corner=q;typeof a.width!=="number"&&delete a.width;typeof a.height!=="number"&&delete a.height;typeof a.border!=="number"&&a.border!==q&&delete a.border;typeof a.offset!=="number"&&delete a.offset}};c.extend(q,z.defaults,{style:{tip:{corner:q,mimic:n,width:6,height:6,border:q,offset:0}}});v.imagemap=function(b,a){function d(b,c){for(var d=0,f=1,h=1,i=0,j=0,g=b.width,k=b.height;g>
0&&k>0&&f>0&&h>0;){g=Math.floor(g/2);k=Math.floor(k/2);a.x==="left"?f=g:a.x==="right"?f=b.width-g:f+=Math.floor(g/2);a.y==="top"?h=k:a.y==="bottom"?h=b.height-k:h+=Math.floor(k/2);for(d=c.length;d--;){if(c.length<2)break;i=c[d][0]-b.offset.left;j=c[d][1]-b.offset.top;(a.x==="left"&&i>=f||a.x==="right"&&i<=f||a.x==="center"&&(i<f||i>b.width-f)||a.y==="top"&&j>=h||a.y==="bottom"&&j<=h||a.y==="center"&&(j<h||j>b.height-h))&&c.splice(d,1)}}return{left:c[0][0],top:c[0][1]}}b.jquery||(b=c(b));var j=b.attr("shape").toLowerCase(),
h=b.attr("coords").split(","),k=[],i=c('img[usemap="#'+b.parent("map").attr("name")+'"]'),l=i.offset(),f={width:0,height:0,offset:{top:1E10,right:0,bottom:0,left:1E10}},n=0,p=0;l.left+=Math.ceil((i.outerWidth()-i.width())/2);l.top+=Math.ceil((i.outerHeight()-i.height())/2);if(j==="poly")for(n=h.length;n--;){p=[parseInt(h[--n],10),parseInt(h[n+1],10)];if(p[0]>f.offset.right)f.offset.right=p[0];if(p[0]<f.offset.left)f.offset.left=p[0];if(p[1]>f.offset.bottom)f.offset.bottom=p[1];if(p[1]<f.offset.top)f.offset.top=
p[1];k.push(p)}else k=c.map(h,function(a){return parseInt(a,10)});switch(j){case "rect":f={width:Math.abs(k[2]-k[0]),height:Math.abs(k[3]-k[1]),offset:{left:k[0],top:k[1]}};break;case "circle":f={width:k[2]+2,height:k[2]+2,offset:{left:k[0],top:k[1]}};break;case "poly":c.extend(f,{width:Math.abs(f.offset.right-f.offset.left),height:Math.abs(f.offset.bottom-f.offset.top)}),f.offset=a.string()==="centercenter"?{left:f.offset.left+f.width/2,top:f.offset.top+f.height/2}:d(f,k.slice()),f.width=f.height=
0}f.offset.left+=l.left;f.offset.top+=l.top;return f};v.svg=function(b){var a=c(document),d=b[0],b={width:0,height:0,offset:{top:1E10,left:1E10}},j,h,k;if(d.getBBox&&d.parentNode){j=d.getBBox();h=d.getScreenCTM();d=d.farthestViewportElement||d;if(!d.createSVGPoint)return b;d=d.createSVGPoint();d.x=j.x;d.y=j.y;k=d.matrixTransform(h);b.offset.left=k.x;b.offset.top=k.y;d.x+=j.width;d.y+=j.height;k=d.matrixTransform(h);b.width=k.x-b.offset.left;b.height=k.y-b.offset.top;b.offset.left+=a.scrollLeft();
b.offset.top+=a.scrollTop()}return b};v.modal=function(b){var a=b.plugins.modal;return"object"===typeof a?a:b.plugins.modal=new aa(b)};v.modal.initialize="render";v.modal.sanitize=function(b){if(b.show)if(typeof b.show.modal!=="object")b.show.modal={on:!!b.show.modal};else if(typeof b.show.modal.on==="undefined")b.show.modal.on=q};c.extend(q,z.defaults,{show:{modal:{on:n,effect:q,blur:q,escape:q}}});v.bgiframe=function(b){var a=c.browser,d=b.plugins.bgiframe;if(c("select, object").length<1||!(a.msie&&
a.version.charAt(0)==="6"))return n;return"object"===typeof d?d:b.plugins.bgiframe=new ba(b)};v.bgiframe.initialize="render"})(jQuery,window);
