(function(e){e.fn.popeye=function(B){function g(e,g){window.console&&window.console.log&&c.debug&&(g=="info"&&window.console.info?window.console.info(e):g=="warn"&&window.console.warn?window.console.warn(e):window.console.log(e))}var c=e.extend({},e.fn.popeye.defaults,B);return this.each(function(){function n(a,k){var k=k||false,a=a||d,i={backgroundImage:"url("+q[a].src+")"},h={height:"+=0"};if(m)r(),f.fadeTo(c.duration/2,0).animate(R,{queue:false,duration:c.duration,easing:c.easing,complete:function(){m=
false;g("$.fn.showThumb: Entering COMPACT MODE","info");b.removeClass(C);b.css("z-index","").parent().css("z-index","");D.removeClass("ppy-hidden");E.addClass("ppy-hidden");n();e(this).fadeTo(c.duration/2,1)}});else{if(k){o.addClass(v);f.fadeTo(c.duration/2,0);var F=new Image;F.onload=function(){g("$.fn.popeye.showThumb: Thumbnail "+a+" loaded","info");o.removeClass(v);f.animate(h,1,"linear",function(){f.css(i);e(this).fadeTo(c.duration/2,1);c.caption=="hover"&&w?x(p[a]):c.caption=="permanent"&&c.caption&&
K.html(p[a]);G()});F.onload=function(){}};F.src=q[a].src}else f.css(i),G(),x(p[a],true);var j=new Image;j.onload=function(){g("$.fn.popeye.showThumb: Image "+a+" loaded","info");j.onload=function(){}};j.src=s[a].href}}function u(a){a=a||d;o.addClass(v);f.fadeTo(c.duration/2,0);e("."+C).css("z-index",c.zindex-1);b.css("z-index",c.zindex).parent().css("z-index",c.zindex);var k=new Image;k.onload=function(){o.removeClass(v);var h={width:k.width,height:k.height},j={backgroundImage:"url("+s[a].href+")",
backgroundPosition:"left top"};r();f.animate(h,{queue:false,duration:c.duration,easing:c.easing,complete:function(){c.navigation=="hover"&&w&&H();m=true;g("$.fn.popeye.showImage: Entering ENLARGED MODE","info");b.addClass(C);E.removeClass("ppy-hidden");D.addClass("ppy-hidden");G();e(this).css(j).fadeTo(c.duration/2,1);x(p[a]);var f;f=d;var h=new Image,k=new Image,l=f;l<i-1?l++:l=0;h.src=s[l].href;l=f;l<=0?l=i-1:l--;k.src=s[l].href}})};k.src=s[a].href}function G(a){a=a||d;S.text(i);T.text(a+1);g("$.fn.popeye.updateCounter: Displaying image "+
(a+1)+" of "+i)}function H(){y.stop().fadeTo(150,c.opacity)}function I(){y.stop().fadeTo(150,0)}function x(a,b){a&&c.caption?(c.caption&&K.html(a),g("$.fn.popeye.showCaption -> ppyCaptionWrap.outerHeight(true): "+z.outerHeight(true)),h.css({visibility:"visible"}),c.caption==="permanent"&&!m?h.css(U):h.animate({height:z.outerHeight(true)},{queue:false,duration:90,easing:c.easing})):!a&&!b&&r()}function r(){var a={visibility:"hidden",overflow:"hidden"};h.animate({height:"0px"},{queue:false,duration:90,
easing:c.easing,complete:function(){h.css(a)}})}function L(){d<i-1?d++:d=0;m?u(d):n(d,true);return d}function B(){M.css(V);b.css(W);b.wrap(M);o=f.wrap(o).parent();z=h.wrapInner(z).children().eq(0);n();c.navigation=="hover"&&(I(),b.hover(function(){H()},function(){I()}),y.hover(function(){H()},function(){I()}));N?(b.addClass(X),O.remove(),P.remove(),j.remove(),A.remove(),Y.remove()):(O.click(function(a){a.stopPropagation();d<=0?d=i-1:d--;m?u(d):n(d,true)}),P.click(function(a){a.stopPropagation();L()}));
c.caption=="hover"&&(r(),b.hover(function(){x(p[d])},function(){r(true)}));D.click(function(a){a.stopPropagation();u();return false});E.click(function(a){a.stopPropagation();n(d);return false});f.click(function(){m?n(d):u()});j.click(function(a){a.stopPropagation();A.removeClass("ppy-hidden");j.addClass("ppy-hidden");slideshow=window.setInterval(function(){L()},c.slidespeed);return false});A.click(function(a){a.stopPropagation();j.removeClass("ppy-hidden");A.addClass("ppy-hidden");window.clearInterval(slideshow);
return false});b.mouseenter(function(){w=true}).mouseleave(function(){w=false});c.autoslide&&j.trigger("click")}e(this).addClass("ppy-active");for(var b=e(this),q=b.find(".ppy-imglist > li > a > img"),s=b.find(".ppy-imglist > li > a"),i=q.length,N=i==1?true:false,w=false,m=false,d=0,C="ppy-expanded",v="ppy-loading",X="ppy-single-image",M=e('<div class="ppy-placeholder"></div>'),o=e('<div class="ppy-stagewrap"></div>'),z=e('<div class="ppy-captionwrap"></div>'),J=b.find(".ppy-outer"),f=b.find(".ppy-stage"),
y=b.find(".ppy-nav"),O=b.find(".ppy-prev"),P=b.find(".ppy-next"),D=b.find(".ppy-switch-enlarge"),E=b.find(".ppy-switch-compact").addClass("ppy-hidden"),j=b.find(".ppy-play"),A=b.find(".ppy-pause").addClass("ppy-hidden"),h=b.find(".ppy-caption"),K=b.find(".ppy-text"),Y=b.find(".ppy-counter"),T=b.find(".ppy-current"),S=b.find(".ppy-total"),W={position:"absolute",width:"auto",height:"auto",margin:0,top:0,left:c.direction=="right"?0:"auto",right:c.direction=="left"?0:"auto"},R={height:f.height(),width:f.width()},
U={height:h.height()},V={height:c.caption=="hover"?J.outerHeight():b.outerHeight(),width:c.caption=="hover"?J.outerWidth():b.outerWidth(),"float":b.css("float"),"margin-top":b.css("margin-top"),"margin-right":b.css("margin-right"),"margin-bottom":b.css("margin-bottom"),"margin-left":b.css("margin-left")},p=[],t=0;t<q.length;t++){var Q=b.find(".ppy-imglist li").eq(t).find(".ppy-extcaption");p[t]=Q.length>0?Q.html():q[t].alt}!f.length||!y.length||!J.length?g("$.fn.popeye: Incorrect HTML structure",
"warn"):i===0?g("$.fn.popeye: No images found","warn"):(N?g("$.fn.popeye -> SingleImageMode started"):g("$.fn.popeye -> "+i+" thumbnails found."),B())})};e.fn.popeye.defaults={navigation:"hover",caption:"hover",zindex:1E4,direction:"right",duration:240,opacity:0.8,easing:"swing",slidespeed:2E3,autoslide:false,debug:false}})(jQuery);jQuery("head").append('<style type="text/css"> .ppy-imglist { position: absolute; top: -1000em; left: -1000em; } </style>');
