(function(e){e.fn.popeye=function(P){function g(j,n){if(window.console&&window.console.log&&b.debug)if(n=="info"&&window.console.info)window.console.info(j);else n=="warn"&&window.console.warn?window.console.warn(j):window.console.log(j)}var b=e.extend({},e.fn.popeye.defaults,P);return this.each(function(){function j(c,h){h=h||false;c=c||d;var w={backgroundImage:"url("+r[c].src+")"},B={height:"+=0"};if(o){s();f.fadeTo(b.duration/2,0).animate(Q,{queue:false,duration:b.duration,easing:b.easing,complete:function(){o=
false;g("$.fn.showThumb: Entering COMPACT MODE","info");a.removeClass(C);a.css("z-index","");D.removeClass("ppy-hidden");E.addClass("ppy-hidden");j();e(this).fadeTo(b.duration/2,1)}})}else{if(h){p.addClass(x);f.fadeTo(b.duration/2,0);var i=new Image;i.onload=function(){g("$.fn.popeye.showThumb: Thumbnail "+c+" loaded","info");p.removeClass(x);f.animate(B,1,"linear",function(){f.css(w);e(this).fadeTo(b.duration/2,1);if(b.caption=="hover")y(q[c]);else b.caption=="permanent"&&b.caption&&J.html(q[c]);
F()});i.onload=function(){}};i.src=r[c].src}else{f.css(w);F();y(q[c],true)}var t=new Image;t.onload=function(){g("$.fn.popeye.showThumb: Image "+c+" loaded","info");t.onload=function(){}};t.src=u[c].href}}function n(c){c=c||d;p.addClass(x);f.fadeTo(b.duration/2,0);e("."+C).css("z-index",b.zindex-1);a.css("z-index",b.zindex);var h=new Image;h.onload=function(){p.removeClass(x);var w={width:h.width,height:h.height},B={backgroundImage:"url("+u[c].href+")",backgroundPosition:"left top"};s();f.animate(w,
{queue:false,duration:b.duration,easing:b.easing,complete:function(){b.navigation=="hover"&&G();o=true;g("$.fn.popeye.showImage: Entering ENLARGED MODE","info");a.addClass(C);E.removeClass("ppy-hidden");D.addClass("ppy-hidden");F();e(this).css(B).fadeTo(b.duration/2,1);y(q[c]);var i=void 0;i=i||d;var t=new Image,R=new Image,k=i;if(k<l-1)k++;else k=0;t.src=u[i].href[k];k=i;if(k<=0)k=l-1;else k--;R.src=u[i].href[k]}})};h.src=u[c].href}function F(c){c=c||d;S.text(l);T.text(c+1);g("$.fn.popeye.updateCounter: Displaying image "+
(c+1)+" of "+l)}function G(){z.stop().fadeTo(150,b.opacity)}function H(){z.stop().fadeTo(150,0)}function y(c,h){if(c&&b.caption){b.caption&&J.html(c);g("$.fn.popeye.showCaption -> ppyCaptionWrap.outerHeight(true): "+A.outerHeight(true));m.css({visibility:"visible"});b.caption==="permanent"&&!o?m.css(U):m.animate({height:A.outerHeight(true)},{queue:false,duration:90,easing:b.easing})}else!c&&!h&&s()}function s(){var c={visibility:"hidden",overflow:"hidden"};m.animate({height:"0px"},{queue:false,duration:90,
easing:b.easing,complete:function(){m.css(c)}})}function V(){if(d<=0)d=l-1;else d--;o?n(d):j(d,true);return d}function W(){if(d<l-1)d++;else d=0;o?n(d):j(d,true);return d}function X(){K.css(Y);a.css(Z);a.wrap(K);p=f.wrap(p).parent();A=m.wrapInner(A).children().eq(0);j();if(b.navigation=="hover"){H();a.hover(function(){G()},function(){H()});z.hover(function(){G()},function(){H()})}if(L){a.addClass($);M.remove();N.remove();aa.remove()}else{M.click(V);N.click(W)}if(b.caption=="hover"){s();a.hover(function(){y(q[d])},
function(){s(true)})}D.click(function(){n();return false});E.click(function(){j(d);return false})}e(this).addClass("ppy-active");for(var a=e(this),r=a.find(".ppy-imglist > li > a > img"),u=a.find(".ppy-imglist > li > a"),l=r.length,L=l==1?true:false,o=false,d=0,C="ppy-expanded",x="ppy-loading",$="ppy-single-image",K=e('<div class="ppy-placeholder"></div>'),p=e('<div class="ppy-stagewrap"></div>'),A=e('<div class="ppy-captionwrap"></div>'),I=a.find(".ppy-outer"),f=a.find(".ppy-stage"),z=a.find(".ppy-nav"),
M=a.find(".ppy-prev"),N=a.find(".ppy-next"),D=a.find(".ppy-switch-enlarge"),E=a.find(".ppy-switch-compact").addClass("ppy-hidden"),m=a.find(".ppy-caption"),J=a.find(".ppy-text"),aa=a.find(".ppy-counter"),T=a.find(".ppy-current"),S=a.find(".ppy-total"),Z={position:"absolute",width:"auto",height:"auto",margin:0,top:0,left:b.direction=="right"?0:"auto",right:b.direction=="left"?0:"auto"},Q={height:f.height(),width:f.width()},U={height:m.height()},Y={height:b.caption=="hover"?I.outerHeight():a.outerHeight(),
width:b.caption=="hover"?I.outerWidth():a.outerWidth(),"float":a.css("float"),marginTop:a.css("margin-top"),marginRight:a.css("margin-right"),marginBottom:a.css("margin-bottom"),marginLeft:a.css("margin-left")},q=[],v=0;v<r.length;v++){var O=a.find(".ppy-imglist li").eq(v).find(".ppy-extcaption");q[v]=O.length>0?O.html():r[v].alt}if(!f.length||!z.length||!I.length)g("$.fn.popeye: Incorrect HTML structure","warn");else if(l===0)g("$.fn.popeye: No images found","warn");else{L?g("$.fn.popeye -> SingleImageMode started"):
g("$.fn.popeye -> "+l+" thumbnails found.");X()}})};e.fn.popeye.defaults={navigation:"hover",caption:"hover",zindex:1E4,direction:"right",duration:240,opacity:0.8,easing:"swing",debug:false}})(jQuery);jQuery("head").append('<style type="text/css"> .ppy-imglist { position: absolute; top: -1000em; left: -1000em; } </style>');
