(function(a){a.fn.bMap=function(b){eachOptions=b;return this.each(function(){obj=a(this);var b={mapCenter:[51,0],mapZoom:1,mapCanvas:obj.attr("id"),mapSidebar:"none",mapLayerbar:"none",mapType:google.maps.MapTypeId.ROADMAP,loadMsg:"<h2>Loading...</h2>"},b=a.extend(b,eachOptions);obj.data("bMap",new bMap(b))})}})(jQuery);
function bMap(a){a=$.extend({mapCenter:[51,0],mapZoom:1,mapCanvas:"map",mapSidebar:"none",mapLayerbar:"none",mapType:google.maps.MapTypeId.ROADMAP,loadMsg:"<h2>Loading...</h2>"},a);this.mapSidebar=a.mapSidebar;this.useSidebar=this.mapSidebar!="none"?!0:!1;this.mapLayerbar=a.mapLayerbar;this.useLayerbar=this.mapLayerbar!="none"?!0:!1;this.LyrArr=[];var b={zoom:a.mapZoom,center:new google.maps.LatLng(a.mapCenter[0],a.mapCenter[1]),mapTypeId:a.mapType};this.map=new google.maps.Map(document.getElementById(a.mapCanvas),
b);this.mapCanvas=a.mapCanvas;$("#"+this.mapCanvas).append("<div id='"+this.mapCanvas+"bMapLoadMsg' class='bMapLoadMsg'>"+a.loadMsg+"</div>");$("#"+this.mapCanvas+"bMapLoadMsg").css("left",$("#map").width()/2-50);$("#"+this.mapCanvas+"bMapLoadMsg").css("top",$("#map").height()/2-50);if(a.icons)this.icons=a.icons;a.markers&&this.insertMarkers(a.markers);this.infoWindow=new google.maps.InfoWindow;this.geoCoder=new google.maps.Geocoder}
bMap.prototype.insertMarkers=function(a){tmpThis=this;var b=tmpThis.LyrArr.length,a=$.extend({name:"Layer"+b,type:"marker",visible:"true"},a);tmpThis.LyrArr[b]=a;tmpThis.LyrArr[b].toggleLayer=function(){if(this.visible!="false"){this.visible="false";i=0;for(j=this.data.length;i<j;i++)this.data[i].setMap(null),tmpThis.infoWindow.close();$("#bMapLyr"+b).addClass("bLyrHide");$("#"+tmpThis.mapSidebar+' div[rel^="'+b+'"]').slideUp("fast");return!1}else{this.visible="true";i=0;for(j=this.data.length;i<
j;i++)this.data[i].setMap(tmpThis.map);$("#bMapLyr"+b).removeClass("bLyrHide");$("#"+tmpThis.mapSidebar+' div[rel^="'+b+'"]').slideDown("fast");return!0}};jQuery.each(a.data,function(a,c){var e=new google.maps.LatLng(c.lat,c.lng);tmpThis.LyrArr[b].data[a]=c.icon?new google.maps.Marker({position:e,map:tmpThis.map,icon:c.icon}):new google.maps.Marker({position:e,map:tmpThis.map});if(c.title){var f="<h2>"+c.title+"</h2>";c.body&&(f+=c.body);google.maps.event.addListener(tmpThis.LyrArr[b].data[a],"click",
function(){tmpThis.infoWindow.setContent(f);tmpThis.infoWindow.open(tmpThis.map,tmpThis.LyrArr[b].data[a]);$("#"+tmpThis.mapSidebar+" div").removeClass("bSideSelect");$("#"+tmpThis.mapSidebar+' div[rel="'+b+" "+a+'"]').addClass("bSideSelect");var c=$("#"+tmpThis.mapSidebar).scrollTop()+$("#"+tmpThis.mapSidebar+' div[rel="'+b+" "+a+'"]').position().top-($("#"+tmpThis.mapSidebar).offset().top+$("#"+tmpThis.mapSidebar).height()/2);$("#"+tmpThis.mapSidebar).animate({scrollTop:c},500)});google.maps.event.addListener(tmpThis.LyrArr[b].data[a],
"infowindowclose",function(){$("#"+tmpThis.mapSidebar+' div[rel="'+b+" "+a+'"]').removeClass("bSideSelect")})}tmpThis.useSidebar&&$('<div rel="'+b+" "+a+'">'+c.title+"</div>").click(function(){google.maps.event.trigger(tmpThis.LyrArr[b].data[a],"click");$("#"+tmpThis.mapSidebar+" div").removeClass("bSideSelect");$(this).addClass("bSideSelect")}).appendTo("#"+tmpThis.mapSidebar)});if(a.visible!="true"){i=0;for(j=tmpThis.LyrArr[b].data.length;i<j;i++)tmpThis.LyrArr[b].data[i].setMap(null),$("#"+tmpThis.mapSidebar+
' div[rel^="'+b+'"]').hide();$("#bMapLyr"+b).addClass("bLyrHide");return!1}this.refreshLayerbar();return this};bMap.prototype.AJAXMarkers=function(a){var a=$.extend({serviceURL:"mapService.php",action:"getMarkers",vars:[],options:{}},a),b=this;$("#"+this.mapCanvas+"bMapLoadMsg").show();$.getJSON(a.serviceURL,{action:a.action,vars:a.vars},function(d){a.options=$.extend(d,a.options);b.insertMarkers(a.options);$("#"+b.mapCanvas+"bMapLoadMsg").hide()});return this};
bMap.prototype.insertLine=function(a){tmpThis=this;var b=tmpThis.LyrArr.length,a=$.extend({name:"Layer"+b,type:"line",visible:"true",color:"#00F",weight:5,opacity:1},a);tmpThis.LyrArr[b]=a;tmpThis.LyrArr[b].toggleLayer=function(){return this.visible!="false"?(this.visible="false",this.data.setMap(null),$("#bMapLyr"+b).addClass("bLyrHide"),!1):(this.visible="true",this.data.setMap(tmpThis.map),$("#bMapLyr"+b).removeClass("bLyrHide"),!0)};var d=[];jQuery.each(a.data,function(a,b){d.push(new google.maps.LatLng(b.lat,
b.lng))});tmpThis.LyrArr[b].data=new google.maps.Polyline({path:d,strokeColor:tmpThis.LyrArr[b].color,strokeOpacity:parseFloat(tmpThis.LyrArr[b].opacity),strokeWeight:parseInt(tmpThis.LyrArr[b].weight)});tmpThis.LyrArr[b].data.setMap(tmpThis.map);a.visible!="true"&&tmpThis.LyrArr[b].data.setMap(null);this.refreshLayerbar();return this};
bMap.prototype.AJAXLine=function(a){var a=$.extend({serviceURL:"mapService.php",action:"getLine",vars:[]},a),b=this;$("#"+this.mapCanvas+"bMapLoadMsg").show();$.post(a.serviceURL,{action:a.action,vars:a.vars},function(a){b.insertLine(a);$("#"+b.mapCanvas+"bMapLoadMsg").hide()},"json");return this};
bMap.prototype.insertPolygon=function(a){tmpThis=this;var b=tmpThis.LyrArr.length,a=$.extend({name:"Layer"+b,type:"polygon",visible:"true",color:"#00F",weight:5,opacity:0.5},a);tmpThis.LyrArr[b]=a;tmpThis.LyrArr[b].toggleLayer=function(){return this.visible!="false"?(this.visible="false",this.data.setMap(null),$("#bMapLyr"+b).addClass("bLyrHide"),!1):(this.visible="true",this.data.setMap(tmpThis.map),$("#bMapLyr"+b).removeClass("bLyrHide"),!0)};var d=[];jQuery.each(a.data,function(a,b){d.push(new google.maps.LatLng(b.lat,
b.lng))});tmpThis.LyrArr[b].data=new google.maps.Polygon({path:d,strokeColor:tmpThis.LyrArr[b].color,strokeOpacity:1,strokeWeight:parseInt(tmpThis.LyrArr[b].weight),fillColor:tmpThis.LyrArr[b].color,fillOpacity:parseFloat(tmpThis.LyrArr[b].opacity)});tmpThis.LyrArr[b].data.setMap(tmpThis.map);a.visible!="true"&&tmpThis.LyrArr[b].data.setMap(null);this.refreshLayerbar();return this};
bMap.prototype.AJAXPolygon=function(a){var a=$.extend({serviceURL:"mapService.php",action:"getPolygon",vars:[]},a),b=this;$("#"+this.mapCanvas+"bMapLoadMsg").show();$.post(a.serviceURL,{action:a.action,vars:a.vars},function(a){b.insertPolygon(a);$("#"+b.mapCanvas+"bMapLoadMsg").hide()},"json");return this};
bMap.prototype.removeAllLayers=function(){i=0;for(j=this.LyrArr.length;i<j;i++){if(this.LyrArr[i].type=="marker"){i2=0;for(j2=this.LyrArr[i].data.length;i2<j2;i2++)this.LyrArr[i].data[i2].setMap(null);this.infoWindow.close()}else this.LyrArr[i].data.setMap(null);this.LyrArr[i].data=0;this.useSidebar&&$("#"+this.mapSidebar+' div[rel^="'+i+'"]').remove()}this.LyrArr.length=0;this.refreshLayerbar();return this};
bMap.prototype.removeLayer=function(a){if(this.LyrArr[a].type=="marker"){i2=0;for(j2=this.LyrArr[a].data.length;i2<j2;i2++)this.LyrArr[a].data[i2].setMap(null)}else this.LyrArr[a].data.setMap(null);this.LyrArr[a].data=0;this.useSidebar&&$("#"+this.mapSidebar+' div[rel^="'+a+'"]').remove();this.refreshLayerbar();return this};
bMap.prototype.popLayer=function(){var a=this.LyrArr.length-1,b=this.LyrArr.pop();if(b.type=="marker"){i2=0;for(j2=b.data.length;i2<j2;i2++)b.data[i2].setMap(null)}else b.data.setMap(null);b.data=0;this.useSidebar&&$("#"+this.mapSidebar+' div[rel^="'+a+'"]').remove();this.refreshLayerbar();return this};
bMap.prototype.shiftLayer=function(){i3=0;for(j3=this.LyrArr.length;i3<j3;i3++)if(this.LyrArr[i3].data!=0){var a=i3;break}if(this.LyrArr[a].type=="marker"){i2=0;for(j2=this.LyrArr[a].data.length;i2<j2;i2++)this.LyrArr[a].data[i2].setMap(null)}else this.LyrArr[a].data.setMap(null);this.LyrArr[a].data=0;this.LyrArr[a].name="";this.LyrArr[a].type="";this.useSidebar&&$("#"+this.mapSidebar+' ^"'+a+'"]').remove();this.refreshLayerbar();return this};
bMap.prototype.refreshLayerbar=function(){if(this.mapLayerbar){var a=this;$("#"+this.mapLayerbar).html("");for(var b=0,d=this.LyrArr.length;b<d;b++)this.LyrArr[b].data!=0&&$("<div "+(this.LyrArr[b].visible!="false"?"":"class='bLyrHide' ")+"id='bMapLyr"+b+"' rel='"+b+"'>"+this.LyrArr[b].name+"</div>").click(function(){a.LyrArr[$(this).attr("rel")].toggleLayer()}).appendTo("#"+this.mapLayerbar)}};
bMap.prototype.centerAtAddress=function(a){var b=this;this.geoCoder.geocode({address:a},function(a,c){c==google.maps.GeocoderStatus.OK&&b.map.setCenter(a[0].geometry.location)});return this};
